/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { DocumentController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('DocumentController', () => {
  let controller : DocumentController;

  beforeAll(() => {
    controller = new DocumentController(testClient);
  });

  it('should Test listDocuments', async () => {
    const response = await makeApiCall(
      () => controller.listDocuments(
        undefined,
        undefined,
        undefined,
        undefined
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'X-After-Cursor': ['', false],
      'X-Per-Page': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
