/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { InvoiceController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('InvoiceController', () => {
  let controller : InvoiceController;

  beforeAll(() => {
    controller = new InvoiceController(testClient);
  });

  it('should Test listInvoices', async () => {
    const response = await makeApiCall(
      () => controller.listInvoices(undefined, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'X-After-Cursor': ['', false],
      'X-Per-Page': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test createInvoice', async () => {
    const response = await makeApiCall(
      () => controller.createInvoice(undefined, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
