/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { LedgerController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('LedgerController', () => {
  let controller : LedgerController;

  beforeAll(() => {
    controller = new LedgerController(testClient);
  });

  it('should Test listLedgers', async () => {
    const response = await makeApiCall(
      () => controller.listLedgers(undefined, undefined, undefined, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'X-After-Cursor': ['', false],
      'X-Per-Page': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test createLedger', async () => {
    const response = await makeApiCall(
      () => controller.createLedger(undefined, undefined)
    );

    expect(response.statusCode).toBe(201);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
