/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { LedgerAccountCategoryController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('LedgerAccountCategoryController', () => {
  let controller : LedgerAccountCategoryController;

  beforeAll(() => {
    controller = new LedgerAccountCategoryController(testClient);
  });

  it('should Test listLedgerAccountCategories', async () => {
    const response = await makeApiCall(
      () => controller.listLedgerAccountCategories(
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'X-After-Cursor': ['', false],
      'X-Per-Page': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test createLedgerAccountCategory', async () => {
    const response = await makeApiCall(
      () => controller.createLedgerAccountCategory(undefined, undefined)
    );

    expect(response.statusCode).toBe(201);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
