/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { LedgerableEventController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('LedgerableEventController', () => {
  let controller : LedgerableEventController;

  beforeAll(() => {
    controller = new LedgerableEventController(testClient);
  });

  it('should Test createLedgerableEvent', async () => {
    const response = await makeApiCall(
      () => controller.createLedgerableEvent(undefined, undefined)
    );

    expect(response.statusCode).toBe(201);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
