/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { PaymentOrderController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('PaymentOrderController', () => {
  let controller : PaymentOrderController;

  beforeAll(() => {
    controller = new PaymentOrderController(testClient);
  });

  it('should Test createAsyncPaymentOrder', async () => {
    const response = await makeApiCall(
      () => controller.createAsyncPaymentOrder(undefined, undefined)
    );

    expect(response.statusCode).toBe(202);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test listPaymentOrders', async () => {
    const response = await makeApiCall(
      () => controller.listPaymentOrders(
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'X-After-Cursor': ['', false],
      'X-Per-Page': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
