/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { PingController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('PingController', () => {
  let controller : PingController;

  beforeAll(() => {
    controller = new PingController(testClient);
  });

  it('should Test pingAPI', async () => {
    const response = await makeApiCall(() => controller.pingAPI());

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
