/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ReturnController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('ReturnController', () => {
  let controller : ReturnController;

  beforeAll(() => {
    controller = new ReturnController(testClient);
  });

  it('should Test listReturns', async () => {
    const response = await makeApiCall(
      () => controller.listReturns(
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'X-After-Cursor': ['', false],
      'X-Per-Page': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test createReturn', async () => {
    const response = await makeApiCall(
      () => controller.createReturn(undefined, undefined)
    );

    expect(response.statusCode).toBe(201);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
