/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { InternalAccount, internalAccountSchema } from '../internalAccount.js';
import {
  ReceivingAccount,
  receivingAccountSchema,
} from '../receivingAccount.js';

/** This is a container type for one-of types. */
export type PaymentOrderReceivingAccount = ReceivingAccount | InternalAccount;

export const paymentOrderReceivingAccountSchema: Schema<PaymentOrderReceivingAccount> = lazy(
  () => oneOf([receivingAccountSchema, internalAccountSchema])
);

export namespace PaymentOrderReceivingAccount {
  /**
   * Validation method to narrow down union type to ReceivingAccount type case.
   *
   * This is ReceivingAccount case.
   */
  export function isReceivingAccount(
    value: unknown
  ): value is ReceivingAccount {
    return isMappedValueValidForSchema(value, receivingAccountSchema);
  }

  /**
   * Validation method to narrow down union type to InternalAccount type case.
   *
   * This is internal_account case.
   */
  export function isInternalAccount(value: unknown): value is InternalAccount {
    return isMappedValueValidForSchema(value, internalAccountSchema);
  }
}
