/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { AccountDetail, accountDetailSchema } from '../models/accountDetail.js';
import {
  AccountDetailCreateRequest,
  accountDetailCreateRequestSchema,
} from '../models/accountDetailCreateRequest.js';
import { AccountsType, accountsTypeSchema } from '../models/accountsType.js';
import { AccountsType1, accountsType1Schema } from '../models/accountsType1.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class AccountDetailController extends BaseController {
  /**
   * Get a list of account details for a single internal or external account.
   *
   * @param accountsType
   * @param accountId     The ID of the account.
   * @param afterCursor
   * @param perPage
   * @return Response from the API call
   */
  async listAccountDetails(
    accountsType: AccountsType,
    accountId: string,
    afterCursor?: string | null,
    perPage?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AccountDetail[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      accountsType: [accountsType, accountsTypeSchema],
      accountId: [accountId, string()],
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.appendTemplatePath`/api/${mapped.accountsType}/${mapped.accountId}/account_details`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(accountDetailSchema), requestOptions);
  }

  /**
   * Create an account detail for an external account.
   *
   * @param accountsType
   * @param accountId       The ID of the account.
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                             something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createAccountDetail(
    accountsType: AccountsType1,
    accountId: string,
    idempotencyKey?: string,
    body?: AccountDetailCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AccountDetail>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      accountsType: [accountsType, accountsType1Schema],
      accountId: [accountId, string()],
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(accountDetailCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.appendTemplatePath`/api/${mapped.accountsType}/${mapped.accountId}/account_details`;
    req.throwOn(404, ErrorMessageError, 'unsuccessful');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(accountDetailSchema, requestOptions);
  }

  /**
   * Get a single account detail for a single internal or external account.
   *
   * @param accountsType
   * @param accountId     The ID of the account.
   * @param id            The ID of the account detail.
   * @return Response from the API call
   */
  async getAccountDetail(
    accountsType: AccountsType,
    accountId: string,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AccountDetail>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      accountsType: [accountsType, accountsTypeSchema],
      accountId: [accountId, string()],
      id: [id, string()],
    });
    req.appendTemplatePath`/api/${mapped.accountsType}/${mapped.accountId}/account_details/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(accountDetailSchema, requestOptions);
  }

  /**
   * Delete a single account detail for an external account.
   *
   * @param accountsType
   * @param accountId     The ID of the account.
   * @param id            The ID of the account detail.
   * @return Response from the API call
   */
  async deleteAccountDetail(
    accountsType: AccountsType1,
    accountId: string,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      accountsType: [accountsType, accountsType1Schema],
      accountId: [accountId, string()],
      id: [id, string()],
    });
    req.appendTemplatePath`/api/${mapped.accountsType}/${mapped.accountId}/account_details/${mapped.id}`;
    req.authenticate([{ basicAuth: true }]);
    return req.call(requestOptions);
  }
}
