/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AccountCollectionFlow,
  accountCollectionFlowSchema,
} from '../models/accountCollectionFlow.js';
import {
  AccountCollectionFlowCreateRequest,
  accountCollectionFlowCreateRequestSchema,
} from '../models/accountCollectionFlowCreateRequest.js';
import {
  AccountCollectionFlowUpdateRequest,
  accountCollectionFlowUpdateRequestSchema,
} from '../models/accountCollectionFlowUpdateRequest.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class AccountCollectionFlowController extends BaseController {
  /**
   * @param afterCursor
   * @param perPage
   * @param clientToken
   * @param status
   * @param counterpartyId
   * @param externalAccountId
   * @return Response from the API call
   */
  async listAccountCollectionFlows(
    afterCursor?: string | null,
    perPage?: number,
    clientToken?: string,
    status?: string,
    counterpartyId?: string,
    externalAccountId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AccountCollectionFlow[]>> {
    const req = this.createRequest('GET', '/api/account_collection_flows');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      clientToken: [clientToken, optional(string())],
      status: [status, optional(string())],
      counterpartyId: [counterpartyId, optional(string())],
      externalAccountId: [externalAccountId, optional(string())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('client_token', mapped.clientToken);
    req.query('status', mapped.status);
    req.query('counterparty_id', mapped.counterpartyId);
    req.query('external_account_id', mapped.externalAccountId);
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(accountCollectionFlowSchema), requestOptions);
  }

  /**
   * @param idempotencyKey  This key should be something unique,
   *                                                                     preferably something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createAccountCollectionFlow(
    idempotencyKey?: string,
    body?: AccountCollectionFlowCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AccountCollectionFlow>> {
    const req = this.createRequest('POST', '/api/account_collection_flows');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(accountCollectionFlowCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(accountCollectionFlowSchema, requestOptions);
  }

  /**
   * @param id              id
   * @param idempotencyKey  This key should be something unique, preferably something like an UUID.
   * @return Response from the API call
   */
  async getAccountCollectionFlow(
    id: string,
    idempotencyKey?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AccountCollectionFlow>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      id: [id, string()],
      idempotencyKey: [idempotencyKey, optional(string())],
    });
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.appendTemplatePath`/api/account_collection_flows/${mapped.id}`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(accountCollectionFlowSchema, requestOptions);
  }

  /**
   * @param id              id
   * @param idempotencyKey  This key should be something unique,
   *                                                                     preferably something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async updateAccountCollectionFlow(
    id: string,
    idempotencyKey?: string,
    body?: AccountCollectionFlowUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AccountCollectionFlow>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(accountCollectionFlowUpdateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.appendTemplatePath`/api/account_collection_flows/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(accountCollectionFlowSchema, requestOptions);
  }
}
