/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { BalanceReport, balanceReportSchema } from '../models/balanceReport.js';
import {
  BalanceReportType1Enum,
  balanceReportType1EnumSchema,
} from '../models/balanceReportType1Enum.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class BalanceReportController extends BaseController {
  /**
   * Get all balance reports for a given internal account.
   *
   * @param internalAccountId
   * @param asOfDate            The date of the balance report in local time.
   * @param balanceReportType   The specific type of balance report. One of `intraday`,
   *                                                      `previous_day`, `real_time`, or `other`.
   * @param afterCursor
   * @param perPage
   * @return Response from the API call
   */
  async listBalanceReports(
    internalAccountId: string,
    asOfDate?: string,
    balanceReportType?: BalanceReportType1Enum,
    afterCursor?: string | null,
    perPage?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BalanceReport[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      internalAccountId: [internalAccountId, string()],
      asOfDate: [asOfDate, optional(string())],
      balanceReportType: [
        balanceReportType,
        optional(balanceReportType1EnumSchema),
      ],
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
    });
    req.query('as_of_date', mapped.asOfDate);
    req.query('balance_report_type', mapped.balanceReportType);
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.appendTemplatePath`/api/internal_accounts/${mapped.internalAccountId}/balance_reports`;
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(balanceReportSchema), requestOptions);
  }

  /**
   * Get a single balance report for a given internal account.
   *
   * @param internalAccountId
   * @param id                  Either the unique identifier of the balance report or latest for the latest
   *                                      balance report.
   * @return Response from the API call
   */
  async getBalanceReport(
    internalAccountId: string,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BalanceReport>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      internalAccountId: [internalAccountId, string()],
      id: [id, string()],
    });
    req.appendTemplatePath`/api/internal_accounts/${mapped.internalAccountId}/balance_reports/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(balanceReportSchema, requestOptions);
  }
}
