/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Counterparty, counterpartySchema } from '../models/counterparty.js';
import {
  CounterpartyCollectAccountRequest,
  counterpartyCollectAccountRequestSchema,
} from '../models/counterpartyCollectAccountRequest.js';
import {
  CounterpartyCollectAccountResponse,
  counterpartyCollectAccountResponseSchema,
} from '../models/counterpartyCollectAccountResponse.js';
import {
  CounterpartyCreateRequest,
  counterpartyCreateRequestSchema,
} from '../models/counterpartyCreateRequest.js';
import {
  CounterpartyUpdateRequest,
  counterpartyUpdateRequestSchema,
} from '../models/counterpartyUpdateRequest.js';
import { array, dict, nullable, number, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ApiError } from '@apimatic/core';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class CounterpartyController extends BaseController {
  /**
   * Send an email requesting account details.
   *
   * @param id              counterparty id
   * @param idempotencyKey  This key should be something unique,
   *                                                                    preferably something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async collectAccountDetails(
    id: string,
    idempotencyKey?: string,
    body?: CounterpartyCollectAccountRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CounterpartyCollectAccountResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      id: [id, string()],
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(counterpartyCollectAccountRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.appendTemplatePath`/api/counterparties/${mapped.id}/collect_account`;
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(
      counterpartyCollectAccountResponseSchema,
      requestOptions
    );
  }

  /**
   * Get a paginated list of all counterparties.
   *
   * @param afterCursor
   * @param perPage
   * @param name                   Performs a partial string match of the name field. This
   *                                                         is also case insensitive.
   * @param email                  Performs a partial string match of the email field. This
   *                                                         is also case insensitive.
   * @param metadata               For example, if you want to query for records with
   *                                                         metadata key `Type` and value `Loan`, the query would be
   *                                                         `metadata%5BType%5D=Loan`. This encodes the query
   *                                                         parameters.
   * @param createdAtLowerBound    Used to return counterparties created after some datetime.
   * @param createdAtUpperBound    Used to return counterparties created before some
   *                                                         datetime.
   * @return Response from the API call
   */
  async listCounterparties(
    afterCursor?: string | null,
    perPage?: number,
    name?: string,
    email?: string,
    metadata?: Record<string, string>,
    createdAtLowerBound?: string,
    createdAtUpperBound?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Counterparty[]>> {
    const req = this.createRequest('GET', '/api/counterparties');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      name: [name, optional(string())],
      email: [email, optional(string())],
      metadata: [metadata, optional(dict(string()))],
      createdAtLowerBound: [createdAtLowerBound, optional(string())],
      createdAtUpperBound: [createdAtUpperBound, optional(string())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('name', mapped.name);
    req.query('email', mapped.email);
    req.query('metadata', mapped.metadata);
    req.query('created_at_lower_bound', mapped.createdAtLowerBound);
    req.query('created_at_upper_bound', mapped.createdAtUpperBound);
    req.throwOn(400, ApiError, 'bad_request');
    req.throwOn(401, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(counterpartySchema), requestOptions);
  }

  /**
   * Create a new counterparty.
   *
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                            something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createCounterparty(
    idempotencyKey?: string,
    body?: CounterpartyCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Counterparty>> {
    const req = this.createRequest('POST', '/api/counterparties');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(counterpartyCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(415, ErrorMessageError, 'unsuccessful');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(counterpartySchema, requestOptions);
  }

  /**
   * Get details on a single counterparty.
   *
   * @param id The id of an existing counterparty.
   * @return Response from the API call
   */
  async getCounterparty(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Counterparty>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/counterparties/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(counterpartySchema, requestOptions);
  }

  /**
   * Updates a given counterparty with new information.
   *
   * @param id           The id of an existing counterparty.
   * @param body
   * @return Response from the API call
   */
  async updateCounterparty(
    id: string,
    body?: CounterpartyUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Counterparty>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(counterpartyUpdateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/counterparties/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(counterpartySchema, requestOptions);
  }

  /**
   * Deletes a given counterparty.
   *
   * @param id The id of an existing counterparty.
   * @return Response from the API call
   */
  async deleteCounterparty(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/counterparties/${mapped.id}`;
    req.authenticate([{ basicAuth: true }]);
    return req.call(requestOptions);
  }
}
