/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, FileWrapper, RequestOptions } from '../core.js';
import { Document, documentSchema } from '../models/document.js';
import {
  DocumentableType1Enum,
  documentableType1EnumSchema,
} from '../models/documentableType1Enum.js';
import {
  DocumentableType2Enum,
  documentableType2EnumSchema,
} from '../models/documentableType2Enum.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class DocumentController extends BaseController {
  /**
   * Get a list of documents.
   *
   * @param documentableId    The unique identifier for the associated object.
   * @param documentableType  The type of the associated object. Currently can be one of
   *                                                   `payment_order`, `transaction`, `paper_item`, `expected_payment`,
   *                                                   `counterparty`, `organization`, `case`, `internal_account`,
   *                                                   `decision`, or `external_account`.
   * @param afterCursor
   * @param perPage
   * @return Response from the API call
   */
  async listDocuments(
    documentableId?: string,
    documentableType?: DocumentableType2Enum,
    afterCursor?: string | null,
    perPage?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Document[]>> {
    const req = this.createRequest('GET', '/api/documents');
    const mapped = req.prepareArgs({
      documentableId: [documentableId, optional(string())],
      documentableType: [
        documentableType,
        optional(documentableType2EnumSchema),
      ],
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
    });
    req.query('documentable_id', mapped.documentableId);
    req.query('documentable_type', mapped.documentableType);
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(documentSchema), requestOptions);
  }

  /**
   * Create a document.
   *
   * @param documentableId    The unique identifier for the associated object.
   * @param documentableType
   * @param file
   * @param idempotencyKey    This key should be something unique, preferably something like
   *                                                   an UUID.
   * @param documentType      A category given to the document, can be `null`.
   * @return Response from the API call
   */
  async createDocument(
    documentableId: string,
    documentableType: DocumentableType1Enum,
    file: FileWrapper,
    idempotencyKey?: string,
    documentType?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Document>> {
    const req = this.createRequest('POST', '/api/documents');
    const mapped = req.prepareArgs({
      documentableId: [documentableId, string()],
      documentableType: [documentableType, documentableType1EnumSchema],
      idempotencyKey: [idempotencyKey, optional(string())],
      documentType: [documentType, optional(string())],
    });
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.formData({
      documentable_id: mapped.documentableId,
      documentable_type: mapped.documentableType,
      file: file,
      document_type: mapped.documentType,
    });
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(documentSchema, requestOptions);
  }

  /**
   * Get a list of documents.
   *
   * @param documentableId    The unique identifier for the associated object.
   * @param documentableType  The type of the associated object. Currently can be one of
   *                                                   `payment_order`, `transaction`, `paper_item`, `expected_payment`,
   *                                                   `counterparty`, `organization`, `case`, `internal_account`,
   *                                                   `decision`, or `external_account`.
   * @param documentType      A category given to the document, can be `null`.
   * @param afterCursor
   * @param perPage
   * @return Response from the API call
   */
  async listDocuments1(
    documentableId: string,
    documentableType: DocumentableType2Enum,
    documentType?: string,
    afterCursor?: string | null,
    perPage?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Document[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      documentableId: [documentableId, string()],
      documentableType: [documentableType, documentableType2EnumSchema],
      documentType: [documentType, optional(string())],
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
    });
    req.query('document_type', mapped.documentType);
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.appendTemplatePath`/api/${mapped.documentableType}/${mapped.documentableId}/documents`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(documentSchema), requestOptions);
  }

  /**
   * Create a document.
   *
   * @param documentableId    The unique identifier for the associated object.
   * @param documentableType  The type of the associated object. Currently can be one of
   *                                                   `payment_order`, `transaction`, `paper_item`, `expected_payment`,
   *                                                   `counterparty`, `organization`, `case`, `internal_account`,
   *                                                   `decision`, or `external_account`.
   * @param file
   * @param idempotencyKey    This key should be something unique, preferably something like
   *                                                   an UUID.
   * @param documentType      A category given to the document, can be `null`.
   * @return Response from the API call
   */
  async createDocument1(
    documentableId: string,
    documentableType: DocumentableType2Enum,
    file: FileWrapper,
    idempotencyKey?: string,
    documentType?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Document>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      documentableId: [documentableId, string()],
      documentableType: [documentableType, documentableType2EnumSchema],
      idempotencyKey: [idempotencyKey, optional(string())],
      documentType: [documentType, optional(string())],
    });
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.formData({ file: file, document_type: mapped.documentType });
    req.appendTemplatePath`/api/${mapped.documentableType}/${mapped.documentableId}/documents`;
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(documentSchema, requestOptions);
  }

  /**
   * Get an existing document.
   *
   * @param documentableId    The unique identifier for the associated object.
   * @param documentableType  The type of the associated object. Currently can be one of
   *                                                   `payment_order`, `transaction`, `paper_item`, `expected_payment`,
   *                                                   `counterparty`, `organization`, `case`, `internal_account`,
   *                                                   `decision`, or `external_account`.
   * @param id                The ID of the document.
   * @return Response from the API call
   */
  async getDocument(
    documentableId: string,
    documentableType: DocumentableType2Enum,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Document>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      documentableId: [documentableId, string()],
      documentableType: [documentableType, documentableType2EnumSchema],
      id: [id, string()],
    });
    req.appendTemplatePath`/api/${mapped.documentableType}/${mapped.documentableId}/documents/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(documentSchema, requestOptions);
  }

  /**
   * Get an existing document.
   *
   * @param id The ID of the document.
   * @return Response from the API call
   */
  async getDocument1(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Document>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/documents/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(documentSchema, requestOptions);
  }

  /**
   * Download an existing document.
   *
   * @param documentableId    The unique identifier for the associated object.
   * @param documentableType  The type of the associated object. Currently can be one of
   *                                                   `payment_order`, `transaction`, `paper_item`, `expected_payment`,
   *                                                   `counterparty`, `organization`, `case`, `internal_account`,
   *                                                   `decision`, or `external_account`.
   * @param id                The ID of the document.
   * @return Response from the API call
   */
  async downloadDocument(
    documentableId: string,
    documentableType: DocumentableType2Enum,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      documentableId: [documentableId, string()],
      documentableType: [documentableType, documentableType2EnumSchema],
      id: [id, string()],
    });
    req.appendTemplatePath`/api/${mapped.documentableType}/${mapped.documentableId}/documents/${mapped.id}/download`;
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.call(requestOptions);
  }

  /**
   * Download an existing document.
   *
   * @param id The ID of the document.
   * @return Response from the API call
   */
  async downloadDocument1(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/documents/${mapped.id}/download`;
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.call(requestOptions);
  }
}
