/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Event, eventSchema } from '../models/event.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class EventApi extends BaseApi {
  /**
   * @param afterCursor
   * @param perPage
   * @param eventTimeStart   An inclusive lower bound for when the event occurred
   * @param eventTimeEnd     An inclusive upper bound for when the event occurred
   * @param resource
   * @param entityId
   * @param eventName
   * @return Response from the API call
   */
  async listEvents(
    afterCursor?: string | null,
    perPage?: number,
    eventTimeStart?: string,
    eventTimeEnd?: string,
    resource?: string,
    entityId?: string,
    eventName?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Event[]>> {
    const req = this.createRequest('GET', '/api/events');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      eventTimeStart: [eventTimeStart, optional(string())],
      eventTimeEnd: [eventTimeEnd, optional(string())],
      resource: [resource, optional(string())],
      entityId: [entityId, optional(string())],
      eventName: [eventName, optional(string())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('event_time_start', mapped.eventTimeStart);
    req.query('event_time_end', mapped.eventTimeEnd);
    req.query('resource', mapped.resource);
    req.query('entity_id', mapped.entityId);
    req.query('event_name', mapped.eventName);
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(eventSchema), requestOptions);
  }

  /**
   * @param id event id
   * @return Response from the API call
   */
  async getEvent(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Event>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/events/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(eventSchema, requestOptions);
  }
}
