/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { CurrencyEnum, currencyEnumSchema } from '../models/currencyEnum.js';
import {
  InternalAccount,
  internalAccountSchema,
} from '../models/internalAccount.js';
import {
  InternalAccountCreateRequest,
  internalAccountCreateRequestSchema,
} from '../models/internalAccountCreateRequest.js';
import {
  InternalAccountUpdateRequest,
  internalAccountUpdateRequestSchema,
} from '../models/internalAccountUpdateRequest.js';
import {
  PaymentDirectionEnum,
  paymentDirectionEnumSchema,
} from '../models/paymentDirectionEnum.js';
import {
  PaymentType13Enum,
  paymentType13EnumSchema,
} from '../models/paymentType13Enum.js';
import { array, dict, nullable, number, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class InternalAccountController extends BaseController {
  /**
   * @param afterCursor
   * @param perPage
   * @param currency          The currency associated with the internal account.
   * @param counterpartyId    The counterparty associated with the internal account.
   * @param paymentType       The type of payment that can be made by the internal account.
   * @param paymentDirection  The direction of payments that can be made by internal account.
   * @param metadata          For example, if you want to query for records with metadata
   *                                                    key `Type` and value `Loan`, the query would be
   *                                                    `metadata%5BType%5D=Loan`. This encodes the query parameters.
   * @return Response from the API call
   */
  async listInternalAccounts(
    afterCursor?: string | null,
    perPage?: number,
    currency?: CurrencyEnum,
    counterpartyId?: string,
    paymentType?: PaymentType13Enum,
    paymentDirection?: PaymentDirectionEnum,
    metadata?: Record<string, string>,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InternalAccount[]>> {
    const req = this.createRequest('GET', '/api/internal_accounts');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      currency: [currency, optional(currencyEnumSchema)],
      counterpartyId: [counterpartyId, optional(string())],
      paymentType: [paymentType, optional(paymentType13EnumSchema)],
      paymentDirection: [
        paymentDirection,
        optional(paymentDirectionEnumSchema),
      ],
      metadata: [metadata, optional(dict(string()))],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('currency', mapped.currency);
    req.query('counterparty_id', mapped.counterpartyId);
    req.query('payment_type', mapped.paymentType);
    req.query('payment_direction', mapped.paymentDirection);
    req.query('metadata', mapped.metadata);
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(internalAccountSchema), requestOptions);
  }

  /**
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                               something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createInternalAccount(
    idempotencyKey?: string,
    body?: InternalAccountCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InternalAccount>> {
    const req = this.createRequest('POST', '/api/internal_accounts');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(internalAccountCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(internalAccountSchema, requestOptions);
  }

  /**
   * @param id Unique identifier for the account.
   * @return Response from the API call
   */
  async getInternalAccount(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InternalAccount>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/internal_accounts/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(internalAccountSchema, requestOptions);
  }

  /**
   * @param id           Unique identifier for the account.
   * @param body
   * @return Response from the API call
   */
  async updateInternalAccount(
    id: string,
    body?: InternalAccountUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InternalAccount>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(internalAccountUpdateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/internal_accounts/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(internalAccountSchema, requestOptions);
  }
}
