/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  InvoiceLineItem,
  invoiceLineItemSchema,
} from '../models/invoiceLineItem.js';
import {
  InvoiceLineItemCreateRequest,
  invoiceLineItemCreateRequestSchema,
} from '../models/invoiceLineItemCreateRequest.js';
import {
  InvoiceLineItemUpdateRequest,
  invoiceLineItemUpdateRequestSchema,
} from '../models/invoiceLineItemUpdateRequest.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class InvoiceLineItemApi extends BaseApi {
  /**
   * @param invoiceId    invoice_id
   * @param afterCursor
   * @param perPage
   * @return Response from the API call
   */
  async listInvoiceLineItems(
    invoiceId: string,
    afterCursor?: string | null,
    perPage?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InvoiceLineItem[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      invoiceId: [invoiceId, string()],
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.appendTemplatePath`/api/invoices/${mapped.invoiceId}/invoice_line_items`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(invoiceLineItemSchema), requestOptions);
  }

  /**
   * @param invoiceId       invoice_id
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                               something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createInvoiceLineItem(
    invoiceId: string,
    idempotencyKey?: string,
    body?: InvoiceLineItemCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InvoiceLineItem>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      invoiceId: [invoiceId, string()],
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(invoiceLineItemCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.appendTemplatePath`/api/invoices/${mapped.invoiceId}/invoice_line_items`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(invoiceLineItemSchema, requestOptions);
  }

  /**
   * @param invoiceId  invoice_id
   * @param id         id
   * @return Response from the API call
   */
  async getInvoiceLineItem(
    invoiceId: string,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InvoiceLineItem>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      invoiceId: [invoiceId, string()],
      id: [id, string()],
    });
    req.appendTemplatePath`/api/invoices/${mapped.invoiceId}/invoice_line_items/${mapped.id}`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(invoiceLineItemSchema, requestOptions);
  }

  /**
   * @param invoiceId    invoice_id
   * @param id           id
   * @param body
   * @return Response from the API call
   */
  async updateInvoiceLineItem(
    invoiceId: string,
    id: string,
    body?: InvoiceLineItemUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InvoiceLineItem>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      invoiceId: [invoiceId, string()],
      id: [id, string()],
      body: [body, optional(invoiceLineItemUpdateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/invoices/${mapped.invoiceId}/invoice_line_items/${mapped.id}`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(invoiceLineItemSchema, requestOptions);
  }

  /**
   * @param invoiceId  invoice_id
   * @param id         id
   * @return Response from the API call
   */
  async deleteInvoiceLineItem(
    invoiceId: string,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<InvoiceLineItem>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      invoiceId: [invoiceId, string()],
      id: [id, string()],
    });
    req.appendTemplatePath`/api/invoices/${mapped.invoiceId}/invoice_line_items/${mapped.id}`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(invoiceLineItemSchema, requestOptions);
  }
}
