/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  LedgerAccountStatement,
  ledgerAccountStatementSchema,
} from '../models/ledgerAccountStatement.js';
import {
  LedgerAccountStatementCreateRequest,
  ledgerAccountStatementCreateRequestSchema,
} from '../models/ledgerAccountStatementCreateRequest.js';
import { optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class LedgerAccountStatementController extends BaseController {
  /**
   * Create a ledger account statement.
   *
   * @param idempotencyKey  This key should be something unique,
   *                                                                      preferably something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createLedgerAccountStatement(
    idempotencyKey?: string,
    body?: LedgerAccountStatementCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerAccountStatement>> {
    const req = this.createRequest('POST', '/api/ledger_account_statements');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(ledgerAccountStatementCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerAccountStatementSchema, requestOptions);
  }

  /**
   * Get details on a single ledger account statement.
   *
   * @param id id
   * @return Response from the API call
   */
  async getLedgerAccountStatement(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerAccountStatement>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/ledger_account_statements/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerAccountStatementSchema, requestOptions);
  }
}
