/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  LedgerAccountPayout,
  ledgerAccountPayoutSchema,
} from '../models/ledgerAccountPayout.js';
import {
  LedgerAccountPayoutCreateRequest,
  ledgerAccountPayoutCreateRequestSchema,
} from '../models/ledgerAccountPayoutCreateRequest.js';
import {
  LedgerAccountPayoutUpdateRequest,
  ledgerAccountPayoutUpdateRequestSchema,
} from '../models/ledgerAccountPayoutUpdateRequest.js';
import { array, dict, nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class LedgerAccountPayoutApi extends BaseApi {
  /**
   * Create a ledger account payout.
   *
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                                   something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createLedgerAccountPayout(
    idempotencyKey?: string,
    body?: LedgerAccountPayoutCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerAccountPayout>> {
    const req = this.createRequest('POST', '/api/ledger_account_payouts');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(ledgerAccountPayoutCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerAccountPayoutSchema, requestOptions);
  }

  /**
   * Get a list of ledger account payouts.
   *
   * @param afterCursor
   * @param perPage
   * @param metadata                 For example, if you want to query for records with
   *                                                           metadata key `Type` and value `Loan`, the query would be
   *                                                           `metadata%5BType%5D=Loan`. This encodes the query
   *                                                           parameters.
   * @param payoutLedgerAccountId
   * @return Response from the API call
   */
  async listLedgerAccountPayouts(
    afterCursor?: string | null,
    perPage?: number,
    metadata?: Record<string, string>,
    payoutLedgerAccountId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerAccountPayout[]>> {
    const req = this.createRequest('GET', '/api/ledger_account_payouts');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      metadata: [metadata, optional(dict(string()))],
      payoutLedgerAccountId: [payoutLedgerAccountId, optional(string())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('metadata', mapped.metadata);
    req.query('payout_ledger_account_id', mapped.payoutLedgerAccountId);
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(ledgerAccountPayoutSchema), requestOptions);
  }

  /**
   * Get details on a single ledger account payout.
   *
   * @param id id
   * @return Response from the API call
   */
  async getLedgerAccountPayout(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerAccountPayout>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/ledger_account_payouts/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerAccountPayoutSchema, requestOptions);
  }

  /**
   * Update the details of a ledger account payout.
   *
   * @param id           id
   * @param body
   * @return Response from the API call
   */
  async updateLedgerAccountPayout(
    id: string,
    body?: LedgerAccountPayoutUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerAccountPayout>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(ledgerAccountPayoutUpdateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/ledger_account_payouts/${mapped.id}`;
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerAccountPayoutSchema, requestOptions);
  }
}
