/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  LedgerableEvent,
  ledgerableEventSchema,
} from '../models/ledgerableEvent.js';
import {
  LedgerableEventCreateRequest,
  ledgerableEventCreateRequestSchema,
} from '../models/ledgerableEventCreateRequest.js';
import { optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class LedgerableEventController extends BaseController {
  /**
   * Translation missing: en.openapi.descriptions.ledger.operations.create_ledgerable_event
   *
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                               something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createLedgerableEvent(
    idempotencyKey?: string,
    body?: LedgerableEventCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerableEvent>> {
    const req = this.createRequest('POST', '/api/ledgerable_events');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(ledgerableEventCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerableEventSchema, requestOptions);
  }

  /**
   * Get details on a single ledgerable event.
   *
   * @param id id
   * @return Response from the API call
   */
  async getLedgerableEvent(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerableEvent>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/ledgerable_events/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerableEventSchema, requestOptions);
  }
}
