/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  LedgerEventHandler,
  ledgerEventHandlerSchema,
} from '../models/ledgerEventHandler.js';
import {
  LedgerEventHandlerCreateRequest,
  ledgerEventHandlerCreateRequestSchema,
} from '../models/ledgerEventHandlerCreateRequest.js';
import { array, dict, nullable, number, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ApiError } from '@apimatic/core';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class LedgerEventHandlerController extends BaseController {
  /**
   * Get a list of ledger event handlers.
   *
   * @param afterCursor
   * @param perPage
   * @param metadata     For example, if you want to query for records with metadata key
   *                                               `Type` and value `Loan`, the query would be
   *                                               `metadata%5BType%5D=Loan`. This encodes the query parameters.
   * @param name
   * @param createdAt    Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or `eq` (=) to
   *                                               filter by the posted at timestamp. For example, for all times after
   *                                               Jan 1 2000 12:00 UTC, use created_at%5Bgt%5D=2000-01-01T12:00:00Z.
   * @return Response from the API call
   */
  async listLedgerEventHandlers(
    afterCursor?: string | null,
    perPage?: number,
    metadata?: Record<string, string>,
    name?: string,
    createdAt?: Record<string, string>,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerEventHandler[]>> {
    const req = this.createRequest('GET', '/api/ledger_event_handlers');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      metadata: [metadata, optional(dict(string()))],
      name: [name, optional(string())],
      createdAt: [createdAt, optional(dict(string()))],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('metadata', mapped.metadata);
    req.query('name', mapped.name);
    req.query('created_at', mapped.createdAt);
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(ledgerEventHandlerSchema), requestOptions);
  }

  /**
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                                  something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createLedgerEventHandler(
    idempotencyKey?: string,
    body?: LedgerEventHandlerCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerEventHandler>> {
    const req = this.createRequest('POST', '/api/ledger_event_handlers');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(ledgerEventHandlerCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'parameter_invalid');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerEventHandlerSchema, requestOptions);
  }

  /**
   * Get details on a single ledger event handler.
   *
   * @param id id
   * @return Response from the API call
   */
  async getLedgerEventHandler(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerEventHandler>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/ledger_event_handlers/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerEventHandlerSchema, requestOptions);
  }

  /**
   * Archive a ledger event handler.
   *
   * @param id id
   * @return Response from the API call
   */
  async deleteLedgerEventHandler(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerEventHandler>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/ledger_event_handlers/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerEventHandlerSchema, requestOptions);
  }
}
