/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Ledger, ledgerSchema } from '../models/ledger.js';
import {
  LedgerCreateRequest,
  ledgerCreateRequestSchema,
} from '../models/ledgerCreateRequest.js';
import {
  LedgerUpdateRequest,
  ledgerUpdateRequestSchema,
} from '../models/ledgerUpdateRequest.js';
import { array, dict, nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class LedgerApi extends BaseApi {
  /**
   * Get a list of ledgers.
   *
   * @param afterCursor
   * @param perPage
   * @param metadata     For example, if you want to query for records with metadata key
   *                                               `Type` and value `Loan`, the query would be
   *                                               `metadata%5BType%5D=Loan`. This encodes the query parameters.
   * @param updatedAt    Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or `eq` (=) to
   *                                               filter by the posted at timestamp. For example, for all times after
   *                                               Jan 1 2000 12:00 UTC, use updated_at%5Bgt%5D=2000-01-01T12:00:00Z.
   * @return Response from the API call
   */
  async listLedgers(
    afterCursor?: string | null,
    perPage?: number,
    metadata?: Record<string, string>,
    updatedAt?: Record<string, string>,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Ledger[]>> {
    const req = this.createRequest('GET', '/api/ledgers');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      metadata: [metadata, optional(dict(string()))],
      updatedAt: [updatedAt, optional(dict(string()))],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('metadata', mapped.metadata);
    req.query('updated_at', mapped.updatedAt);
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(ledgerSchema), requestOptions);
  }

  /**
   * Create a ledger.
   *
   * @param idempotencyKey  This key should be something unique, preferably something
   *                                                      like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createLedger(
    idempotencyKey?: string,
    body?: LedgerCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Ledger>> {
    const req = this.createRequest('POST', '/api/ledgers');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(ledgerCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerSchema, requestOptions);
  }

  /**
   * Get details on a single ledger.
   *
   * @param id id
   * @return Response from the API call
   */
  async getLedger(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Ledger>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/ledgers/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerSchema, requestOptions);
  }

  /**
   * Update the details of a ledger.
   *
   * @param id           id
   * @param body
   * @return Response from the API call
   */
  async updateLedger(
    id: string,
    body?: LedgerUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Ledger>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(ledgerUpdateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/ledgers/${mapped.id}`;
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerSchema, requestOptions);
  }

  /**
   * Delete a ledger.
   *
   * @param id id
   * @return Response from the API call
   */
  async deleteLedger(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Ledger>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/ledgers/${mapped.id}`;
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerSchema, requestOptions);
  }
}
