/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Balances2, balances2Schema } from '../models/balances2.js';
import { Balances3, balances3Schema } from '../models/balances3.js';
import { LedgerAccount, ledgerAccountSchema } from '../models/ledgerAccount.js';
import {
  LedgerAccountCreateRequest,
  ledgerAccountCreateRequestSchema,
} from '../models/ledgerAccountCreateRequest.js';
import {
  LedgerAccountUpdateRequest,
  ledgerAccountUpdateRequestSchema,
} from '../models/ledgerAccountUpdateRequest.js';
import { array, dict, nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class LedgerAccountApi extends BaseApi {
  /**
   * Get a list of ledger accounts.
   *
   * @param afterCursor
   * @param perPage
   * @param metadata                   For example, if you want to query for records with
   *                                                             metadata key `Type` and value `Loan`, the query would
   *                                                             be `metadata%5BType%5D=Loan`. This encodes the query
   *                                                             parameters.
   * @param id
   * @param name
   * @param ledgerId
   * @param currency
   * @param balances                   Use `balances[effective_at_lower_bound]` and
   *                                                             `balances[effective_at_upper_bound]` to get the
   *                                                             balances change between the two timestamps. The lower
   *                                                             bound is inclusive while the upper bound is exclusive
   *                                                             of the provided timestamps. If no value is supplied
   *                                                             the balances will be retrieved not including that
   *                                                             bound.
   * @param createdAt                  Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or
   *                                                             `eq` (=) to filter by the created at timestamp. For
   *                                                             example, for all times after Jan 1 2000 12:00 UTC, use
   *                                                             created_at%5Bgt%5D=2000-01-01T12:00:00Z.
   * @param updatedAt                  Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or
   *                                                             `eq` (=) to filter by the updated at timestamp. For
   *                                                             example, for all times after Jan 1 2000 12:00 UTC, use
   *                                                             updated_at%5Bgt%5D=2000-01-01T12:00:00Z.
   * @param ledgerAccountCategoryId
   * @return Response from the API call
   */
  async listLedgerAccounts(
    afterCursor?: string | null,
    perPage?: number,
    metadata?: Record<string, string>,
    id?: string,
    name?: string,
    ledgerId?: string,
    currency?: string,
    balances?: Balances2,
    createdAt?: Record<string, string>,
    updatedAt?: Record<string, string>,
    ledgerAccountCategoryId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerAccount[]>> {
    const req = this.createRequest('GET', '/api/ledger_accounts');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      metadata: [metadata, optional(dict(string()))],
      id: [id, optional(string())],
      name: [name, optional(string())],
      ledgerId: [ledgerId, optional(string())],
      currency: [currency, optional(string())],
      balances: [balances, optional(balances2Schema)],
      createdAt: [createdAt, optional(dict(string()))],
      updatedAt: [updatedAt, optional(dict(string()))],
      ledgerAccountCategoryId: [ledgerAccountCategoryId, optional(string())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('metadata', mapped.metadata);
    req.query('id', mapped.id);
    req.query('name', mapped.name);
    req.query('ledger_id', mapped.ledgerId);
    req.query('currency', mapped.currency);
    req.query('balances', mapped.balances);
    req.query('created_at', mapped.createdAt);
    req.query('updated_at', mapped.updatedAt);
    req.query('ledger_account_category_id', mapped.ledgerAccountCategoryId);
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(ledgerAccountSchema), requestOptions);
  }

  /**
   * Create a ledger account.
   *
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                             something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createLedgerAccount(
    idempotencyKey?: string,
    body?: LedgerAccountCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerAccount>> {
    const req = this.createRequest('POST', '/api/ledger_accounts');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(ledgerAccountCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerAccountSchema, requestOptions);
  }

  /**
   * Get details on a single ledger account.
   *
   * @param id       id
   * @param balances Use `balances[effective_at_lower_bound]` and
   *                                     `balances[effective_at_upper_bound]` to get the balances change between the
   *                                     two timestamps. The lower bound is inclusive while the upper bound is
   *                                     exclusive of the provided timestamps. If no value is supplied the balances
   *                                     will be retrieved not including that bound. Use `balances[as_of_lock_version]`
   *                                     to retrieve a balance as of a specific Ledger Account `lock_version`.
   * @return Response from the API call
   */
  async getLedgerAccount(
    id: string,
    balances?: Balances3,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerAccount>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      id: [id, string()],
      balances: [balances, optional(balances3Schema)],
    });
    req.query('balances', mapped.balances);
    req.appendTemplatePath`/api/ledger_accounts/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerAccountSchema, requestOptions);
  }

  /**
   * Update the details of a ledger account.
   *
   * @param id           id
   * @param body
   * @return Response from the API call
   */
  async updateLedgerAccount(
    id: string,
    body?: LedgerAccountUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerAccount>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(ledgerAccountUpdateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/ledger_accounts/${mapped.id}`;
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerAccountSchema, requestOptions);
  }

  /**
   * Delete a ledger account.
   *
   * @param id id
   * @return Response from the API call
   */
  async deleteLedgerAccount(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerAccount>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/ledger_accounts/${mapped.id}`;
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerAccountSchema, requestOptions);
  }
}
