/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  LedgerableType6,
  ledgerableType6Schema,
} from '../models/ledgerableType6.js';
import {
  LedgerTransaction,
  ledgerTransactionSchema,
} from '../models/ledgerTransaction.js';
import {
  LedgerTransactionCreateRequest,
  ledgerTransactionCreateRequestSchema,
} from '../models/ledgerTransactionCreateRequest.js';
import {
  LedgerTransactionReversalCreateRequest,
  ledgerTransactionReversalCreateRequestSchema,
} from '../models/ledgerTransactionReversalCreateRequest.js';
import {
  LedgerTransactionUpdateRequest,
  ledgerTransactionUpdateRequestSchema,
} from '../models/ledgerTransactionUpdateRequest.js';
import {
  LedgerTransactionVersion,
  ledgerTransactionVersionSchema,
} from '../models/ledgerTransactionVersion.js';
import { OrderBy, orderBySchema } from '../models/orderBy.js';
import { Status22, status22Schema } from '../models/status22.js';
import { array, dict, nullable, number, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class LedgerTransactionController extends BaseController {
  /**
   * Create a ledger transaction reversal.
   *
   * @param id           The id of ledger transaction to reverse.
   * @param body
   * @return Response from the API call
   */
  async createLedgerTransactionReversal(
    id: string,
    body?: LedgerTransactionReversalCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerTransaction>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(ledgerTransactionReversalCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/ledger_transactions/${mapped.id}/reversal`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerTransactionSchema, requestOptions);
  }

  /**
   * Get a list of ledger transaction versions.
   *
   * @param afterCursor
   * @param perPage
   * @param createdAt                   Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or
   *                                                              `eq` (=) to filter by the created_at timestamp. For
   *                                                              example, for all dates after Jan 1 2000 12:00 UTC,
   *                                                              use created_at%5Bgt%5D=2000-01-01T12:00:00Z.
   * @param version                     Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or
   *                                                              `eq` (=) to filter by the version. For example, for
   *                                                              all versions after 2, use version%5Bgt%5D=2.
   * @param ledgerTransactionId         Get all the ledger transaction versions
   *                                                              corresponding to the ID of a ledger transaction.
   * @param ledgerAccountStatementId    Get all ledger transaction versions that are
   *                                                              included in the ledger account statement.
   * @return Response from the API call
   */
  async listLedgerTransactionVersions(
    afterCursor?: string | null,
    perPage?: number,
    createdAt?: Record<string, string>,
    version?: Record<string, number>,
    ledgerTransactionId?: string,
    ledgerAccountStatementId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerTransactionVersion[]>> {
    const req = this.createRequest('GET', '/api/ledger_transaction_versions');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      createdAt: [createdAt, optional(dict(string()))],
      version: [version, optional(dict(number()))],
      ledgerTransactionId: [ledgerTransactionId, optional(string())],
      ledgerAccountStatementId: [ledgerAccountStatementId, optional(string())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('created_at', mapped.createdAt);
    req.query('version', mapped.version);
    req.query('ledger_transaction_id', mapped.ledgerTransactionId);
    req.query('ledger_account_statement_id', mapped.ledgerAccountStatementId);
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(
      array(ledgerTransactionVersionSchema),
      requestOptions
    );
  }

  /**
   * Get a list of ledger transactions.
   *
   * @param afterCursor
   * @param perPage
   * @param id
   * @param metadata                       For example, if you want to query for records
   *                                                                 with metadata key `Type` and value `Loan`, the
   *                                                                 query would be `metadata%5BType%5D=Loan`. This
   *                                                                 encodes the query parameters.
   * @param ledgerId
   * @param ledgerAccountId
   * @param effectiveAt                    Use "gt" (>), "gte" (>=), "lt" (<), "lte" (<=),
   *                                                                 or "eq" (=) to filter by effective at. For example,
   *                                                                 for all transactions after Jan 1 2000, use
   *                                                                 effective_at%5Bgt%5D=2000-01-01T00:00:00:00.000Z.
   * @param effectiveDate                  Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=),
   *                                                                 or `eq` (=) to filter by effective date. For
   *                                                                 example, for all dates after Jan 1 2000, use
   *                                                                 effective_date%5Bgt%5D=2000-01-01.
   * @param postedAt                       Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=),
   *                                                                 or `eq` (=) to filter by the posted at timestamp.
   *                                                                 For example, for all times after Jan 1 2000 12:00
   *                                                                 UTC, use posted_at%5Bgt%5D=2000-01-01T12:00:00Z.
   * @param updatedAt                      Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=),
   *                                                                 or `eq` (=) to filter by the posted at timestamp.
   *                                                                 For example, for all times after Jan 1 2000 12:00
   *                                                                 UTC, use updated_at%5Bgt%5D=2000-01-01T12:00:00Z.
   * @param orderBy                        Order by `created_at` or `effective_at` in `asc`
   *                                                                 or `desc` order. For example, to order by
   *                                                                 `effective_at asc`, use
   *                                                                 `order_by%5Beffective_at%5D=asc`. Ordering by only
   *                                                                 one field at a time is supported.
   * @param status
   * @param externalId
   * @param ledgerAccountCategoryId
   * @param ledgerAccountPayoutId
   * @param reversesLedgerTransactionId
   * @param ledgerableId
   * @param ledgerableType
   * @return Response from the API call
   */
  async listLedgerTransactions(
    afterCursor?: string | null,
    perPage?: number,
    id?: Record<string, string>,
    metadata?: Record<string, string>,
    ledgerId?: string,
    ledgerAccountId?: string,
    effectiveAt?: Record<string, string>,
    effectiveDate?: Record<string, string>,
    postedAt?: Record<string, string>,
    updatedAt?: Record<string, string>,
    orderBy?: OrderBy,
    status?: Status22,
    externalId?: string,
    ledgerAccountCategoryId?: string,
    ledgerAccountPayoutId?: string,
    reversesLedgerTransactionId?: string,
    ledgerableId?: string,
    ledgerableType?: LedgerableType6,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerTransaction[]>> {
    const req = this.createRequest('GET', '/api/ledger_transactions');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      id: [id, optional(dict(string()))],
      metadata: [metadata, optional(dict(string()))],
      ledgerId: [ledgerId, optional(string())],
      ledgerAccountId: [ledgerAccountId, optional(string())],
      effectiveAt: [effectiveAt, optional(dict(string()))],
      effectiveDate: [effectiveDate, optional(dict(string()))],
      postedAt: [postedAt, optional(dict(string()))],
      updatedAt: [updatedAt, optional(dict(string()))],
      orderBy: [orderBy, optional(orderBySchema)],
      status: [status, optional(status22Schema)],
      externalId: [externalId, optional(string())],
      ledgerAccountCategoryId: [ledgerAccountCategoryId, optional(string())],
      ledgerAccountPayoutId: [ledgerAccountPayoutId, optional(string())],
      reversesLedgerTransactionId: [
        reversesLedgerTransactionId,
        optional(string()),
      ],
      ledgerableId: [ledgerableId, optional(string())],
      ledgerableType: [ledgerableType, optional(ledgerableType6Schema)],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('id', mapped.id);
    req.query('metadata', mapped.metadata);
    req.query('ledger_id', mapped.ledgerId);
    req.query('ledger_account_id', mapped.ledgerAccountId);
    req.query('effective_at', mapped.effectiveAt);
    req.query('effective_date', mapped.effectiveDate);
    req.query('posted_at', mapped.postedAt);
    req.query('updated_at', mapped.updatedAt);
    req.query('order_by', mapped.orderBy);
    req.query('status', mapped.status);
    req.query('external_id', mapped.externalId);
    req.query('ledger_account_category_id', mapped.ledgerAccountCategoryId);
    req.query('ledger_account_payout_id', mapped.ledgerAccountPayoutId);
    req.query(
      'reverses_ledger_transaction_id',
      mapped.reversesLedgerTransactionId
    );
    req.query('ledgerable_id', mapped.ledgerableId);
    req.query('ledgerable_type', mapped.ledgerableType);
    req.throwOn(422, ErrorMessageError, 'parameter invalid');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(ledgerTransactionSchema), requestOptions);
  }

  /**
   * Create a ledger transaction.
   *
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                                 something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createLedgerTransaction(
    idempotencyKey?: string,
    body?: LedgerTransactionCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerTransaction>> {
    const req = this.createRequest('POST', '/api/ledger_transactions');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(ledgerTransactionCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.throwOn(429, ErrorMessageError, 'too many requests');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerTransactionSchema, requestOptions);
  }

  /**
   * Get details on a single ledger transaction.
   *
   * @param id id
   * @return Response from the API call
   */
  async getLedgerTransaction(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerTransaction>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/ledger_transactions/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerTransactionSchema, requestOptions);
  }

  /**
   * Update the details of a ledger transaction.
   *
   * @param id           id
   * @param body
   * @return Response from the API call
   */
  async updateLedgerTransaction(
    id: string,
    body?: LedgerTransactionUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerTransaction>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(ledgerTransactionUpdateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/ledger_transactions/${mapped.id}`;
    req.throwOn(400, ErrorMessageError, 'parameter_invalid');
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.throwOn(429, ErrorMessageError, 'too many requests');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(ledgerTransactionSchema, requestOptions);
  }

  /**
   * Get a list of ledger transaction versions.
   *
   * @param id           id
   * @param afterCursor
   * @param perPage
   * @param createdAt    Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or `eq` (=) to
   *                                               filter by the created_at timestamp. For example, for all dates after
   *                                               Jan 1 2000 12:00 UTC, use created_at%5Bgt%5D=2000-01-01T12:00:00Z.
   * @param version      Use `gt` (>), `gte` (>=), `lt` (<), `lte` (<=), or `eq` (=) to
   *                                               filter by the version. For example, for all versions after 2, use
   *                                               version%5Bgt%5D=2.
   * @return Response from the API call
   */
  async listLedgerTransactionVersions1(
    id: string,
    afterCursor?: string | null,
    perPage?: number,
    createdAt?: Record<string, string>,
    version?: Record<string, number>,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LedgerTransactionVersion[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      id: [id, string()],
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      createdAt: [createdAt, optional(dict(string()))],
      version: [version, optional(dict(number()))],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('created_at', mapped.createdAt);
    req.query('version', mapped.version);
    req.appendTemplatePath`/api/ledger_transactions/${mapped.id}/versions`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(
      array(ledgerTransactionVersionSchema),
      requestOptions
    );
  }
}
