/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ItemizableType1,
  itemizableType1Schema,
} from '../models/itemizableType1.js';
import { LineItem, lineItemSchema } from '../models/lineItem.js';
import {
  LineItemUpdateRequest,
  lineItemUpdateRequestSchema,
} from '../models/lineItemUpdateRequest.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class LineItemController extends BaseController {
  /**
   * Get a list of line items
   *
   * @param itemizableId    The ID of the payment order or expected payment.
   * @param itemizableType  One of `payment_orders` or `expected_payments`.
   * @param afterCursor
   * @param perPage
   * @return Response from the API call
   */
  async listLineItems(
    itemizableId: string,
    itemizableType: ItemizableType1,
    afterCursor?: string | null,
    perPage?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LineItem[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      itemizableId: [itemizableId, string()],
      itemizableType: [itemizableType, itemizableType1Schema],
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.appendTemplatePath`/api/${mapped.itemizableType}/${mapped.itemizableId}/line_items`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(lineItemSchema), requestOptions);
  }

  /**
   * Get a single line item
   *
   * @param itemizableId    The ID of the payment order or expected payment.
   * @param itemizableType  One of `payment_orders` or `expected_payments`.
   * @param id              The ID of the line item.
   * @return Response from the API call
   */
  async getLineItem(
    itemizableId: string,
    itemizableType: ItemizableType1,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LineItem>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      itemizableId: [itemizableId, string()],
      itemizableType: [itemizableType, itemizableType1Schema],
      id: [id, string()],
    });
    req.appendTemplatePath`/api/${mapped.itemizableType}/${mapped.itemizableId}/line_items/${mapped.id}`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(lineItemSchema, requestOptions);
  }

  /**
   * @param itemizableId    The ID of the payment order or expected payment.
   * @param itemizableType  One of `payment_orders` or `expected_payments`.
   * @param id              The ID of the line item.
   * @param body
   * @return Response from the API call
   */
  async updateLineItem(
    itemizableId: string,
    itemizableType: ItemizableType1,
    id: string,
    body?: LineItemUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LineItem>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      itemizableId: [itemizableId, string()],
      itemizableType: [itemizableType, itemizableType1Schema],
      id: [id, string()],
      body: [body, optional(lineItemUpdateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/${mapped.itemizableType}/${mapped.itemizableId}/line_items/${mapped.id}`;
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(lineItemSchema, requestOptions);
  }
}
