/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { PaperItem, paperItemSchema } from '../models/paperItem.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class PaperItemApi extends BaseApi {
  /**
   * Get a list of all paper items.
   *
   * @param lockboxNumber      Specify `lockbox_number` if you wish to see paper items that are
   *                                            associated with a specific lockbox number.
   * @param depositDateStart   Specify an inclusive start date (YYYY-MM-DD) when filtering by
   *                                            deposit_date
   * @param depositDateEnd     Specify an inclusive end date (YYYY-MM-DD) when filtering by
   *                                            deposit_date
   * @param afterCursor
   * @param perPage
   * @return Response from the API call
   */
  async listPaperItems(
    lockboxNumber?: string,
    depositDateStart?: string,
    depositDateEnd?: string,
    afterCursor?: string | null,
    perPage?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaperItem[]>> {
    const req = this.createRequest('GET', '/api/paper_items');
    const mapped = req.prepareArgs({
      lockboxNumber: [lockboxNumber, optional(string())],
      depositDateStart: [depositDateStart, optional(string())],
      depositDateEnd: [depositDateEnd, optional(string())],
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
    });
    req.query('lockbox_number', mapped.lockboxNumber);
    req.query('deposit_date_start', mapped.depositDateStart);
    req.query('deposit_date_end', mapped.depositDateEnd);
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(paperItemSchema), requestOptions);
  }

  /**
   * Get details on a single paper item.
   *
   * @param id id
   * @return Response from the API call
   */
  async getPaperItem(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaperItem>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/paper_items/${mapped.id}`;
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(paperItemSchema, requestOptions);
  }
}
