/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Accounting, accountingSchema } from '../models/accounting.js';
import { AsyncResponse, asyncResponseSchema } from '../models/asyncResponse.js';
import {
  ChargeBearerEnum,
  chargeBearerEnumSchema,
} from '../models/chargeBearerEnum.js';
import {
  ContentTypeEnum,
  contentTypeEnumSchema,
} from '../models/contentTypeEnum.js';
import { CurrencyEnum, currencyEnumSchema } from '../models/currencyEnum.js';
import {
  Direction15Enum,
  direction15EnumSchema,
} from '../models/direction15Enum.js';
import {
  Direction5Enum,
  direction5EnumSchema,
} from '../models/direction5Enum.js';
import {
  DocumentCreateRequest,
  documentCreateRequestSchema,
} from '../models/documentCreateRequest.js';
import {
  FallbackTypeEnum,
  fallbackTypeEnumSchema,
} from '../models/fallbackTypeEnum.js';
import {
  ForeignExchangeIndicatorEnum,
  foreignExchangeIndicatorEnumSchema,
} from '../models/foreignExchangeIndicatorEnum.js';
import {
  LedgerTransactionCreateRequest,
  ledgerTransactionCreateRequestSchema,
} from '../models/ledgerTransactionCreateRequest.js';
import {
  LineItemRequest,
  lineItemRequestSchema,
} from '../models/lineItemRequest.js';
import { PaymentOrder, paymentOrderSchema } from '../models/paymentOrder.js';
import {
  PaymentOrderAsyncCreateRequest,
  paymentOrderAsyncCreateRequestSchema,
} from '../models/paymentOrderAsyncCreateRequest.js';
import {
  PaymentOrderUpdateRequest,
  paymentOrderUpdateRequestSchema,
} from '../models/paymentOrderUpdateRequest.js';
import { Priority4Enum, priority4EnumSchema } from '../models/priority4Enum.js';
import { PriorityEnum, priorityEnumSchema } from '../models/priorityEnum.js';
import {
  ReceivingAccount1,
  receivingAccount1Schema,
} from '../models/receivingAccount1.js';
import { Status24Enum, status24EnumSchema } from '../models/status24Enum.js';
import { SubtypeEnum, subtypeEnumSchema } from '../models/subtypeEnum.js';
import { Type13Enum, type13EnumSchema } from '../models/type13Enum.js';
import { Type5Enum, type5EnumSchema } from '../models/type5Enum.js';
import {
  array,
  boolean,
  dict,
  nullable,
  number,
  optional,
  string,
} from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class PaymentOrderController extends BaseController {
  /**
   * Create a new payment order asynchronously
   *
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                                 something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createAsyncPaymentOrder(
    idempotencyKey?: string,
    body?: PaymentOrderAsyncCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AsyncResponse>> {
    const req = this.createRequest('POST', '/api/payment_orders/create_async');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(paymentOrderAsyncCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(asyncResponseSchema, requestOptions);
  }

  /**
   * Get a list of all payment orders
   *
   * @param afterCursor
   * @param perPage
   * @param type
   * @param priority               Either `normal` or `high`. For ACH and EFT payments,
   *                                                         `high` represents a same-day ACH or EFT transfer,
   *                                                         respectively. For check payments, `high` can mean an
   *                                                         overnight check rather than standard mail.
   * @param counterpartyId
   * @param originatingAccountId
   * @param transactionId          The ID of a transaction that the payment order has been
   *                                                         reconciled to.
   * @param status
   * @param direction
   * @param referenceNumber        Query for records with the provided reference number
   * @param effectiveDateStart     An inclusive lower bound for searching effective_date
   * @param effectiveDateEnd       An inclusive upper bound for searching effective_date
   * @param metadata               For example, if you want to query for records with
   *                                                         metadata key `Type` and value `Loan`, the query would be
   *                                                         `metadata%5BType%5D=Loan`. This encodes the query
   *                                                         parameters.
   * @return Response from the API call
   */
  async listPaymentOrders(
    afterCursor?: string | null,
    perPage?: number,
    type?: Type13Enum,
    priority?: Priority4Enum,
    counterpartyId?: string,
    originatingAccountId?: string,
    transactionId?: string,
    status?: Status24Enum,
    direction?: Direction15Enum,
    referenceNumber?: string,
    effectiveDateStart?: string,
    effectiveDateEnd?: string,
    metadata?: Record<string, string>,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentOrder[]>> {
    const req = this.createRequest('GET', '/api/payment_orders');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      type: [type, optional(type13EnumSchema)],
      priority: [priority, optional(priority4EnumSchema)],
      counterpartyId: [counterpartyId, optional(string())],
      originatingAccountId: [originatingAccountId, optional(string())],
      transactionId: [transactionId, optional(string())],
      status: [status, optional(status24EnumSchema)],
      direction: [direction, optional(direction15EnumSchema)],
      referenceNumber: [referenceNumber, optional(string())],
      effectiveDateStart: [effectiveDateStart, optional(string())],
      effectiveDateEnd: [effectiveDateEnd, optional(string())],
      metadata: [metadata, optional(dict(string()))],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('type', mapped.type);
    req.query('priority', mapped.priority);
    req.query('counterparty_id', mapped.counterpartyId);
    req.query('originating_account_id', mapped.originatingAccountId);
    req.query('transaction_id', mapped.transactionId);
    req.query('status', mapped.status);
    req.query('direction', mapped.direction);
    req.query('reference_number', mapped.referenceNumber);
    req.query('effective_date_start', mapped.effectiveDateStart);
    req.query('effective_date_end', mapped.effectiveDateEnd);
    req.query('metadata', mapped.metadata);
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(paymentOrderSchema), requestOptions);
  }

  /**
   * Create a new Payment Order
   *
   * @param type                                  One of `ach`, `eft`, `wire`,
   *                                                                                       `check`, `sen`, `book`,
   *                                                                                       `rtp`, `sepa`, `bacs`,
   *                                                                                       `au_becs`, `interac`,
   *                                                                                       `signet`, `provexchange`.
   * @param amount                                Value in specified
   *                                                                                       currency's smallest unit. e.
   *                                                                                       g. $10 would be represented
   *                                                                                       as 1000 (cents). For RTP,
   *                                                                                       the maximum amount allowed
   *                                                                                       by the network is $100,000.
   * @param direction                             One of `credit`, `debit`.
   *                                                                                       Describes the direction
   *                                                                                       money is flowing in the
   *                                                                                       transaction. A `credit`
   *                                                                                       moves money from your
   *                                                                                       account to someone else's. A
   *                                                                                       `debit` pulls money from
   *                                                                                       someone else's account to
   *                                                                                       your own. Note that wire,
   *                                                                                       rtp, and check payments will
   *                                                                                       always be `credit`.
   * @param originatingAccountId                  The ID of one of your
   *                                                                                       organization's internal
   *                                                                                       accounts.
   * @param contentType
   * @param idempotencyKey                        This key should be
   *                                                                                       something unique, preferably
   *                                                                                       something like an UUID.
   * @param subtype                               An additional layer of
   *                                                                                       classification for the type
   *                                                                                       of payment order you are
   *                                                                                       doing. This field is only
   *                                                                                       used for `ach` payment
   *                                                                                       orders currently. For `ach`
   *                                                                                       payment orders, the
   *                                                                                       `subtype`  represents the
   *                                                                                       SEC code. We currently
   *                                                                                       support `CCD`, `PPD`, `IAT`,
   *                                                                                       `CTX`, `WEB`, `CIE`, and
   *                                                                                       `TEL`.
   * @param priority                              Either `normal` or `high`.
   *                                                                                       For ACH and EFT payments,
   *                                                                                       `high` represents a same-day
   *                                                                                       ACH or EFT transfer,
   *                                                                                       respectively. For check
   *                                                                                       payments, `high` can mean an
   *                                                                                       overnight check rather than
   *                                                                                       standard mail.
   * @param receivingAccountId                    Either `receiving_account`
   *                                                                                       or `receiving_account_id`
   *                                                                                       must be present. When using
   *                                                                                       `receiving_account_id`, you
   *                                                                                       may pass the id of an
   *                                                                                       external account or an
   *                                                                                       internal account.
   * @param accounting
   * @param accountingCategoryId                  The ID of one of your
   *                                                                                       accounting categories. Note
   *                                                                                       that these will only be
   *                                                                                       accessible if your
   *                                                                                       accounting system has been
   *                                                                                       connected.
   * @param accountingLedgerClassId               The ID of one of your
   *                                                                                       accounting ledger classes.
   *                                                                                       Note that these will only be
   *                                                                                       accessible if your
   *                                                                                       accounting system has been
   *                                                                                       connected.
   * @param currency                              Three-letter ISO currency
   *                                                                                       code.
   * @param effectiveDate                         Date transactions are to be
   *                                                                                       posted to the participants'
   *                                                                                       account. Defaults to the
   *                                                                                       current business day or the
   *                                                                                       next business day if the
   *                                                                                       current day is a bank
   *                                                                                       holiday or weekend. Format:
   *                                                                                       yyyy-mm-dd.
   * @param description                           An optional description for
   *                                                                                       internal use.
   * @param statementDescriptor                   An optional descriptor
   *                                                                                       which will appear in the
   *                                                                                       receiver's statement. For
   *                                                                                       `check` payments this field
   *                                                                                       will be used as the memo
   *                                                                                       line. For `ach` the maximum
   *                                                                                       length is 10 characters.
   *                                                                                       Note that for ACH payments,
   *                                                                                       the name on your bank
   *                                                                                       account will be included
   *                                                                                       automatically by the bank,
   *                                                                                       so you can use the
   *                                                                                       characters for other useful
   *                                                                                       information. For `eft` the
   *                                                                                       maximum length is 15
   *                                                                                       characters.
   * @param remittanceInformation                 For `ach`, this field will
   *                                                                                       be passed through on an
   *                                                                                       addenda record. For `wire`
   *                                                                                       payments the field will be
   *                                                                                       passed through as the
   *                                                                                       "Originator to Beneficiary
   *                                                                                       Information", also known as
   *                                                                                       OBI or Fedwire tag 6000.
   * @param purpose                               For `wire`, this is usually
   *                                                                                       the purpose which is
   *                                                                                       transmitted via the
   *                                                                                       "InstrForDbtrAgt" field in
   *                                                                                       the ISO20022 file. If you
   *                                                                                       are using Currencycloud,
   *                                                                                       this is the `payment.
   *                                                                                       purpose_code` field. For
   *                                                                                       `eft`, this field is the 3
   *                                                                                       digit CPA Code that will be
   *                                                                                       attached to the payment.
   * @param metadata                              Additional data represented
   *                                                                                       as key-value pairs. Both the
   *                                                                                       key and value must be
   *                                                                                       strings.
   * @param chargeBearer                          The party that will pay the
   *                                                                                       fees for the payment order.
   *                                                                                       Only applies to wire payment
   *                                                                                       orders. Can be one of shared,
   *                                                                                       sender, or receiver, which
   *                                                                                       correspond respectively with
   *                                                                                       the SWIFT 71A values `SHA`,
   *                                                                                       `OUR`, `BEN`.
   * @param foreignExchangeIndicator              Indicates the type of FX
   *                                                                                       transfer to initiate, can be
   *                                                                                       either `variable_to_fixed`,
   *                                                                                       `fixed_to_variable`, or
   *                                                                                       `null` if the payment order
   *                                                                                       currency matches the
   *                                                                                       originating account currency.
   * @param foreignExchangeContract               If present, indicates a
   *                                                                                       specific foreign exchange
   *                                                                                       contract number that has
   *                                                                                       been generated by your
   *                                                                                       financial institution.
   * @param nsfProtected                          A boolean to determine if
   *                                                                                       NSF Protection is enabled
   *                                                                                       for this payment order. Note
   *                                                                                       that this setting must also
   *                                                                                       be turned on in your
   *                                                                                       organization settings page.
   * @param originatingPartyName                  If present, this will
   *                                                                                       replace your default company
   *                                                                                       name on receiver's bank
   *                                                                                       statement. This field can
   *                                                                                       only be used for ACH
   *                                                                                       payments currently. For ACH,
   *                                                                                       only the first 16 characters
   *                                                                                       of this string will be used.
   *                                                                                       Any additional characters
   *                                                                                       will be truncated.
   * @param ultimateOriginatingPartyName          Name of the ultimate
   *                                                                                       originator of the payment
   *                                                                                       order.
   * @param ultimateOriginatingPartyIdentifier    Identifier of the ultimate
   *                                                                                       originator of the payment
   *                                                                                       order.
   * @param ultimateReceivingPartyName            Name of the ultimate funds
   *                                                                                       recipient.
   * @param ultimateReceivingPartyIdentifier      Identifier of the ultimate
   *                                                                                       funds recipient.
   * @param sendRemittanceAdvice                  Send an email to the
   *                                                                                       counterparty when the
   *                                                                                       payment order is sent to the
   *                                                                                       bank. If `null`,
   *                                                                                       `send_remittance_advice` on
   *                                                                                       the Counterparty is used.
   * @param expiresAt                             RFP payments require an
   *                                                                                       expires_at. This value must
   *                                                                                       be past the effective_date.
   * @param fallbackType                          A payment type to fallback
   *                                                                                       to if the original type is
   *                                                                                       not valid for the receiving
   *                                                                                       account. Currently, this
   *                                                                                       only supports falling back
   *                                                                                       from RTP to ACH (type=rtp
   *                                                                                       and fallback_type=ach)
   * @param receivingAccount                      Either `receiving_account`
   *                                                                                       or `receiving_account_id`
   *                                                                                       must be present. When using
   *                                                                                       `receiving_account_id`, you
   *                                                                                       may pass the id of an
   *                                                                                       external account or an
   *                                                                                       internal account.
   * @param ledgerTransaction
   * @param lineItems                             An array of line items that
   *                                                                                       must sum up to the amount of
   *                                                                                       the payment order.
   * @param transactionMonitoringEnabled          A flag that determines
   *                                                                                       whether a payment order
   *                                                                                       should go through
   *                                                                                       transaction monitoring.
   * @param documents                             An array of documents to be
   *                                                                                       attached to the payment
   *                                                                                       order. Note that if you
   *                                                                                       attach documents, the
   *                                                                                       request's content type must
   *                                                                                       be `multipart/form-data`.
   * @return Response from the API call
   */
  async createPaymentOrder(
    type: Type5Enum,
    amount: number,
    direction: Direction5Enum,
    originatingAccountId: string,
    contentType?: ContentTypeEnum,
    idempotencyKey?: string,
    subtype?: SubtypeEnum | null,
    priority?: PriorityEnum,
    receivingAccountId?: string,
    accounting?: Accounting,
    accountingCategoryId?: string | null,
    accountingLedgerClassId?: string | null,
    currency?: CurrencyEnum,
    effectiveDate?: string,
    description?: string | null,
    statementDescriptor?: string | null,
    remittanceInformation?: string | null,
    purpose?: string | null,
    metadata?: Record<string, string>,
    chargeBearer?: ChargeBearerEnum | null,
    foreignExchangeIndicator?: ForeignExchangeIndicatorEnum | null,
    foreignExchangeContract?: string | null,
    nsfProtected?: boolean,
    originatingPartyName?: string | null,
    ultimateOriginatingPartyName?: string | null,
    ultimateOriginatingPartyIdentifier?: string | null,
    ultimateReceivingPartyName?: string | null,
    ultimateReceivingPartyIdentifier?: string | null,
    sendRemittanceAdvice?: boolean | null,
    expiresAt?: string | null,
    fallbackType?: FallbackTypeEnum,
    receivingAccount?: ReceivingAccount1,
    ledgerTransaction?: LedgerTransactionCreateRequest,
    lineItems?: LineItemRequest[],
    transactionMonitoringEnabled?: boolean,
    documents?: DocumentCreateRequest[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentOrder>> {
    const req = this.createRequest('POST', '/api/payment_orders');
    const mapped = req.prepareArgs({
      type: [type, type5EnumSchema],
      amount: [amount, number()],
      direction: [direction, direction5EnumSchema],
      originatingAccountId: [originatingAccountId, string()],
      contentType: [contentType, optional(contentTypeEnumSchema)],
      idempotencyKey: [idempotencyKey, optional(string())],
      subtype: [subtype, optional(nullable(subtypeEnumSchema))],
      priority: [priority, optional(priorityEnumSchema)],
      receivingAccountId: [receivingAccountId, optional(string())],
      accounting: [accounting, optional(accountingSchema)],
      accountingCategoryId: [
        accountingCategoryId,
        optional(nullable(string())),
      ],
      accountingLedgerClassId: [
        accountingLedgerClassId,
        optional(nullable(string())),
      ],
      currency: [currency, optional(currencyEnumSchema)],
      effectiveDate: [effectiveDate, optional(string())],
      description: [description, optional(nullable(string()))],
      statementDescriptor: [statementDescriptor, optional(nullable(string()))],
      remittanceInformation: [
        remittanceInformation,
        optional(nullable(string())),
      ],
      purpose: [purpose, optional(nullable(string()))],
      metadata: [metadata, optional(dict(string()))],
      chargeBearer: [chargeBearer, optional(nullable(chargeBearerEnumSchema))],
      foreignExchangeIndicator: [
        foreignExchangeIndicator,
        optional(nullable(foreignExchangeIndicatorEnumSchema)),
      ],
      foreignExchangeContract: [
        foreignExchangeContract,
        optional(nullable(string())),
      ],
      nsfProtected: [nsfProtected, optional(boolean())],
      originatingPartyName: [
        originatingPartyName,
        optional(nullable(string())),
      ],
      ultimateOriginatingPartyName: [
        ultimateOriginatingPartyName,
        optional(nullable(string())),
      ],
      ultimateOriginatingPartyIdentifier: [
        ultimateOriginatingPartyIdentifier,
        optional(nullable(string())),
      ],
      ultimateReceivingPartyName: [
        ultimateReceivingPartyName,
        optional(nullable(string())),
      ],
      ultimateReceivingPartyIdentifier: [
        ultimateReceivingPartyIdentifier,
        optional(nullable(string())),
      ],
      sendRemittanceAdvice: [
        sendRemittanceAdvice,
        optional(nullable(boolean())),
      ],
      expiresAt: [expiresAt, optional(nullable(string()))],
      fallbackType: [fallbackType, optional(fallbackTypeEnumSchema)],
      receivingAccount: [receivingAccount, optional(receivingAccount1Schema)],
      ledgerTransaction: [
        ledgerTransaction,
        optional(ledgerTransactionCreateRequestSchema),
      ],
      lineItems: [lineItems, optional(array(lineItemRequestSchema))],
      transactionMonitoringEnabled: [
        transactionMonitoringEnabled,
        optional(boolean()),
      ],
      documents: [documents, optional(array(documentCreateRequestSchema))],
    });
    req.header('Content-Type', mapped.contentType);
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.form({
      type: mapped.type,
      amount: mapped.amount,
      direction: mapped.direction,
      originating_account_id: mapped.originatingAccountId,
      subtype: mapped.subtype,
      priority: mapped.priority,
      receiving_account_id: mapped.receivingAccountId,
      accounting: mapped.accounting,
      accounting_category_id: mapped.accountingCategoryId,
      accounting_ledger_class_id: mapped.accountingLedgerClassId,
      currency: mapped.currency,
      effective_date: mapped.effectiveDate,
      description: mapped.description,
      statement_descriptor: mapped.statementDescriptor,
      remittance_information: mapped.remittanceInformation,
      purpose: mapped.purpose,
      metadata: mapped.metadata,
      charge_bearer: mapped.chargeBearer,
      foreign_exchange_indicator: mapped.foreignExchangeIndicator,
      foreign_exchange_contract: mapped.foreignExchangeContract,
      nsf_protected: mapped.nsfProtected,
      originating_party_name: mapped.originatingPartyName,
      ultimate_originating_party_name: mapped.ultimateOriginatingPartyName,
      ultimate_originating_party_identifier: mapped.ultimateOriginatingPartyIdentifier,
      ultimate_receiving_party_name: mapped.ultimateReceivingPartyName,
      ultimate_receiving_party_identifier: mapped.ultimateReceivingPartyIdentifier,
      send_remittance_advice: mapped.sendRemittanceAdvice,
      expires_at: mapped.expiresAt,
      fallback_type: mapped.fallbackType,
      receiving_account: mapped.receivingAccount,
      ledger_transaction: mapped.ledgerTransaction,
      line_items: mapped.lineItems,
      transaction_monitoring_enabled: mapped.transactionMonitoringEnabled,
      documents: mapped.documents,
    });
    req.throwOn(400, ErrorMessageError, 'parameter_invalid');
    req.throwOn(401, ErrorMessageError, 'unsuccessful');
    req.throwOn(403, ErrorMessageError, 'forbidden');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(paymentOrderSchema, requestOptions);
  }

  /**
   * Get details on a single payment order
   *
   * @param id
   * @return Response from the API call
   */
  async getPaymentOrder(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentOrder>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/payment_orders/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(paymentOrderSchema, requestOptions);
  }

  /**
   * Update a payment order
   *
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updatePaymentOrder(
    id: string,
    body?: PaymentOrderUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentOrder>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(paymentOrderUpdateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/payment_orders/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'parameter_invalid');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(paymentOrderSchema, requestOptions);
  }
}
