/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  PaymentReferenceObject,
  paymentReferenceObjectSchema,
} from '../models/paymentReferenceObject.js';
import {
  ReferenceableType1,
  referenceableType1Schema,
} from '../models/referenceableType1.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class PaymentReferenceApi extends BaseApi {
  /**
   * @param afterCursor
   * @param perPage
   * @param referenceableId    The id of the referenceable to search for. Must be accompanied by
   *                                                 the referenceable_type or will return an error.
   * @param referenceableType  One of the referenceable types. This must be accompanied by the
   *                                                 id of the referenceable or will return an error.
   * @param referenceNumber    The actual reference number assigned by the bank.
   * @return Response from the API call
   */
  async listPaymentReferences(
    afterCursor?: string | null,
    perPage?: number,
    referenceableId?: string,
    referenceableType?: ReferenceableType1,
    referenceNumber?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentReferenceObject[]>> {
    const req = this.createRequest('GET', '/api/payment_references');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      referenceableId: [referenceableId, optional(string())],
      referenceableType: [
        referenceableType,
        optional(referenceableType1Schema),
      ],
      referenceNumber: [referenceNumber, optional(string())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('referenceable_id', mapped.referenceableId);
    req.query('referenceable_type', mapped.referenceableType);
    req.query('reference_number', mapped.referenceNumber);
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(paymentReferenceObjectSchema), requestOptions);
  }

  /**
   * @param id id
   * @return Response from the API call
   */
  async getPaymentReference(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentReferenceObject>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/payment_references/${mapped.id}`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(paymentReferenceObjectSchema, requestOptions);
  }
}
