/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { PaymentFlow, paymentFlowSchema } from '../models/paymentFlow.js';
import {
  PaymentFlowCreateRequest,
  paymentFlowCreateRequestSchema,
} from '../models/paymentFlowCreateRequest.js';
import {
  PaymentFlowUpdateRequest,
  paymentFlowUpdateRequestSchema,
} from '../models/paymentFlowUpdateRequest.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class PaymentFlowApi extends BaseApi {
  /**
   * @param afterCursor
   * @param perPage
   * @param clientToken
   * @param status
   * @param counterpartyId
   * @param receivingAccountId
   * @param originatingAccountId
   * @param paymentOrderId
   * @return Response from the API call
   */
  async listPaymentFlows(
    afterCursor?: string | null,
    perPage?: number,
    clientToken?: string,
    status?: string,
    counterpartyId?: string,
    receivingAccountId?: string,
    originatingAccountId?: string,
    paymentOrderId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentFlow[]>> {
    const req = this.createRequest('GET', '/api/payment_flows');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      clientToken: [clientToken, optional(string())],
      status: [status, optional(string())],
      counterpartyId: [counterpartyId, optional(string())],
      receivingAccountId: [receivingAccountId, optional(string())],
      originatingAccountId: [originatingAccountId, optional(string())],
      paymentOrderId: [paymentOrderId, optional(string())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('client_token', mapped.clientToken);
    req.query('status', mapped.status);
    req.query('counterparty_id', mapped.counterpartyId);
    req.query('receiving_account_id', mapped.receivingAccountId);
    req.query('originating_account_id', mapped.originatingAccountId);
    req.query('payment_order_id', mapped.paymentOrderId);
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(paymentFlowSchema), requestOptions);
  }

  /**
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                           something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createPaymentFlow(
    idempotencyKey?: string,
    body?: PaymentFlowCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentFlow>> {
    const req = this.createRequest('POST', '/api/payment_flows');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(paymentFlowCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(paymentFlowSchema, requestOptions);
  }

  /**
   * @param id              id
   * @param idempotencyKey  This key should be something unique, preferably something like an UUID.
   * @return Response from the API call
   */
  async getPaymentFlow(
    id: string,
    idempotencyKey?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentFlow>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      id: [id, string()],
      idempotencyKey: [idempotencyKey, optional(string())],
    });
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.appendTemplatePath`/api/payment_flows/${mapped.id}`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(paymentFlowSchema, requestOptions);
  }

  /**
   * @param id              id
   * @param idempotencyKey  This key should be something unique, preferably
   *                                                           something like an UUID.
   * @param body
   * @return Response from the API call
   */
  async updatePaymentFlow(
    id: string,
    idempotencyKey?: string,
    body?: PaymentFlowUpdateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentFlow>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(paymentFlowUpdateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.appendTemplatePath`/api/payment_flows/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(paymentFlowSchema, requestOptions);
  }
}
