/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { PingResponse, pingResponseSchema } from '../models/pingResponse.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class PingApi extends BaseApi {
  /**
   * A test endpoint often used to confirm credentials and headers are being passed in correctly.
   *
   * @return Response from the API call
   */
  async pingApi(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PingResponse>> {
    const req = this.createRequest('GET', '/api/ping');
    req.throwOn(401, ErrorMessageError, 'unsuccessful');
    req.throwOn(429, ApiError, 'unsuccessful');
    req.throwOn(500, ApiError, 'internal server error');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(pingResponseSchema, requestOptions);
  }
}
