/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Return, returnSchema } from '../models/return.js';
import {
  ReturnableType2,
  returnableType2Schema,
} from '../models/returnableType2.js';
import {
  ReturnCreateRequest,
  returnCreateRequestSchema,
} from '../models/returnCreateRequest.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class ReturnApi extends BaseApi {
  /**
   * Get a list of returns.
   *
   * @param afterCursor
   * @param perPage
   * @param internalAccountId   Specify `internal_account_id` if you wish to see returns to/from a
   *                                               specific account.
   * @param counterpartyId      Specify `counterparty_id` if you wish to see returns that occurred
   *                                               with a specific counterparty.
   * @param returnableId        The ID of a valid returnable. Must be accompanied by
   *                                               `returnable_type`.
   * @param returnableType      One of `payment_order`, `paper_item`, `reversal`, or
   *                                               `incoming_payment_detail`. Must be accompanied by `returnable_id`.
   * @return Response from the API call
   */
  async listReturns(
    afterCursor?: string | null,
    perPage?: number,
    internalAccountId?: string,
    counterpartyId?: string,
    returnableId?: string,
    returnableType?: ReturnableType2,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Return[]>> {
    const req = this.createRequest('GET', '/api/returns');
    const mapped = req.prepareArgs({
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
      internalAccountId: [internalAccountId, optional(string())],
      counterpartyId: [counterpartyId, optional(string())],
      returnableId: [returnableId, optional(string())],
      returnableType: [returnableType, optional(returnableType2Schema)],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.query('internal_account_id', mapped.internalAccountId);
    req.query('counterparty_id', mapped.counterpartyId);
    req.query('returnable_id', mapped.returnableId);
    req.query('returnable_type', mapped.returnableType);
    req.throwOn(401, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(returnSchema), requestOptions);
  }

  /**
   * Create a return.
   *
   * @param idempotencyKey  This key should be something unique, preferably something
   *                                                      like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createReturn(
    idempotencyKey?: string,
    body?: ReturnCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Return>> {
    const req = this.createRequest('POST', '/api/returns');
    const mapped = req.prepareArgs({
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(returnCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.throwOn(404, ErrorMessageError, 'unsuccessful');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(returnSchema, requestOptions);
  }

  /**
   * Get a single return.
   *
   * @param id The ID of an existing return.
   * @return Response from the API call
   */
  async getReturn(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Return>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/returns/${mapped.id}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(returnSchema, requestOptions);
  }
}
