/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Reversal, reversalSchema } from '../models/reversal.js';
import {
  ReversalCreateRequest,
  reversalCreateRequestSchema,
} from '../models/reversalCreateRequest.js';
import { array, nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class ReversalApi extends BaseApi {
  /**
   * Get a list of all reversals of a payment order.
   *
   * @param paymentOrderId   The ID of the relevant Payment Order.
   * @param afterCursor
   * @param perPage
   * @return Response from the API call
   */
  async listReversals(
    paymentOrderId: string,
    afterCursor?: string | null,
    perPage?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Reversal[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      paymentOrderId: [paymentOrderId, string()],
      afterCursor: [afterCursor, optional(nullable(string()))],
      perPage: [perPage, optional(number())],
    });
    req.query('after_cursor', mapped.afterCursor);
    req.query('per_page', mapped.perPage);
    req.appendTemplatePath`/api/payment_orders/${mapped.paymentOrderId}/reversals`;
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(array(reversalSchema), requestOptions);
  }

  /**
   * Create a reversal for a payment order.
   *
   * @param paymentOrderId   The ID of the relevant Payment Order.
   * @param idempotencyKey   This key should be something unique, preferably something
   *                                                         like an UUID.
   * @param body
   * @return Response from the API call
   */
  async createReversal(
    paymentOrderId: string,
    idempotencyKey?: string,
    body?: ReversalCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Reversal>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      paymentOrderId: [paymentOrderId, string()],
      idempotencyKey: [idempotencyKey, optional(string())],
      body: [body, optional(reversalCreateRequestSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.header('Idempotency-Key', mapped.idempotencyKey);
    req.json(mapped.body);
    req.appendTemplatePath`/api/payment_orders/${mapped.paymentOrderId}/reversals`;
    req.throwOn(404, ErrorMessageError, 'unsuccessful');
    req.throwOn(422, ErrorMessageError, 'unsuccessful');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(reversalSchema, requestOptions);
  }

  /**
   * Get details on a single reversal of a payment order.
   *
   * @param paymentOrderId   The id of the payment order being reversed.
   * @param reversalId       The ID of the reversal.
   * @return Response from the API call
   */
  async getReversal(
    paymentOrderId: string,
    reversalId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Reversal>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      paymentOrderId: [paymentOrderId, string()],
      reversalId: [reversalId, string()],
    });
    req.appendTemplatePath`/api/payment_orders/${mapped.paymentOrderId}/reversals/${mapped.reversalId}`;
    req.throwOn(404, ErrorMessageError, 'not found');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(reversalSchema, requestOptions);
  }
}
