/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  RoutingNumberLookupRequest,
  routingNumberLookupRequestSchema,
} from '../models/routingNumberLookupRequest.js';
import {
  RoutingNumberType8,
  routingNumberType8Schema,
} from '../models/routingNumberType8.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ErrorMessageError } from '../errors/errorMessageError.js';

export class ValidationController extends BaseController {
  /**
   * Validates the routing number information supplied without creating a routing detail
   *
   * @param routingNumber       The routing number that is being validated.
   * @param routingNumberType   One of `aba`, `au_bsb`, `br_codigo`, `ca_cpa`, `cnaps`,
   *                                                  `gb_sort_code`, `in_ifsc`, `my_branch_code`, or `swift`. In
   *                                                  sandbox mode we currently only support `aba` and `swift` with
   *                                                  routing numbers '123456789' and 'GRINUST0XXX' respectively.
   * @return Response from the API call
   */
  async validateRoutingNumber(
    routingNumber: string,
    routingNumberType: RoutingNumberType8,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RoutingNumberLookupRequest>> {
    const req = this.createRequest('GET', '/api/validations/routing_numbers');
    const mapped = req.prepareArgs({
      routingNumber: [routingNumber, string()],
      routingNumberType: [routingNumberType, routingNumberType8Schema],
    });
    req.query('routing_number', mapped.routingNumber);
    req.query('routing_number_type', mapped.routingNumberType);
    req.throwOn(404, ErrorMessageError, 'not found');
    req.throwOn(422, ErrorMessageError, 'unsuccessful with invalid parameter');
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(routingNumberLookupRequestSchema, requestOptions);
  }
}
