/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AccountNumberType2,
  accountNumberType2Schema,
} from './accountNumberType2.js';

export interface AccountDetail1 {
  accountNumber: string;
  accountNumberType?: AccountNumberType2;
  additionalProperties?: Record<string, unknown>;
}

export const accountDetail1Schema: Schema<AccountDetail1> = typedExpandoObject(
  {
    accountNumber: ['account_number', string()],
    accountNumberType: [
      'account_number_type',
      optional(accountNumberType2Schema),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
