/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import {
  AccountNumberType2Enum,
  accountNumberType2EnumSchema,
} from './accountNumberType2Enum.js';

export interface AccountDetail1 {
  accountNumber: string;
  accountNumberType?: AccountNumberType2Enum;
}

export const accountDetail1Schema: Schema<AccountDetail1> = object({
  accountNumber: ['account_number', string()],
  accountNumberType: [
    'account_number_type',
    optional(accountNumberType2EnumSchema),
  ],
});
