/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountNumberType
 */
export enum AccountNumberType {
  Clabe = 'clabe',
  Iban = 'iban',
  Other = 'other',
  Pan = 'pan',
  WalletAddress = 'wallet_address',
}

/**
 * Schema for AccountNumberType
 */
export const accountNumberTypeSchema: Schema<AccountNumberType> = stringEnum(
  AccountNumberType
);
