/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountsType
 */
export enum AccountsType {
  ExternalAccounts = 'external_accounts',
  InternalAccounts = 'internal_accounts',
}

/**
 * Schema for AccountsType
 */
export const accountsTypeSchema: Schema<AccountsType> = stringEnum(
  AccountsType
);
