/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  AccountNumberTypeEnum,
  accountNumberTypeEnumSchema,
} from './accountNumberTypeEnum.js';

export interface AccountDetail {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  /** The account number for the bank account. */
  accountNumber?: string;
  /** One of `iban`, `clabe`, `wallet_address`, or `other`. Use `other` if the bank account number is in a generic format. */
  accountNumberType: AccountNumberTypeEnum;
  /** The last 4 digits of the account_number. */
  accountNumberSafe: string;
}

export const accountDetailSchema: Schema<AccountDetail> = object({
  id: ['id', string()],
  object: ['object', string()],
  liveMode: ['live_mode', boolean()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  discardedAt: ['discarded_at', nullable(string())],
  accountNumber: ['account_number', optional(string())],
  accountNumberType: ['account_number_type', accountNumberTypeEnumSchema],
  accountNumberSafe: ['account_number_safe', string()],
});
