/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountType5
 */
export enum AccountType5 {
  Cash = 'cash',
  Checking = 'checking',
  Loan = 'loan',
  NonResident = 'non_resident',
  Other = 'other',
  Overdraft = 'overdraft',
  Savings = 'savings',
}

/**
 * Schema for AccountType5
 */
export const accountType5Schema: Schema<AccountType5> = stringEnum(
  AccountType5
);
