/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountTypeEnum
 */
export enum AccountTypeEnum {
  Cash = 'cash',
  Checking = 'checking',
  Loan = 'loan',
  NonResident = 'non_resident',
  Other = 'other',
  Overdraft = 'overdraft',
  Savings = 'savings',
}

/**
 * Schema for AccountTypeEnum
 */
export const accountTypeEnumSchema: Schema<AccountTypeEnum> = stringEnum(
  AccountTypeEnum
);
