/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountsType1
 */
export enum AccountsType1 {
  ExternalAccounts = 'external_accounts',
}

/**
 * Schema for AccountsType1
 */
export const accountsType1Schema: Schema<AccountsType1> = stringEnum(
  AccountsType1
);
