/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema.js';

export interface AccountCollectionFlowCreateRequest {
  /** Required. */
  counterpartyId: string;
  paymentTypes: string[];
}

export const accountCollectionFlowCreateRequestSchema: Schema<AccountCollectionFlowCreateRequest> = object(
  {
    counterpartyId: ['counterparty_id', string()],
    paymentTypes: ['payment_types', array(string())],
  }
);
