/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Accounting {
  /** The ID of one of your accounting categories. Note that these will only be accessible if your accounting system has been connected. */
  accountId?: string | null;
  /** The ID of one of the class objects in your accounting system. Class objects track segments of your business independent of client or project. Note that these will only be accessible if your accounting system has been connected. */
  classId?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const accountingSchema: Schema<Accounting> = typedExpandoObject(
  {
    accountId: ['account_id', optional(nullable(string()))],
    classId: ['class_id', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
