/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { PaymentType, paymentTypeSchema } from './paymentType.js';
import { Status, statusSchema } from './status.js';

export interface AccountCollectionFlow {
  id?: string;
  object?: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode?: boolean;
  createdAt?: string;
  updatedAt?: string;
  /** The client token of the account collection flow.  This token can be used to embed account collection in your client-side application. */
  clientToken?: string;
  /** The current status of the account collection flow. One of `pending`, `completed`, `expired`, or `cancelled`. */
  status?: Status;
  /** The ID of a counterparty. An external account created with this flow will be associated with this counterparty. */
  counterpartyId: string;
  /** If present, the ID of the external account created using this flow. */
  externalAccountId?: string | null;
  paymentTypes: PaymentType[];
}

export const accountCollectionFlowSchema: Schema<AccountCollectionFlow> = object(
  {
    id: ['id', optional(string())],
    object: ['object', optional(string())],
    liveMode: ['live_mode', optional(boolean())],
    createdAt: ['created_at', optional(string())],
    updatedAt: ['updated_at', optional(string())],
    clientToken: ['client_token', optional(string())],
    status: ['status', optional(statusSchema)],
    counterpartyId: ['counterparty_id', string()],
    externalAccountId: ['external_account_id', optional(nullable(string()))],
    paymentTypes: ['payment_types', array(paymentTypeSchema)],
  }
);
