/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountsType1Enum
 */
export enum AccountsType1Enum {
  ExternalAccounts = 'external_accounts',
}

/**
 * Schema for AccountsType1Enum
 */
export const accountsType1EnumSchema: Schema<AccountsType1Enum> = stringEnum(
  AccountsType1Enum
);
