/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';
import { Type, typeSchema } from './type.js';

export interface Accounting1 {
  /** An optional type to auto-sync the counterparty to your ledger. Either `customer` or `vendor`. */
  type?: Type;
  additionalProperties?: Record<string, unknown>;
}

export const accounting1Schema: Schema<Accounting1> = typedExpandoObject(
  { type: ['type', optional(typeSchema)] },
  'additionalProperties',
  optional(unknown())
);
