/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import { TypeEnum, typeEnumSchema } from './typeEnum.js';

export interface Accounting1 {
  /** An optional type to auto-sync the counterparty to your ledger. Either `customer` or `vendor`. */
  type?: TypeEnum;
}

export const accounting1Schema: Schema<Accounting1> = object({
  type: ['type', optional(typeEnumSchema)],
});
