/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountType
 */
export enum AccountType {
  Cash = 'cash',
  Checking = 'checking',
  Loan = 'loan',
  NonResident = 'non_resident',
  Other = 'other',
  Overdraft = 'overdraft',
  Savings = 'savings',
}

/**
 * Schema for AccountType
 */
export const accountTypeSchema: Schema<AccountType> = stringEnum(AccountType);
