/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountNumberType2Enum
 */
export enum AccountNumberType2Enum {
  Iban = 'iban',
  Clabe = 'clabe',
  WalletAddress = 'wallet_address',
  Pan = 'pan',
  Other = 'other',
}

/**
 * Schema for AccountNumberType2Enum
 */
export const accountNumberType2EnumSchema: Schema<AccountNumberType2Enum> = stringEnum(
  AccountNumberType2Enum
);
