/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AccountCollectionFlowCreateRequest {
  /** Required. */
  counterpartyId: string;
  paymentTypes: string[];
  additionalProperties?: Record<string, unknown>;
}

export const accountCollectionFlowCreateRequestSchema: Schema<AccountCollectionFlowCreateRequest> = typedExpandoObject(
  {
    counterpartyId: ['counterparty_id', string()],
    paymentTypes: ['payment_types', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
