/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountsTypeEnum
 */
export enum AccountsTypeEnum {
  ExternalAccounts = 'external_accounts',
  InternalAccounts = 'internal_accounts',
}

/**
 * Schema for AccountsTypeEnum
 */
export const accountsTypeEnumSchema: Schema<AccountsTypeEnum> = stringEnum(
  AccountsTypeEnum
);
