/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountNumberTypeEnum
 */
export enum AccountNumberTypeEnum {
  Clabe = 'clabe',
  Iban = 'iban',
  Other = 'other',
  Pan = 'pan',
  WalletAddress = 'wallet_address',
}

/**
 * Schema for AccountNumberTypeEnum
 */
export const accountNumberTypeEnumSchema: Schema<AccountNumberTypeEnum> = stringEnum(
  AccountNumberTypeEnum
);
