/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, object, Schema, string } from '../schema.js';

export interface Address {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  line1: string | null;
  line2: string | null;
  /** Locality or City. */
  locality: string | null;
  /** Region or State. */
  region: string | null;
  /** The postal code of the address. */
  postalCode: string | null;
  /** Country code conforms to [ISO 3166-1 alpha-2] */
  country: string | null;
}

export const addressSchema: Schema<Address> = object({
  id: ['id', string()],
  object: ['object', string()],
  liveMode: ['live_mode', boolean()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  line1: ['line1', nullable(string())],
  line2: ['line2', nullable(string())],
  locality: ['locality', nullable(string())],
  region: ['region', nullable(string())],
  postalCode: ['postal_code', nullable(string())],
  country: ['country', nullable(string())],
});
