/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface AsyncResponse {
  id: string;
  object: string;
}

export const asyncResponseSchema: Schema<AsyncResponse> = object({
  id: ['id', string()],
  object: ['object', string()],
});
