/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BalanceType
 */
export enum BalanceType {
  ClosingAvailable = 'closing_available',
  ClosingLedger = 'closing_ledger',
  CurrentAvailable = 'current_available',
  CurrentLedger = 'current_ledger',
  OpeningAvailable = 'opening_available',
  OpeningAvailableNextBusinessDay = 'opening_available_next_business_day',
  OpeningLedger = 'opening_ledger',
  Other = 'other',
}

/**
 * Schema for BalanceType
 */
export const balanceTypeSchema: Schema<BalanceType> = stringEnum(BalanceType);
