/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  object,
  Schema,
  string,
} from '../schema.js';
import { Balance, balanceSchema } from './balance.js';
import {
  BalanceReportTypeEnum,
  balanceReportTypeEnumSchema,
} from './balanceReportTypeEnum.js';

export interface BalanceReport {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  /** The specific type of balance report. One of `intraday`, `previous_day`, `real_time`, or `other`. */
  balanceReportType: BalanceReportTypeEnum;
  /** The date of the balance report in local time. */
  asOfDate: string;
  /** The time (24-hour clock) of the balance report in local time. */
  asOfTime: string | null;
  /** An array of `Balance` objects. */
  balances: Balance[];
  /** The ID of one of your organization's Internal Accounts. */
  internalAccountId: string;
}

export const balanceReportSchema: Schema<BalanceReport> = lazy(() =>
  object({
    id: ['id', string()],
    object: ['object', string()],
    liveMode: ['live_mode', boolean()],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    balanceReportType: ['balance_report_type', balanceReportTypeEnumSchema],
    asOfDate: ['as_of_date', string()],
    asOfTime: ['as_of_time', nullable(string())],
    balances: ['balances', array(balanceSchema)],
    internalAccountId: ['internal_account_id', string()],
  })
);
