/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';

export interface Balances3 {
  asOfDate?: string;
  effectiveAt?: string;
  effectiveAtLowerBound?: string;
  effectiveAtUpperBound?: string;
  asOfLockVersion?: number;
}

export const balances3Schema: Schema<Balances3> = object({
  asOfDate: ['as_of_date', optional(string())],
  effectiveAt: ['effective_at', optional(string())],
  effectiveAtLowerBound: ['effective_at_lower_bound', optional(string())],
  effectiveAtUpperBound: ['effective_at_upper_bound', optional(string())],
  asOfLockVersion: ['as_of_lock_version', optional(number())],
});
