/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BalanceReportType
 */
export enum BalanceReportType {
  Intraday = 'intraday',
  Other = 'other',
  PreviousDay = 'previous_day',
  RealTime = 'real_time',
}

/**
 * Schema for BalanceReportType
 */
export const balanceReportTypeSchema: Schema<BalanceReportType> = stringEnum(
  BalanceReportType
);
