/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Balances1 {
  asOfDate?: string;
  effectiveAt?: string;
}

export const balances1Schema: Schema<Balances1> = object({
  asOfDate: ['as_of_date', optional(string())],
  effectiveAt: ['effective_at', optional(string())],
});
