/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Balances {
  effectiveAt?: string;
}

export const balancesSchema: Schema<Balances> = object({
  effectiveAt: ['effective_at', optional(string())],
});
