/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ChargeBearer
 */
export enum ChargeBearer {
  Shared = 'shared',
  Sender = 'sender',
  Receiver = 'receiver',
}

/**
 * Schema for ChargeBearer
 */
export const chargeBearerSchema: Schema<ChargeBearer> = stringEnum(
  ChargeBearer
);
