/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ChargeBearerEnum
 */
export enum ChargeBearerEnum {
  Shared = 'shared',
  Sender = 'sender',
  Receiver = 'receiver',
}

/**
 * Schema for ChargeBearerEnum
 */
export const chargeBearerEnumSchema: Schema<ChargeBearerEnum> = stringEnum(
  ChargeBearerEnum
);
