/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CodeEnum
 */
export enum CodeEnum {
  ParameterInvalid = 'parameter_invalid',
  ParameterMissing = 'parameter_missing',
  ResourceNotFound = 'resource_not_found',
  NotFound = 'not_found',
  Forbidden = 'forbidden',
  InvalidIp = 'invalid_ip',
  InvalidKey = 'invalid_key',
  HeaderInvalid = 'header_invalid',
  ExpiredKey = 'expired_key',
  TooManyRequests = 'too_many_requests',
}

/**
 * Schema for CodeEnum
 */
export const codeEnumSchema: Schema<CodeEnum> = stringEnum(CodeEnum);
