/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Code1
 */
export enum Code1 {
  Enum901 = '901',
  Enum902 = '902',
  Enum903 = '903',
  Enum904 = '904',
  Enum905 = '905',
  Enum907 = '907',
  Enum908 = '908',
  Enum909 = '909',
  Enum910 = '910',
  Enum911 = '911',
  Enum912 = '912',
  Enum914 = '914',
  R01 = 'R01',
  R02 = 'R02',
  R03 = 'R03',
  R04 = 'R04',
  R05 = 'R05',
  R06 = 'R06',
  R07 = 'R07',
  R08 = 'R08',
  R09 = 'R09',
  R10 = 'R10',
  R11 = 'R11',
  R12 = 'R12',
  R14 = 'R14',
  R15 = 'R15',
  R16 = 'R16',
  R17 = 'R17',
  R20 = 'R20',
  R21 = 'R21',
  R22 = 'R22',
  R23 = 'R23',
  R24 = 'R24',
  R29 = 'R29',
  R31 = 'R31',
  R33 = 'R33',
  R37 = 'R37',
  R38 = 'R38',
  R39 = 'R39',
  R51 = 'R51',
  R52 = 'R52',
  R53 = 'R53',
  Currencycloud = 'currencycloud',
}

/**
 * Schema for Code1
 */
export const code1Schema: Schema<Code1> = stringEnum(Code1);
