/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, object, Schema, string } from '../schema.js';

export interface Connection {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  /** Unique identifier for the bank or vendor. */
  vendorId: string;
  /** An identifier given to this connection by the bank. */
  vendorCustomerId: string | null;
  /** A human-friendly name for the bank or vendor. */
  vendorName: string;
}

export const connectionSchema: Schema<Connection> = object({
  id: ['id', string()],
  object: ['object', string()],
  liveMode: ['live_mode', boolean()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  discardedAt: ['discarded_at', nullable(string())],
  vendorId: ['vendor_id', string()],
  vendorCustomerId: ['vendor_customer_id', nullable(string())],
  vendorName: ['vendor_name', string()],
});
