/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ContactIdentifierType
 */
export enum ContactIdentifierType {
  Email = 'email',
  PhoneNumber = 'phone_number',
  Website = 'website',
}

/**
 * Schema for ContactIdentifierType
 */
export const contactIdentifierTypeSchema: Schema<ContactIdentifierType> = stringEnum(
  ContactIdentifierType
);
