/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ContactIdentifierTypeEnum
 */
export enum ContactIdentifierTypeEnum {
  Email = 'email',
  PhoneNumber = 'phone_number',
  Website = 'website',
}

/**
 * Schema for ContactIdentifierTypeEnum
 */
export const contactIdentifierTypeEnumSchema: Schema<ContactIdentifierTypeEnum> = stringEnum(
  ContactIdentifierTypeEnum
);
