/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ContentTypeEnum
 */
export enum ContentTypeEnum {
  EnumApplicationjson = 'application/json',
  EnumMultipartformdata = 'multipart/form-data',
}

/**
 * Schema for ContentTypeEnum
 */
export const contentTypeEnumSchema: Schema<ContentTypeEnum> = stringEnum(
  ContentTypeEnum
);
