/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, object, Schema, string } from '../schema.js';
import {
  ContactIdentifierType,
  contactIdentifierTypeSchema,
} from './contactIdentifierType.js';

export interface ContactDetail {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  contactIdentifier: string;
  contactIdentifierType: ContactIdentifierType;
}

export const contactDetailSchema: Schema<ContactDetail> = object({
  id: ['id', string()],
  object: ['object', string()],
  liveMode: ['live_mode', boolean()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  discardedAt: ['discarded_at', nullable(string())],
  contactIdentifier: ['contact_identifier', string()],
  contactIdentifierType: [
    'contact_identifier_type',
    contactIdentifierTypeSchema,
  ],
});
