/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema.js';

export interface CounterpartyCollectAccountResponse {
  /** The id of the existing counterparty. */
  id: string;
  /** This field will be `true` if an email requesting account details has already been sent to this counterparty. */
  isResend: boolean;
  /** This is the link to the secure Modern Treasury form. By default, Modern Treasury will send an email to your counterparty that includes a link to this form. However, if `send_email` is passed as `false` in the body then Modern Treasury will not send the email and you can send it to the counterparty directly. */
  formLink: string;
}

export const counterpartyCollectAccountResponseSchema: Schema<CounterpartyCollectAccountResponse> = object(
  {
    id: ['id', string()],
    isResend: ['is_resend', boolean()],
    formLink: ['form_link', string()],
  }
);
