/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CounterpartyUpdateRequest {
  /** A new name for the counterparty. Will only update if passed. */
  name?: string;
  /** A new email for the counterparty. */
  email?: string;
  /** Additional data in the form of key-value pairs. Pairs can be removed by passing an empty string or `null` as the value. */
  metadata?: Record<string, string>;
  /** If this is `true`, Modern Treasury will send an email to the counterparty whenever an associated payment order is sent to the bank. */
  sendRemittanceAdvice?: boolean;
  /** Either a valid SSN or EIN. */
  taxpayerIdentifier?: string;
  additionalProperties?: Record<string, unknown>;
}

export const counterpartyUpdateRequestSchema: Schema<CounterpartyUpdateRequest> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    email: ['email', optional(string())],
    metadata: ['metadata', optional(dict(string()))],
    sendRemittanceAdvice: ['send_remittance_advice', optional(boolean())],
    taxpayerIdentifier: ['taxpayer_identifier', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
