/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  lazy,
  nullable,
  object,
  Schema,
  string,
} from '../schema.js';
import { Account, accountSchema } from './account.js';
import {
  VerificationStatus1,
  verificationStatus1Schema,
} from './verificationStatus1.js';

export interface Counterparty {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  /** A human friendly name for this counterparty. */
  name: string | null;
  /** The accounts for this counterparty. */
  accounts: Account[];
  /** The counterparty's email. */
  email: string | null;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string>;
  /** Send an email to the counterparty whenever an associated payment order is sent to the bank. */
  sendRemittanceAdvice: boolean;
  /** The verification status of the counterparty. */
  verificationStatus: VerificationStatus1;
}

export const counterpartySchema: Schema<Counterparty> = lazy(() =>
  object({
    id: ['id', string()],
    object: ['object', string()],
    liveMode: ['live_mode', boolean()],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    discardedAt: ['discarded_at', nullable(string())],
    name: ['name', nullable(string())],
    accounts: ['accounts', array(accountSchema)],
    email: ['email', nullable(string())],
    metadata: ['metadata', dict(string())],
    sendRemittanceAdvice: ['send_remittance_advice', boolean()],
    verificationStatus: ['verification_status', verificationStatus1Schema],
  })
);
