/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CreatedAt
 */
export enum CreatedAt {
  Asc = 'asc',
  Desc = 'desc',
}

/**
 * Schema for CreatedAt
 */
export const createdAtSchema: Schema<CreatedAt> = stringEnum(CreatedAt);
