/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CreatedAtEnum
 */
export enum CreatedAtEnum {
  Asc = 'asc',
  Desc = 'desc',
}

/**
 * Schema for CreatedAtEnum
 */
export const createdAtEnumSchema: Schema<CreatedAtEnum> = stringEnum(
  CreatedAtEnum
);
