/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { ReturnableType1, returnableType1Schema } from './returnableType1.js';
import { Status5, status5Schema } from './status5.js';

/** If the return's status is `returned`, this will include the return object's data that is returning this return. */
export interface CurrentReturn {
  id?: string;
  object?: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode?: boolean;
  createdAt?: string;
  updatedAt?: string;
  status?: Status5;
  returnableId?: string | null;
  returnableType?: ReturnableType1 | null;
}

export const currentReturnSchema: Schema<CurrentReturn> = object({
  id: ['id', optional(string())],
  object: ['object', optional(string())],
  liveMode: ['live_mode', optional(boolean())],
  createdAt: ['created_at', optional(string())],
  updatedAt: ['updated_at', optional(string())],
  status: ['status', optional(status5Schema)],
  returnableId: ['returnable_id', optional(nullable(string()))],
  returnableType: [
    'returnable_type',
    optional(nullable(returnableType1Schema)),
  ],
});
