/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Currency1
 */
export enum Currency1 {
  Usd = 'USD',
  Cad = 'CAD',
}

/**
 * Schema for Currency1
 */
export const currency1Schema: Schema<Currency1> = stringEnum(Currency1);
