/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction5
 */
export enum Direction5 {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for Direction5
 */
export const direction5Schema: Schema<Direction5> = stringEnum(Direction5);
