/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction14Enum
 */
export enum Direction14Enum {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for Direction14Enum
 */
export const direction14EnumSchema: Schema<Direction14Enum> = stringEnum(
  Direction14Enum
);
