/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction15Enum
 */
export enum Direction15Enum {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for Direction15Enum
 */
export const direction15EnumSchema: Schema<Direction15Enum> = stringEnum(
  Direction15Enum
);
