/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction9
 */
export enum Direction9 {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for Direction9
 */
export const direction9Schema: Schema<Direction9> = stringEnum(Direction9);
