/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction4Enum
 */
export enum Direction4Enum {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for Direction4Enum
 */
export const direction4EnumSchema: Schema<Direction4Enum> = stringEnum(
  Direction4Enum
);
