/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction1
 */
export enum Direction1 {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for Direction1
 */
export const direction1Schema: Schema<Direction1> = stringEnum(Direction1);
