/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction15
 */
export enum Direction15 {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for Direction15
 */
export const direction15Schema: Schema<Direction15> = stringEnum(Direction15);
