/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction10
 */
export enum Direction10 {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for Direction10
 */
export const direction10Schema: Schema<Direction10> = stringEnum(Direction10);
