/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction10Enum
 */
export enum Direction10Enum {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for Direction10Enum
 */
export const direction10EnumSchema: Schema<Direction10Enum> = stringEnum(
  Direction10Enum
);
