/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction14
 */
export enum Direction14 {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for Direction14
 */
export const direction14Schema: Schema<Direction14> = stringEnum(Direction14);
