/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import {
  DocumentableType1Enum,
  documentableType1EnumSchema,
} from './documentableType1Enum.js';

export interface DocumentCreateRequest {
  /** The unique identifier for the associated object. */
  documentableId: string;
  documentableType: DocumentableType1Enum;
  /** A category given to the document, can be `null`. */
  documentType?: string;
  file: string;
}

export const documentCreateRequestSchema: Schema<DocumentCreateRequest> = object(
  {
    documentableId: ['documentable_id', string()],
    documentableType: ['documentable_type', documentableType1EnumSchema],
    documentType: ['document_type', optional(string())],
    file: ['file', string()],
  }
);
