/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, object, Schema, string } from '../schema.js';

export interface DocumentDetail {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  documentIdentifierType: string;
  documentIdentifier: string;
}

export const documentDetailSchema: Schema<DocumentDetail> = object({
  id: ['id', string()],
  object: ['object', string()],
  liveMode: ['live_mode', boolean()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  discardedAt: ['discarded_at', nullable(string())],
  documentIdentifierType: ['document_identifier_type', string()],
  documentIdentifier: ['document_identifier', string()],
});
