/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DocumentableTypeEnum
 */
export enum DocumentableTypeEnum {
  Case = 'case',
  Counterparty = 'counterparty',
  ExpectedPayment = 'expected_payment',
  ExternalAccount = 'external_account',
  InternalAccount = 'internal_account',
  Organization = 'organization',
  PaperItem = 'paper_item',
  PaymentOrder = 'payment_order',
  Transaction = 'transaction',
  Decision = 'decision',
  Connection = 'connection',
}

/**
 * Schema for DocumentableTypeEnum
 */
export const documentableTypeEnumSchema: Schema<DocumentableTypeEnum> = stringEnum(
  DocumentableTypeEnum
);
