/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DocumentableType2Enum
 */
export enum DocumentableType2Enum {
  Cases = 'cases',
  Counterparties = 'counterparties',
  ExpectedPayments = 'expected_payments',
  ExternalAccounts = 'external_accounts',
  InternalAccounts = 'internal_accounts',
  Organizations = 'organizations',
  PaperItems = 'paper_items',
  PaymentOrders = 'payment_orders',
  Transactions = 'transactions',
  Decisions = 'decisions',
  Connections = 'connections',
}

/**
 * Schema for DocumentableType2Enum
 */
export const documentableType2EnumSchema: Schema<DocumentableType2Enum> = stringEnum(
  DocumentableType2Enum
);
