/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EffectiveAt
 */
export enum EffectiveAt {
  Asc = 'asc',
  Desc = 'desc',
}

/**
 * Schema for EffectiveAt
 */
export const effectiveAtSchema: Schema<EffectiveAt> = stringEnum(EffectiveAt);
