/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { CodeEnum, codeEnumSchema } from './codeEnum.js';

export interface Errors {
  code?: CodeEnum;
  message?: string;
  parameter?: string;
}

export const errorsSchema: Schema<Errors> = object({
  code: ['code', optional(codeEnumSchema)],
  message: ['message', optional(string())],
  parameter: ['parameter', optional(string())],
});
