/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Code, codeSchema } from './code.js';

export interface Errors {
  code?: Code;
  message?: string;
  parameter?: string;
  additionalProperties?: Record<string, unknown>;
}

export const errorsSchema: Schema<Errors> = typedExpandoObject(
  {
    code: ['code', optional(codeSchema)],
    message: ['message', optional(string())],
    parameter: ['parameter', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
