/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { CurrencyEnum, currencyEnumSchema } from './currencyEnum.js';
import { Direction1Enum, direction1EnumSchema } from './direction1Enum.js';
import {
  ReconciliationMethodEnum,
  reconciliationMethodEnumSchema,
} from './reconciliationMethodEnum.js';
import { Status1Enum, status1EnumSchema } from './status1Enum.js';
import { Type1Enum, type1EnumSchema } from './type1Enum.js';

export interface ExpectedPayment {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  /** The highest amount this expected payment may be equal to. Value in specified currency's smallest unit. e.g. $10 would be represented as 1000. */
  amountUpperBound: number;
  /** The lowest amount this expected payment may be equal to. Value in specified currency's smallest unit. e.g. $10 would be represented as 1000. */
  amountLowerBound: number;
  /** One of credit or debit. When you are receiving money, use credit. When you are being charged, use debit. */
  direction: Direction1Enum;
  /** The ID of the Internal Account for the expected payment. */
  internalAccountId: string;
  /** One of: ach, au_becs, bacs, book, check, eft, interac, provxchange, rtp, sen, sepa, signet, wire. */
  type: Type1Enum | null;
  /** Three-letter ISO currency code. */
  currency: CurrencyEnum;
  /** The latest date the payment may come in. Format: yyyy-mm-dd */
  dateUpperBound: string | null;
  /** The earliest date the payment may come in. Format: yyyy-mm-dd */
  dateLowerBound: string | null;
  /** An optional description for internal use. */
  description: string | null;
  /** The statement description you expect to see on the transaction. For ACH payments, this will be the full line item passed from the bank. For wire payments, this will be the OBI field on the wire. For check payments, this will be the memo field. */
  statementDescriptor: string | null;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string>;
  /** The ID of the counterparty you expect for this payment. */
  counterpartyId: string | null;
  /** For `ach`, this field will be passed through on an addenda record. For `wire` payments the field will be passed through as the "Originator to Beneficiary Information", also known as OBI or Fedwire tag 6000. */
  remittanceInformation: string | null;
  /** The reconciliation groups you have for this payment. */
  reconciliationGroups?: unknown | null;
  /** The reconciliation filters you have for this payment. */
  reconciliationFilters?: unknown | null;
  /** The ID of the Transaction this expected payment object has been matched to. */
  transactionId: string | null;
  /** The ID of the Transaction Line Item this expected payment has been matched to. */
  transactionLineItemId: string | null;
  /** One of unreconciled, reconciled, or archived. */
  status: Status1Enum;
  /** One of manual if this expected payment was manually reconciled in the dashboard, automatic if it was automatically reconciled by Modern Treasury, or null if it is unreconciled. */
  reconciliationMethod: ReconciliationMethodEnum | null;
  /** The ID of the ledger transaction linked to the expected payment. */
  ledgerTransactionId: string | null;
}

export const expectedPaymentSchema: Schema<ExpectedPayment> = object({
  id: ['id', string()],
  object: ['object', string()],
  liveMode: ['live_mode', boolean()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  amountUpperBound: ['amount_upper_bound', number()],
  amountLowerBound: ['amount_lower_bound', number()],
  direction: ['direction', direction1EnumSchema],
  internalAccountId: ['internal_account_id', string()],
  type: ['type', nullable(type1EnumSchema)],
  currency: ['currency', currencyEnumSchema],
  dateUpperBound: ['date_upper_bound', nullable(string())],
  dateLowerBound: ['date_lower_bound', nullable(string())],
  description: ['description', nullable(string())],
  statementDescriptor: ['statement_descriptor', nullable(string())],
  metadata: ['metadata', dict(string())],
  counterpartyId: ['counterparty_id', nullable(string())],
  remittanceInformation: ['remittance_information', nullable(string())],
  reconciliationGroups: [
    'reconciliation_groups',
    optional(nullable(unknown())),
  ],
  reconciliationFilters: [
    'reconciliation_filters',
    optional(nullable(unknown())),
  ],
  transactionId: ['transaction_id', nullable(string())],
  transactionLineItemId: ['transaction_line_item_id', nullable(string())],
  status: ['status', status1EnumSchema],
  reconciliationMethod: [
    'reconciliation_method',
    nullable(reconciliationMethodEnumSchema),
  ],
  ledgerTransactionId: ['ledger_transaction_id', nullable(string())],
});
