/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ExternalAccountCompleteVerificationRequest {
  amounts?: number[];
  additionalProperties?: Record<string, unknown>;
}

export const externalAccountCompleteVerificationRequestSchema: Schema<ExternalAccountCompleteVerificationRequest> = typedExpandoObject(
  { amounts: ['amounts', optional(array(number()))] },
  'additionalProperties',
  optional(unknown())
);
