/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { CurrencyEnum, currencyEnumSchema } from './currencyEnum.js';
import {
  PaymentType4Enum,
  paymentType4EnumSchema,
} from './paymentType4Enum.js';

export interface ExternalAccountVerifyRequest {
  /** The ID of the internal account where the micro-deposits originate from. Both credit and debit capabilities must be enabled. */
  originatingAccountId: string;
  /** Both ach and eft are supported payment types. */
  paymentType: PaymentType4Enum;
  /** Three-letter ISO currency code. */
  currency?: CurrencyEnum;
}

export const externalAccountVerifyRequestSchema: Schema<ExternalAccountVerifyRequest> = object(
  {
    originatingAccountId: ['originating_account_id', string()],
    paymentType: ['payment_type', paymentType4EnumSchema],
    currency: ['currency', optional(currencyEnumSchema)],
  }
);
