/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  lazy,
  nullable,
  object,
  Schema,
  string,
} from '../schema.js';
import { AccountDetail, accountDetailSchema } from './accountDetail.js';
import { AccountType, accountTypeSchema } from './accountType.js';
import { Address, addressSchema } from './address.js';
import { ContactDetail, contactDetailSchema } from './contactDetail.js';
import { PartyType, partyTypeSchema } from './partyType.js';
import { RoutingDetail, routingDetailSchema } from './routingDetail.js';
import {
  VerificationStatus,
  verificationStatusSchema,
} from './verificationStatus.js';

export interface ExternalAccount {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  /** Can be `checking`, `savings` or `other`. */
  accountType: AccountType;
  /** Either `individual` or `business`. */
  partyType: PartyType | null;
  partyAddress: Address | null;
  /** A nickname for the external account. This is only for internal usage and won't affect any payments */
  name: string | null;
  counterpartyId: string | null;
  accountDetails: AccountDetail[];
  routingDetails: RoutingDetail[];
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string>;
  /** The legal name of the entity which owns the account. */
  partyName: string;
  contactDetails: ContactDetail[];
  /** If the external account links to a ledger account in Modern Treasury, the id of the ledger account will be populated here. */
  ledgerAccountId: string | null;
  verificationStatus: VerificationStatus;
}

export const externalAccountSchema: Schema<ExternalAccount> = lazy(() =>
  object({
    id: ['id', string()],
    object: ['object', string()],
    liveMode: ['live_mode', boolean()],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    discardedAt: ['discarded_at', nullable(string())],
    accountType: ['account_type', accountTypeSchema],
    partyType: ['party_type', nullable(partyTypeSchema)],
    partyAddress: ['party_address', nullable(addressSchema)],
    name: ['name', nullable(string())],
    counterpartyId: ['counterparty_id', nullable(string())],
    accountDetails: ['account_details', array(accountDetailSchema)],
    routingDetails: ['routing_details', array(routingDetailSchema)],
    metadata: ['metadata', dict(string())],
    partyName: ['party_name', string()],
    contactDetails: ['contact_details', array(contactDetailSchema)],
    ledgerAccountId: ['ledger_account_id', nullable(string())],
    verificationStatus: ['verification_status', verificationStatusSchema],
  })
);
