/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { AccountDetail1, accountDetail1Schema } from './accountDetail1.js';
import { AccountTypeEnum, accountTypeEnumSchema } from './accountTypeEnum.js';
import { AddressRequest, addressRequestSchema } from './addressRequest.js';
import {
  ContactDetailCreateRequest,
  contactDetailCreateRequestSchema,
} from './contactDetailCreateRequest.js';
import {
  LedgerAccountCreateRequest,
  ledgerAccountCreateRequestSchema,
} from './ledgerAccountCreateRequest.js';
import { PartyTypeEnum, partyTypeEnumSchema } from './partyTypeEnum.js';
import { RoutingDetail1, routingDetail1Schema } from './routingDetail1.js';

export interface ExternalAccountCreateRequest {
  /** Can be `checking`, `savings` or `other`. */
  accountType?: AccountTypeEnum;
  /** Either `individual` or `business`. */
  partyType?: PartyTypeEnum | null;
  partyAddress?: AddressRequest;
  /** A nickname for the external account. This is only for internal usage and won't affect any payments */
  name?: string | null;
  counterpartyId: string | null;
  accountDetails?: AccountDetail1[];
  routingDetails?: RoutingDetail1[];
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  /** If this value isn't provided, it will be inherited from the counterparty's name. */
  partyName?: string;
  partyIdentifier?: string;
  ledgerAccount?: LedgerAccountCreateRequest;
  /** If you've enabled the Modern Treasury + Plaid integration in your Plaid account, you can pass the processor token in this field. */
  plaidProcessorToken?: string;
  contactDetails?: ContactDetailCreateRequest[];
}

export const externalAccountCreateRequestSchema: Schema<ExternalAccountCreateRequest> = lazy(
  () =>
    object({
      accountType: ['account_type', optional(accountTypeEnumSchema)],
      partyType: ['party_type', optional(nullable(partyTypeEnumSchema))],
      partyAddress: ['party_address', optional(addressRequestSchema)],
      name: ['name', optional(nullable(string()))],
      counterpartyId: ['counterparty_id', nullable(string())],
      accountDetails: [
        'account_details',
        optional(array(accountDetail1Schema)),
      ],
      routingDetails: [
        'routing_details',
        optional(array(routingDetail1Schema)),
      ],
      metadata: ['metadata', optional(dict(string()))],
      partyName: ['party_name', optional(string())],
      partyIdentifier: ['party_identifier', optional(string())],
      ledgerAccount: [
        'ledger_account',
        optional(ledgerAccountCreateRequestSchema),
      ],
      plaidProcessorToken: ['plaid_processor_token', optional(string())],
      contactDetails: [
        'contact_details',
        optional(array(contactDetailCreateRequestSchema)),
      ],
    })
);
