/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AccountType, accountTypeSchema } from './accountType.js';
import { AddressRequest, addressRequestSchema } from './addressRequest.js';
import { PartyType, partyTypeSchema } from './partyType.js';

export interface ExternalAccountUpdateRequest {
  /** Either `individual` or `business`. */
  partyType?: PartyType | null;
  /** Can be `checking`, `savings` or `other`. */
  accountType?: AccountType;
  counterpartyId?: string | null;
  /** A nickname for the external account. This is only for internal usage and won't affect any payments */
  name?: string | null;
  /** If this value isn't provided, it will be inherited from the counterparty's name. */
  partyName?: string;
  partyAddress?: AddressRequest;
  /** Additional data in the form of key-value pairs. Pairs can be removed by passing an empty string or `null` as the value. */
  metadata?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const externalAccountUpdateRequestSchema: Schema<ExternalAccountUpdateRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        partyType: ['party_type', optional(nullable(partyTypeSchema))],
        accountType: ['account_type', optional(accountTypeSchema)],
        counterpartyId: ['counterparty_id', optional(nullable(string()))],
        name: ['name', optional(nullable(string()))],
        partyName: ['party_name', optional(string())],
        partyAddress: ['party_address', optional(addressRequestSchema)],
        metadata: ['metadata', optional(dict(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
