/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Currency, currencySchema } from './currency.js';
import { PaymentType4, paymentType4Schema } from './paymentType4.js';

export interface ExternalAccountVerifyRequest {
  /** The ID of the internal account where the micro-deposits originate from. Both credit and debit capabilities must be enabled. */
  originatingAccountId: string;
  /** Both ach and eft are supported payment types. */
  paymentType: PaymentType4;
  /** Three-letter ISO currency code. */
  currency?: Currency;
  additionalProperties?: Record<string, unknown>;
}

export const externalAccountVerifyRequestSchema: Schema<ExternalAccountVerifyRequest> = typedExpandoObject(
  {
    originatingAccountId: ['originating_account_id', string()],
    paymentType: ['payment_type', paymentType4Schema],
    currency: ['currency', optional(currencySchema)],
  },
  'additionalProperties',
  optional(unknown())
);
