/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for FallbackTypeEnum
 */
export enum FallbackTypeEnum {
  Ach = 'ach',
}

/**
 * Schema for FallbackTypeEnum
 */
export const fallbackTypeEnumSchema: Schema<FallbackTypeEnum> = stringEnum(
  FallbackTypeEnum
);
