/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for FallbackType
 */
export enum FallbackType {
  Ach = 'ach',
}

/**
 * Schema for FallbackType
 */
export const fallbackTypeSchema: Schema<FallbackType> = stringEnum(
  FallbackType
);
