/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for FieldEnum
 */
export enum FieldEnum {
  Name = 'name',
  NameOnAccount = 'nameOnAccount',
  TaxpayerIdentifier = 'taxpayerIdentifier',
  AccountType = 'accountType',
  AccountNumber = 'accountNumber',
  IbanNumber = 'ibanNumber',
  ClabeNumber = 'clabeNumber',
  WalletAddress = 'walletAddress',
  PanNumber = 'panNumber',
  RoutingNumber = 'routingNumber',
  AbaWireRoutingNumber = 'abaWireRoutingNumber',
  SwiftCode = 'swiftCode',
  AuBsb = 'auBsb',
  CaCpa = 'caCpa',
  Cnaps = 'cnaps',
  GbSortCode = 'gbSortCode',
  InIfsc = 'inIfsc',
  MyBranchCode = 'myBranchCode',
  BrCodigo = 'brCodigo',
  RoutingNumberType = 'routingNumberType',
  Address = 'address',
}

/**
 * Schema for FieldEnum
 */
export const fieldEnumSchema: Schema<FieldEnum> = stringEnum(FieldEnum);
