/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';

export interface File {
  /** The size of the document in bytes. */
  size?: number;
  /** The original filename of the document. */
  filename?: string;
  /** The MIME content type of the document. */
  contentType?: string;
}

export const fileSchema: Schema<File> = object({
  size: ['size', optional(number())],
  filename: ['filename', optional(string())],
  contentType: ['content_type', optional(string())],
});
