/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ForeignExchangeIndicatorEnum
 */
export enum ForeignExchangeIndicatorEnum {
  FixedToVariable = 'fixed_to_variable',
  VariableToFixed = 'variable_to_fixed',
}

/**
 * Schema for ForeignExchangeIndicatorEnum
 */
export const foreignExchangeIndicatorEnumSchema: Schema<ForeignExchangeIndicatorEnum> = stringEnum(
  ForeignExchangeIndicatorEnum
);
