/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ForeignExchangeIndicator
 */
export enum ForeignExchangeIndicator {
  FixedToVariable = 'fixed_to_variable',
  VariableToFixed = 'variable_to_fixed',
}

/**
 * Schema for ForeignExchangeIndicator
 */
export const foreignExchangeIndicatorSchema: Schema<ForeignExchangeIndicator> = stringEnum(
  ForeignExchangeIndicator
);
