/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { CurrencyEnum, currencyEnumSchema } from './currencyEnum.js';
import { Direction14Enum, direction14EnumSchema } from './direction14Enum.js';
import { Type10Enum, type10EnumSchema } from './type10Enum.js';

export interface IncomingPaymentDetailCreateRequest {
  /** One of `ach`, `wire`, `check`. */
  type?: Type10Enum;
  /** One of `credit`, `debit`. */
  direction?: Direction14Enum;
  /** Value in specified currency's smallest unit. e.g. $10 would be represented as 1000. */
  amount?: number;
  /** Three-letter ISO currency code. */
  currency?: CurrencyEnum;
  /** The ID of one of your internal accounts. */
  internalAccountId?: string;
  /** An optional parameter to associate the incoming payment detail to a virtual account. */
  virtualAccountId?: string | null;
  /** Defaults to today. */
  asOfDate?: string | null;
  /** Defaults to a random description. */
  description?: string | null;
}

export const incomingPaymentDetailCreateRequestSchema: Schema<IncomingPaymentDetailCreateRequest> = object(
  {
    type: ['type', optional(type10EnumSchema)],
    direction: ['direction', optional(direction14EnumSchema)],
    amount: ['amount', optional(number())],
    currency: ['currency', optional(currencyEnumSchema)],
    internalAccountId: ['internal_account_id', optional(string())],
    virtualAccountId: ['virtual_account_id', optional(nullable(string()))],
    asOfDate: ['as_of_date', optional(nullable(string()))],
    description: ['description', optional(nullable(string()))],
  }
);
