/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface IncomingPaymentDetailUpdateRequest {
  /** Additional data in the form of key-value pairs. Pairs can be removed by passing an empty string or `null` as the value. */
  metadata?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const incomingPaymentDetailUpdateRequestSchema: Schema<IncomingPaymentDetailUpdateRequest> = typedExpandoObject(
  { metadata: ['metadata', optional(dict(string()))] },
  'additionalProperties',
  optional(unknown())
);
