/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { Currency, currencySchema } from './currency.js';
import { Direction4, direction4Schema } from './direction4.js';
import {
  OriginatingAccountNumberType,
  originatingAccountNumberTypeSchema,
} from './originatingAccountNumberType.js';
import {
  OriginatingRoutingNumberType,
  originatingRoutingNumberTypeSchema,
} from './originatingRoutingNumberType.js';
import { Status2, status2Schema } from './status2.js';
import { Type4, type4Schema } from './type4.js';
import { VirtualAccount, virtualAccountSchema } from './virtualAccount.js';

export interface IncomingPaymentDetail {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  /** The ID of the Internal Account for the incoming payment detail. This is always present. */
  internalAccountId: string;
  /** If the incoming payment detail is in a virtual account, the ID of the Virtual Account. */
  virtualAccountId: string | null;
  virtualAccount: VirtualAccount;
  /** The ID of the reconciled Transaction Line Item or `null`. */
  transactionLineItemId: string | null;
  /** The ID of the reconciled Transaction or `null`. */
  transactionId: string | null;
  /** The ID of the ledger transaction linked to the incoming payment detail or `null`. */
  ledgerTransactionId: string | null;
  /** One of: `ach`, `book`, `check`, `eft`, `interac`, `rtp`, `sepa`, `signet`, or `wire`. */
  type: Type4;
  /** The raw data from the payment pre-notification file that we get from the bank. */
  data?: unknown;
  /** Value in specified currency's smallest unit. e.g. $10 would be represented as 1000. */
  amount: number;
  /** Three-letter ISO currency code. */
  currency: Currency;
  /** One of `credit` or `debit`. */
  direction: Direction4;
  /** The current status of the incoming payment order. One of `pending`, `completed`, or `returned`. */
  status: Status2;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string>;
  /** The date on which the corresponding transaction will occur. */
  asOfDate: string;
  /** The identifier of the vendor bank. */
  vendorId: string | null;
  /** The routing number of the originating account for the incoming payment detail. */
  originatingRoutingNumber: string | null;
  /** The type of the originating routing number for the incoming payment detail. */
  originatingRoutingNumberType: OriginatingRoutingNumberType | null;
  /** The account number of the originating account for the incoming payment detail. */
  originatingAccountNumber?: string | null;
  /** The last 4 digits of the originating account_number for the incoming payment detail. */
  originatingAccountNumberSafe: string | null;
  /** The type of the originating account number for the incoming payment detail. */
  originatingAccountNumberType: OriginatingAccountNumberType | null;
}

export const incomingPaymentDetailSchema: Schema<IncomingPaymentDetail> = lazy(
  () =>
    object({
      id: ['id', string()],
      object: ['object', string()],
      liveMode: ['live_mode', boolean()],
      createdAt: ['created_at', string()],
      updatedAt: ['updated_at', string()],
      internalAccountId: ['internal_account_id', string()],
      virtualAccountId: ['virtual_account_id', nullable(string())],
      virtualAccount: ['virtual_account', virtualAccountSchema],
      transactionLineItemId: ['transaction_line_item_id', nullable(string())],
      transactionId: ['transaction_id', nullable(string())],
      ledgerTransactionId: ['ledger_transaction_id', nullable(string())],
      type: ['type', type4Schema],
      data: ['data', optional(unknown())],
      amount: ['amount', number()],
      currency: ['currency', currencySchema],
      direction: ['direction', direction4Schema],
      status: ['status', status2Schema],
      metadata: ['metadata', dict(string())],
      asOfDate: ['as_of_date', string()],
      vendorId: ['vendor_id', nullable(string())],
      originatingRoutingNumber: [
        'originating_routing_number',
        nullable(string()),
      ],
      originatingRoutingNumberType: [
        'originating_routing_number_type',
        nullable(originatingRoutingNumberTypeSchema),
      ],
      originatingAccountNumber: [
        'originating_account_number',
        optional(nullable(string())),
      ],
      originatingAccountNumberSafe: [
        'originating_account_number_safe',
        nullable(string()),
      ],
      originatingAccountNumberType: [
        'originating_account_number_type',
        nullable(originatingAccountNumberTypeSchema),
      ],
    })
);
