/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Currency, currencySchema } from './currency.js';
import { Direction14, direction14Schema } from './direction14.js';
import { Type10, type10Schema } from './type10.js';

export interface IncomingPaymentDetailCreateRequest {
  /** One of `ach`, `wire`, `check`. */
  type?: Type10;
  /** One of `credit`, `debit`. */
  direction?: Direction14;
  /** Value in specified currency's smallest unit. e.g. $10 would be represented as 1000. */
  amount?: number;
  /** Three-letter ISO currency code. */
  currency?: Currency;
  /** The ID of one of your internal accounts. */
  internalAccountId?: string;
  /** An optional parameter to associate the incoming payment detail to a virtual account. */
  virtualAccountId?: string | null;
  /** Defaults to today. */
  asOfDate?: string | null;
  /** Defaults to a random description. */
  description?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const incomingPaymentDetailCreateRequestSchema: Schema<IncomingPaymentDetailCreateRequest> = typedExpandoObject(
  {
    type: ['type', optional(type10Schema)],
    direction: ['direction', optional(direction14Schema)],
    amount: ['amount', optional(number())],
    currency: ['currency', optional(currencySchema)],
    internalAccountId: ['internal_account_id', optional(string())],
    virtualAccountId: ['virtual_account_id', optional(nullable(string()))],
    asOfDate: ['as_of_date', optional(nullable(string()))],
    description: ['description', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
