/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InternalAccountUpdateRequest {
  /** The nickname for the internal account. */
  name?: string;
  /** Additional data in the form of key-value pairs. Pairs can be removed by passing an empty string or `null` as the value. */
  metadata?: Record<string, string>;
  /** The parent internal account for this account. */
  parentAccountId?: string;
  /** The Counterparty associated to this account. */
  counterpartyId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const internalAccountUpdateRequestSchema: Schema<InternalAccountUpdateRequest> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    metadata: ['metadata', optional(dict(string()))],
    parentAccountId: ['parent_account_id', optional(string())],
    counterpartyId: ['counterparty_id', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
