/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, object, optional, Schema, string } from '../schema.js';
import { Currency1Enum, currency1EnumSchema } from './currency1Enum.js';
import { PartyAddress, partyAddressSchema } from './partyAddress.js';

export interface InternalAccountCreateRequest {
  /** The identifier of the financial institution the account belongs to. */
  connectionId: string;
  /** The nickname of the account. */
  name: string;
  /** The legal name of the entity which owns the account. */
  partyName: string;
  /** The address associated with the owner or null. */
  partyAddress?: PartyAddress;
  /** Either "USD" or "CAD". Internal accounts created at Increase only supports "USD". */
  currency: Currency1Enum;
  /** A hash of vendor specific attributes that will be used when creating the account at the vendor specified by the given connection. */
  vendorAttributes?: Record<string, string>;
  /** The parent internal account of this new account. */
  parentAccountId?: string;
  /** The Counterparty associated to this account. */
  counterpartyId?: string;
}

export const internalAccountCreateRequestSchema: Schema<InternalAccountCreateRequest> = lazy(
  () =>
    object({
      connectionId: ['connection_id', string()],
      name: ['name', string()],
      partyName: ['party_name', string()],
      partyAddress: ['party_address', optional(partyAddressSchema)],
      currency: ['currency', currency1EnumSchema],
      vendorAttributes: ['vendor_attributes', optional(dict(string()))],
      parentAccountId: ['parent_account_id', optional(string())],
      counterpartyId: ['counterparty_id', optional(string())],
    })
);
