/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  lazy,
  nullable,
  object,
  Schema,
  string,
} from '../schema.js';
import { AccountDetail, accountDetailSchema } from './accountDetail.js';
import { AccountType5, accountType5Schema } from './accountType5.js';
import { Address, addressSchema } from './address.js';
import { Connection, connectionSchema } from './connection.js';
import { Currency, currencySchema } from './currency.js';
import { PartyType5, partyType5Schema } from './partyType5.js';
import { RoutingDetail, routingDetailSchema } from './routingDetail.js';

export interface InternalAccount {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  /** Can be checking, savings or other. */
  accountType: AccountType5 | null;
  /** The legal name of the entity which owns the account. */
  partyName: string;
  /** Either individual or business. */
  partyType: PartyType5 | null;
  partyAddress: Address | null;
  /** A nickname for the account. */
  name: string | null;
  /** An array of account detail objects. */
  accountDetails: AccountDetail[];
  /** An array of routing detail objects. */
  routingDetails: RoutingDetail[];
  connection: Connection;
  /** Three-letter ISO currency code. */
  currency: Currency;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string>;
  /** The parent InternalAccount of this account. */
  parentAccountId: string | null;
  /** The Counterparty associated to this account. */
  counterpartyId: string | null;
  /** If the internal account links to a ledger account in Modern Treasury, the id of the ledger account will be populated here. */
  ledgerAccountId: string | null;
}

export const internalAccountSchema: Schema<InternalAccount> = lazy(() =>
  object({
    id: ['id', string()],
    object: ['object', string()],
    liveMode: ['live_mode', boolean()],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    accountType: ['account_type', nullable(accountType5Schema)],
    partyName: ['party_name', string()],
    partyType: ['party_type', nullable(partyType5Schema)],
    partyAddress: ['party_address', nullable(addressSchema)],
    name: ['name', nullable(string())],
    accountDetails: ['account_details', array(accountDetailSchema)],
    routingDetails: ['routing_details', array(routingDetailSchema)],
    connection: ['connection', connectionSchema],
    currency: ['currency', currencySchema],
    metadata: ['metadata', dict(string())],
    parentAccountId: ['parent_account_id', nullable(string())],
    counterpartyId: ['counterparty_id', nullable(string())],
    ledgerAccountId: ['ledger_account_id', nullable(string())],
  })
);
