/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import { ContactDetail, contactDetailSchema } from './contactDetail.js';
import {
  CounterpartyBillingAddress,
  counterpartyBillingAddressSchema,
} from './counterpartyBillingAddress.js';
import {
  CounterpartyShippingAddress,
  counterpartyShippingAddressSchema,
} from './counterpartyShippingAddress.js';
import { Currency, currencySchema } from './currency.js';
import { InvoicerAddress, invoicerAddressSchema } from './invoicerAddress.js';
import { PaymentMethod, paymentMethodSchema } from './paymentMethod.js';
import { PaymentOrder, paymentOrderSchema } from './paymentOrder.js';
import { PaymentType5, paymentType5Schema } from './paymentType5.js';
import { Status5, status5Schema } from './status5.js';

export interface Invoice {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  /** The invoicer's contact details displayed at the top of the invoice. */
  contactDetails: ContactDetail[];
  /** The ID of the counterparty receiving the invoice. */
  counterpartyId: string;
  /** The counterparty's billing address. */
  counterpartyBillingAddress: CounterpartyBillingAddress | null;
  /** The counterparty's shipping address where physical goods should be delivered. */
  counterpartyShippingAddress: CounterpartyShippingAddress | null;
  /** Three-letter ISO currency code. */
  currency: Currency;
  /** A free-form description of the invoice. */
  description: string;
  /** A future date by when the invoice needs to be paid. */
  dueDate: string;
  /** The invoice issuer's business address. */
  invoicerAddress: InvoicerAddress | null;
  /** The ID of the internal account the invoice should be paid to. */
  originatingAccountId: string;
  /** The receiving account ID. Can be an `internal_account`. */
  receivingAccountId: string | null;
  /** Date transactions are to be posted to the participants' account. Defaults to the current business day or the next business day if the current day is a bank holiday or weekend. Format: yyyy-mm-dd. */
  paymentEffectiveDate: string | null;
  /** One of `ach` or `eft` */
  paymentType: PaymentType5 | null;
  /** When opening an invoice, whether to show the embedded payment UI , automatically debit the recipient, or rely on manual payment from the recipient. */
  paymentMethod: PaymentMethod | null;
  /** The URL of the hosted web UI where the invoice can be viewed. */
  hostedUrl: string;
  /** A unique record number assigned to each invoice that is issued. */
  number: string;
  /** The payment orders created for paying the invoice through the invoice payment UI. */
  paymentOrders: PaymentOrder[];
  /** The URL where the invoice PDF can be downloaded. */
  pdfUrl: string | null;
  /** The status of the invoice. */
  status: Status5;
  /** Total amount due in specified currency's smallest unit, e.g., $10 USD would be represented as 1000. */
  totalAmount: number;
}

export const invoiceSchema: Schema<Invoice> = lazy(() =>
  object({
    id: ['id', string()],
    object: ['object', string()],
    liveMode: ['live_mode', boolean()],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    contactDetails: ['contact_details', array(contactDetailSchema)],
    counterpartyId: ['counterparty_id', string()],
    counterpartyBillingAddress: [
      'counterparty_billing_address',
      nullable(counterpartyBillingAddressSchema),
    ],
    counterpartyShippingAddress: [
      'counterparty_shipping_address',
      nullable(counterpartyShippingAddressSchema),
    ],
    currency: ['currency', currencySchema],
    description: ['description', string()],
    dueDate: ['due_date', string()],
    invoicerAddress: ['invoicer_address', nullable(invoicerAddressSchema)],
    originatingAccountId: ['originating_account_id', string()],
    receivingAccountId: ['receiving_account_id', nullable(string())],
    paymentEffectiveDate: ['payment_effective_date', nullable(string())],
    paymentType: ['payment_type', nullable(paymentType5Schema)],
    paymentMethod: ['payment_method', nullable(paymentMethodSchema)],
    hostedUrl: ['hosted_url', string()],
    number: ['number', string()],
    paymentOrders: ['payment_orders', array(paymentOrderSchema)],
    pdfUrl: ['pdf_url', nullable(string())],
    status: ['status', status5Schema],
    totalAmount: ['total_amount', number()],
  })
);
