/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { ContactDetail, contactDetailSchema } from './contactDetail.js';
import {
  CounterpartyBillingAddress,
  counterpartyBillingAddressSchema,
} from './counterpartyBillingAddress.js';
import {
  CounterpartyShippingAddress,
  counterpartyShippingAddressSchema,
} from './counterpartyShippingAddress.js';
import { CurrencyEnum, currencyEnumSchema } from './currencyEnum.js';
import { InvoicerAddress, invoicerAddressSchema } from './invoicerAddress.js';
import {
  PaymentMethod1Enum,
  paymentMethod1EnumSchema,
} from './paymentMethod1Enum.js';
import {
  PaymentType6Enum,
  paymentType6EnumSchema,
} from './paymentType6Enum.js';

export interface InvoiceLineItemUpdateRequest {
  /** The invoicer's contact details displayed at the top of the invoice. */
  contactDetails?: ContactDetail[];
  /** The ID of the counterparty receiving the invoice. */
  counterpartyId?: string;
  /** The counterparty's billing address. */
  counterpartyBillingAddress?: CounterpartyBillingAddress | null;
  /** The counterparty's shipping address where physical goods should be delivered. */
  counterpartyShippingAddress?: CounterpartyShippingAddress | null;
  /** Three-letter ISO currency code. */
  currency?: CurrencyEnum;
  /** A free-form description of the invoice. */
  description?: string;
  /** A future date by when the invoice needs to be paid. */
  dueDate?: string;
  /** The invoice issuer's business address. */
  invoicerAddress?: InvoicerAddress | null;
  /** The ID of the internal account the invoice should be paid to. */
  originatingAccountId?: string;
  /** The receiving account ID. Can be an `external_account`. */
  receivingAccountId?: string;
  /** Date transactions are to be posted to the participants' account. Defaults to the current business day or the next business day if the current day is a bank holiday or weekend. Format: yyyy-mm-dd. */
  paymentEffectiveDate?: string;
  /** One of `ach`, `eft`, `wire`, `check`, `sen`, `book`, `rtp`, `sepa`, `bacs`, `au_becs`, `interac`, `signet`, `provexchange`. */
  paymentType?: PaymentType6Enum;
  /** The method by which the invoice can be paid. `ui` will show the embedded payment collection flow. `automatic` will automatically initiate payment based upon the account details of the receiving_account id.\nIf the invoice amount is positive, the automatically initiated payment order's direction will be debit. If the invoice amount is negative, the automatically initiated payment order's direction will be credit. One of `manual`, `ui`, or `automatic`. */
  paymentMethod?: PaymentMethod1Enum;
}

export const invoiceLineItemUpdateRequestSchema: Schema<InvoiceLineItemUpdateRequest> = lazy(
  () =>
    object({
      contactDetails: ['contact_details', optional(array(contactDetailSchema))],
      counterpartyId: ['counterparty_id', optional(string())],
      counterpartyBillingAddress: [
        'counterparty_billing_address',
        optional(nullable(counterpartyBillingAddressSchema)),
      ],
      counterpartyShippingAddress: [
        'counterparty_shipping_address',
        optional(nullable(counterpartyShippingAddressSchema)),
      ],
      currency: ['currency', optional(currencyEnumSchema)],
      description: ['description', optional(string())],
      dueDate: ['due_date', optional(string())],
      invoicerAddress: [
        'invoicer_address',
        optional(nullable(invoicerAddressSchema)),
      ],
      originatingAccountId: ['originating_account_id', optional(string())],
      receivingAccountId: ['receiving_account_id', optional(string())],
      paymentEffectiveDate: ['payment_effective_date', optional(string())],
      paymentType: ['payment_type', optional(paymentType6EnumSchema)],
      paymentMethod: ['payment_method', optional(paymentMethod1EnumSchema)],
    })
);
