/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ItemizableType
 */
export enum ItemizableType {
  ExpectedPayment = 'ExpectedPayment',
  PaymentOrder = 'PaymentOrder',
}

/**
 * Schema for ItemizableType
 */
export const itemizableTypeSchema: Schema<ItemizableType> = stringEnum(
  ItemizableType
);
