/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ItemizableType1Enum
 */
export enum ItemizableType1Enum {
  ExpectedPayments = 'expected_payments',
  PaymentOrders = 'payment_orders',
}

/**
 * Schema for ItemizableType1Enum
 */
export const itemizableType1EnumSchema: Schema<ItemizableType1Enum> = stringEnum(
  ItemizableType1Enum
);
