/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ItemizableTypeEnum
 */
export enum ItemizableTypeEnum {
  ExpectedPayment = 'ExpectedPayment',
  PaymentOrder = 'PaymentOrder',
}

/**
 * Schema for ItemizableTypeEnum
 */
export const itemizableTypeEnumSchema: Schema<ItemizableTypeEnum> = stringEnum(
  ItemizableTypeEnum
);
