/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for LedgerableType6Enum
 */
export enum LedgerableType6Enum {
  Counterparty = 'counterparty',
  ExpectedPayment = 'expected_payment',
  IncomingPaymentDetail = 'incoming_payment_detail',
  InternalAccount = 'internal_account',
  LineItem = 'line_item',
  PaperItem = 'paper_item',
  PaymentOrder = 'payment_order',
  PaymentOrderAttempt = 'payment_order_attempt',
  Return = 'return',
  Reversal = 'reversal',
}

/**
 * Schema for LedgerableType6Enum
 */
export const ledgerableType6EnumSchema: Schema<LedgerableType6Enum> = stringEnum(
  LedgerableType6Enum
);
