/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for LedgerAccountNormalBalance
 */
export enum LedgerAccountNormalBalance {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for LedgerAccountNormalBalance
 */
export const ledgerAccountNormalBalanceSchema: Schema<LedgerAccountNormalBalance> = stringEnum(
  LedgerAccountNormalBalance
);
