/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Status9, status9Schema } from './status9.js';

export interface LedgerAccountPayoutUpdateRequest {
  /** The description of the ledger account payout. */
  description?: string | null;
  /** To post a pending ledger account payout, use `posted`. To archive a pending ledger transaction, use `archived`. */
  status?: Status9;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const ledgerAccountPayoutUpdateRequestSchema: Schema<LedgerAccountPayoutUpdateRequest> = typedExpandoObject(
  {
    description: ['description', optional(nullable(string()))],
    status: ['status', optional(status9Schema)],
    metadata: ['metadata', optional(dict(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
