/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for LedgerTypeEnum
 */
export enum LedgerTypeEnum {
  Customer = 'customer',
  Vendor = 'vendor',
}

/**
 * Schema for LedgerTypeEnum
 */
export const ledgerTypeEnumSchema: Schema<LedgerTypeEnum> = stringEnum(
  LedgerTypeEnum
);
