/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  lazy,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import {
  LedgerAccountNormalBalanceEnum,
  ledgerAccountNormalBalanceEnumSchema,
} from './ledgerAccountNormalBalanceEnum.js';
import { LedgerBalances, ledgerBalancesSchema } from './ledgerBalances.js';

export interface LedgerAccountStatement {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  /** The id of the ledger that this ledger account statement belongs to. */
  ledgerId: string;
  /** The description of the ledger account statement. */
  description: string | null;
  /** The id of the ledger account whose ledger entries are queried against, and its balances are computed as a result. */
  ledgerAccountId: string;
  /** Lock version of the ledger account at the time of statement generation. */
  ledgerAccountLockVersion: number;
  /** The normal balance of the ledger account. */
  ledgerAccountNormalBalance: LedgerAccountNormalBalanceEnum;
  /** The inclusive lower bound of the effective_at timestamp of the ledger entries to be included in the ledger account statement. */
  effectiveAtLowerBound: string;
  /** The exclusive upper bound of the effective_at timestamp of the ledger entries to be included in the ledger account statement. */
  effectiveAtUpperBound: string;
  startingBalance: LedgerBalances;
  endingBalance: LedgerBalances;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string>;
}

export const ledgerAccountStatementSchema: Schema<LedgerAccountStatement> = lazy(
  () =>
    object({
      id: ['id', string()],
      object: ['object', string()],
      liveMode: ['live_mode', boolean()],
      createdAt: ['created_at', string()],
      updatedAt: ['updated_at', string()],
      ledgerId: ['ledger_id', string()],
      description: ['description', nullable(string())],
      ledgerAccountId: ['ledger_account_id', string()],
      ledgerAccountLockVersion: ['ledger_account_lock_version', number()],
      ledgerAccountNormalBalance: [
        'ledger_account_normal_balance',
        ledgerAccountNormalBalanceEnumSchema,
      ],
      effectiveAtLowerBound: ['effective_at_lower_bound', string()],
      effectiveAtUpperBound: ['effective_at_upper_bound', string()],
      startingBalance: ['starting_balance', ledgerBalancesSchema],
      endingBalance: ['ending_balance', ledgerBalancesSchema],
      metadata: ['metadata', dict(string())],
    })
);
