/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface LedgerAccountUpdateRequest {
  /** The name of the ledger account. */
  name?: string;
  /** The description of the ledger account. */
  description?: string | null;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const ledgerAccountUpdateRequestSchema: Schema<LedgerAccountUpdateRequest> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    description: ['description', optional(nullable(string()))],
    metadata: ['metadata', optional(dict(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
