/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  lazy,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import {
  LedgerableTypeEnum,
  ledgerableTypeEnumSchema,
} from './ledgerableTypeEnum.js';
import {
  LedgerBalancesWithEffectiveAt,
  ledgerBalancesWithEffectiveAtSchema,
} from './ledgerBalancesWithEffectiveAt.js';
import {
  NormalBalanceEnum,
  normalBalanceEnumSchema,
} from './normalBalanceEnum.js';

export interface LedgerAccount {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  /** The name of the ledger account. */
  name: string;
  /** The description of the ledger account. */
  description: string | null;
  /** The normal balance of the ledger account. */
  normalBalance: NormalBalanceEnum;
  balances: LedgerBalancesWithEffectiveAt;
  /** Lock version of the ledger account. */
  lockVersion: number;
  /** The id of the ledger that this account belongs to. */
  ledgerId: string;
  /** If the ledger account links to another object in Modern Treasury, the id will be populated here, otherwise null. */
  ledgerableId: string | null;
  /** If the ledger account links to another object in Modern Treasury, the type will be populated here, otherwise null. The value is one of internal_account or external_account. */
  ledgerableType: LedgerableTypeEnum | null;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string>;
}

export const ledgerAccountSchema: Schema<LedgerAccount> = lazy(() =>
  object({
    id: ['id', string()],
    object: ['object', string()],
    liveMode: ['live_mode', boolean()],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    discardedAt: ['discarded_at', nullable(string())],
    name: ['name', string()],
    description: ['description', nullable(string())],
    normalBalance: ['normal_balance', normalBalanceEnumSchema],
    balances: ['balances', ledgerBalancesWithEffectiveAtSchema],
    lockVersion: ['lock_version', number()],
    ledgerId: ['ledger_id', string()],
    ledgerableId: ['ledgerable_id', nullable(string())],
    ledgerableType: ['ledgerable_type', nullable(ledgerableTypeEnumSchema)],
    metadata: ['metadata', dict(string())],
  })
);
