/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for LedgerableType2
 */
export enum LedgerableType2 {
  Counterparty = 'counterparty',
  ExpectedPayment = 'expected_payment',
  IncomingPaymentDetail = 'incoming_payment_detail',
  InternalAccount = 'internal_account',
  LineItem = 'line_item',
  PaperItem = 'paper_item',
  PaymentOrder = 'payment_order',
  PaymentOrderAttempt = 'payment_order_attempt',
  Return = 'return',
  Reversal = 'reversal',
}

/**
 * Schema for LedgerableType2
 */
export const ledgerableType2Schema: Schema<LedgerableType2> = stringEnum(
  LedgerableType2
);
