/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  LedgerableTypeEnum,
  ledgerableTypeEnumSchema,
} from './ledgerableTypeEnum.js';
import {
  NormalBalanceEnum,
  normalBalanceEnumSchema,
} from './normalBalanceEnum.js';

export interface LedgerAccountCreateRequest {
  /** The name of the ledger account. */
  name: string;
  /** The description of the ledger account. */
  description?: string | null;
  /** The normal balance of the ledger account. */
  normalBalance: NormalBalanceEnum;
  /** The id of the ledger that this account belongs to. */
  ledgerId: string;
  /** The currency of the ledger account. */
  currency: string;
  /** The currency exponent of the ledger account. */
  currencyExponent?: number | null;
  /** If the ledger account links to another object in Modern Treasury, the id will be populated here, otherwise null. */
  ledgerableId?: string;
  /** If the ledger account links to another object in Modern Treasury, the type will be populated here, otherwise null. The value is one of internal_account or external_account. */
  ledgerableType?: LedgerableTypeEnum;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
}

export const ledgerAccountCreateRequestSchema: Schema<LedgerAccountCreateRequest> = object(
  {
    name: ['name', string()],
    description: ['description', optional(nullable(string()))],
    normalBalance: ['normal_balance', normalBalanceEnumSchema],
    ledgerId: ['ledger_id', string()],
    currency: ['currency', string()],
    currencyExponent: ['currency_exponent', optional(nullable(number()))],
    ledgerableId: ['ledgerable_id', optional(string())],
    ledgerableType: ['ledgerable_type', optional(ledgerableTypeEnumSchema)],
    metadata: ['metadata', optional(dict(string()))],
  }
);
