/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, nullable, object, optional, Schema, string } from '../schema.js';

export interface LedgerCreateRequest {
  /** The name of the ledger. */
  name: string;
  /** An optional free-form description for internal use. */
  description?: string | null;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
}

export const ledgerCreateRequestSchema: Schema<LedgerCreateRequest> = object({
  name: ['name', string()],
  description: ['description', optional(nullable(string()))],
  metadata: ['metadata', optional(dict(string()))],
});
