/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, nullable, object, optional, Schema, string } from '../schema.js';
import { Status8Enum, status8EnumSchema } from './status8Enum.js';

export interface LedgerAccountPayoutUpdateRequest {
  /** The description of the ledger account payout. */
  description?: string | null;
  /** To post a pending ledger account payout, use `posted`. To archive a pending ledger transaction, use `archived`. */
  status?: Status8Enum;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
}

export const ledgerAccountPayoutUpdateRequestSchema: Schema<LedgerAccountPayoutUpdateRequest> = object(
  {
    description: ['description', optional(nullable(string()))],
    status: ['status', optional(status8EnumSchema)],
    metadata: ['metadata', optional(dict(string()))],
  }
);
