/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface LedgerBalance {
  credits: number;
  debits: number;
  amount: number;
  /** The currency of the ledger account. */
  currency: string;
  /** The currency exponent of the ledger account. */
  currencyExponent: number;
}

export const ledgerBalanceSchema: Schema<LedgerBalance> = object({
  credits: ['credits', number()],
  debits: ['debits', number()],
  amount: ['amount', number()],
  currency: ['currency', string()],
  currencyExponent: ['currency_exponent', number()],
});
