/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface LedgerAccountStatementCreateRequest {
  /** The description of the ledger account statement. */
  description?: string | null;
  /** The id of the ledger account whose ledger entries are queried against, and its balances are computed as a result. */
  ledgerAccountId: string;
  /** The inclusive lower bound of the effective_at timestamp of the ledger entries to be included in the ledger account statement. */
  effectiveAtLowerBound: string;
  /** The exclusive upper bound of the effective_at timestamp of the ledger entries to be included in the ledger account statement. */
  effectiveAtUpperBound: string;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const ledgerAccountStatementCreateRequestSchema: Schema<LedgerAccountStatementCreateRequest> = typedExpandoObject(
  {
    description: ['description', optional(nullable(string()))],
    ledgerAccountId: ['ledger_account_id', string()],
    effectiveAtLowerBound: ['effective_at_lower_bound', string()],
    effectiveAtUpperBound: ['effective_at_upper_bound', string()],
    metadata: ['metadata', optional(dict(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
