/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface LedgerEventHandlerLedgerEntries {
  /** The field you're fetching from the `ledgerable_event`. */
  amount: string;
  /** What the operator between the `field` and `value` is. Currently only supports `equals`. */
  direction: string;
  /** What raw string you are comparing the `field` against. */
  ledgerAccountId: string;
}

export const ledgerEventHandlerLedgerEntriesSchema: Schema<LedgerEventHandlerLedgerEntries> = object(
  {
    amount: ['amount', string()],
    direction: ['direction', string()],
    ledgerAccountId: ['ledger_account_id', string()],
  }
);
