/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  LedgerEntryCreateRequest,
  ledgerEntryCreateRequestSchema,
} from './ledgerEntryCreateRequest.js';
import { Status12, status12Schema } from './status12.js';

export interface LedgerTransactionUpdateRequest {
  /** An optional description for internal use. */
  description?: string | null;
  /** To post a ledger transaction at creation, use `posted`. */
  status?: Status12;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  /** The timestamp (ISO8601 format) at which the ledger transaction happened for reporting purposes. */
  effectiveAt?: string;
  /** An array of ledger entry objects. */
  ledgerEntries?: LedgerEntryCreateRequest[];
  additionalProperties?: Record<string, unknown>;
}

export const ledgerTransactionUpdateRequestSchema: Schema<LedgerTransactionUpdateRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        description: ['description', optional(nullable(string()))],
        status: ['status', optional(status12Schema)],
        metadata: ['metadata', optional(dict(string()))],
        effectiveAt: ['effective_at', optional(string())],
        ledgerEntries: [
          'ledger_entries',
          optional(array(ledgerEntryCreateRequestSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
