/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for LedgerAccountNormalBalanceEnum
 */
export enum LedgerAccountNormalBalanceEnum {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for LedgerAccountNormalBalanceEnum
 */
export const ledgerAccountNormalBalanceEnumSchema: Schema<LedgerAccountNormalBalanceEnum> = stringEnum(
  LedgerAccountNormalBalanceEnum
);
