/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for LedgerableTypeEnum
 */
export enum LedgerableTypeEnum {
  ExternalAccount = 'external_account',
  InternalAccount = 'internal_account',
}

/**
 * Schema for LedgerableTypeEnum
 */
export const ledgerableTypeEnumSchema: Schema<LedgerableTypeEnum> = stringEnum(
  LedgerableTypeEnum
);
