/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  LedgerEventHandlerConditions,
  ledgerEventHandlerConditionsSchema,
} from './ledgerEventHandlerConditions.js';
import {
  LedgerEventHandlerLedgerTransactionTemplate,
  ledgerEventHandlerLedgerTransactionTemplateSchema,
} from './ledgerEventHandlerLedgerTransactionTemplate.js';

export interface LedgerEventHandlerCreateRequest {
  /** Name of the ledger event handler. */
  name: string;
  /** An optional description. */
  description?: string | null;
  /** The id of the ledger that this account belongs to. */
  ledgerId?: string;
  ledgerTransactionTemplate: LedgerEventHandlerLedgerTransactionTemplate;
  conditions?: LedgerEventHandlerConditions;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string> | null;
  additionalProperties?: Record<string, unknown>;
}

export const ledgerEventHandlerCreateRequestSchema: Schema<LedgerEventHandlerCreateRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        name: ['name', string()],
        description: ['description', optional(nullable(string()))],
        ledgerId: ['ledger_id', optional(string())],
        ledgerTransactionTemplate: [
          'ledger_transaction_template',
          ledgerEventHandlerLedgerTransactionTemplateSchema,
        ],
        conditions: [
          'conditions',
          optional(ledgerEventHandlerConditionsSchema),
        ],
        metadata: ['metadata', optional(nullable(dict(string())))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
