/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { LedgerableType5, ledgerableType5Schema } from './ledgerableType5.js';
import { Status15, status15Schema } from './status15.js';

export interface LedgerTransactionReversalCreateRequest {
  /** An optional free-form description for the reversal ledger transaction. Maximum of 1000 characters allowed. */
  description?: string;
  /** Status of the reversal ledger transaction. It defaults to `posted` if not provided. */
  status?: Status15;
  /** Additional data to be added to the reversal ledger transaction as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  /** The timestamp (ISO8601 format) at which the reversal ledger transaction happened for reporting purposes. It defaults to the `effective_at` of the original ledger transaction if not provided. */
  effectiveAt?: string | null;
  /** Must be unique within the ledger. */
  externalId?: string;
  /** Specify this if you'd like to link the reversal ledger transaction to a Payment object like Return or Reversal. */
  ledgerableType?: LedgerableType5;
  /** Specify this if you'd like to link the reversal ledger transaction to a Payment object like Return or Reversal. */
  ledgerableId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const ledgerTransactionReversalCreateRequestSchema: Schema<LedgerTransactionReversalCreateRequest> = typedExpandoObject(
  {
    description: ['description', optional(string())],
    status: ['status', optional(status15Schema)],
    metadata: ['metadata', optional(dict(string()))],
    effectiveAt: ['effective_at', optional(nullable(string()))],
    externalId: ['external_id', optional(string())],
    ledgerableType: ['ledgerable_type', optional(ledgerableType5Schema)],
    ledgerableId: ['ledgerable_id', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
