/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Status7, status7Schema } from './status7.js';

export interface LedgerAccountPayoutCreateRequest {
  /** The description of the ledger account payout. */
  description?: string | null;
  /** The status of the ledger account payout. It is set to `pending` by default. To post a ledger account payout at creation, use `posted`. */
  status?: Status7 | null;
  /** The id of the payout ledger account whose ledger entries are queried against, and its balance is reduced as a result. */
  payoutLedgerAccountId: string;
  /** The id of the funding ledger account that sends to or receives funds from the payout ledger account. */
  fundingLedgerAccountId: string;
  /** The exclusive upper bound of the effective_at timestamp of the ledger entries to be included in the ledger account payout. The default value is the created_at timestamp of the ledger account payout. */
  effectiveAtUpperBound?: string | null;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  /** It is set to `false` by default. It should be set to `true` when migrating existing payouts. */
  skipPayoutLedgerTransaction?: boolean | null;
  additionalProperties?: Record<string, unknown>;
}

export const ledgerAccountPayoutCreateRequestSchema: Schema<LedgerAccountPayoutCreateRequest> = typedExpandoObject(
  {
    description: ['description', optional(nullable(string()))],
    status: ['status', optional(nullable(status7Schema))],
    payoutLedgerAccountId: ['payout_ledger_account_id', string()],
    fundingLedgerAccountId: ['funding_ledger_account_id', string()],
    effectiveAtUpperBound: [
      'effective_at_upper_bound',
      optional(nullable(string())),
    ],
    metadata: ['metadata', optional(dict(string()))],
    skipPayoutLedgerTransaction: [
      'skip_payout_ledger_transaction',
      optional(nullable(boolean())),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
