/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { LedgerableType2, ledgerableType2Schema } from './ledgerableType2.js';
import {
  LedgerEntryCreateRequest,
  ledgerEntryCreateRequestSchema,
} from './ledgerEntryCreateRequest.js';
import { Status12, status12Schema } from './status12.js';

export interface LedgerTransactionCreateRequest {
  /** An optional description for internal use. */
  description?: string | null;
  /** To post a ledger transaction at creation, use `posted`. */
  status?: Status12;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  /** The timestamp (ISO8601 format) at which the ledger transaction happened for reporting purposes. */
  effectiveAt?: string;
  /** The date (YYYY-MM-DD) on which the ledger transaction happened for reporting purposes. */
  effectiveDate?: string;
  /** An array of ledger entry objects. */
  ledgerEntries: LedgerEntryCreateRequest[];
  /** A unique string to represent the ledger transaction. Only one pending or posted ledger transaction may have this ID in the ledger. */
  externalId?: string;
  /** If the ledger transaction can be reconciled to another object in Modern Treasury, the type will be populated here, otherwise null. This can be one of payment_order, incoming_payment_detail, expected_payment, return, or reversal. */
  ledgerableType?: LedgerableType2;
  /** If the ledger transaction can be reconciled to another object in Modern Treasury, the id will be populated here, otherwise null. */
  ledgerableId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const ledgerTransactionCreateRequestSchema: Schema<LedgerTransactionCreateRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        description: ['description', optional(nullable(string()))],
        status: ['status', optional(status12Schema)],
        metadata: ['metadata', optional(dict(string()))],
        effectiveAt: ['effective_at', optional(string())],
        effectiveDate: ['effective_date', optional(string())],
        ledgerEntries: [
          'ledger_entries',
          array(ledgerEntryCreateRequestSchema),
        ],
        externalId: ['external_id', optional(string())],
        ledgerableType: ['ledgerable_type', optional(ledgerableType2Schema)],
        ledgerableId: ['ledgerable_id', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
