/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  lazy,
  nullable,
  object,
  Schema,
  string,
} from '../schema.js';
import {
  LedgerEventHandlerConditions,
  ledgerEventHandlerConditionsSchema,
} from './ledgerEventHandlerConditions.js';
import {
  LedgerEventHandlerLedgerTransactionTemplate,
  ledgerEventHandlerLedgerTransactionTemplateSchema,
} from './ledgerEventHandlerLedgerTransactionTemplate.js';

export interface LedgerEventHandler {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  /** Name of the ledger event handler. */
  name: string;
  /** An optional description. */
  description: string | null;
  ledgerTransactionTemplate: LedgerEventHandlerLedgerTransactionTemplate;
  conditions: LedgerEventHandlerConditions;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string> | null;
}

export const ledgerEventHandlerSchema: Schema<LedgerEventHandler> = lazy(() =>
  object({
    id: ['id', string()],
    object: ['object', string()],
    liveMode: ['live_mode', boolean()],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    discardedAt: ['discarded_at', nullable(string())],
    name: ['name', string()],
    description: ['description', nullable(string())],
    ledgerTransactionTemplate: [
      'ledger_transaction_template',
      ledgerEventHandlerLedgerTransactionTemplateSchema,
    ],
    conditions: ['conditions', ledgerEventHandlerConditionsSchema],
    metadata: ['metadata', nullable(dict(string()))],
  })
);
