/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, nullable, object, optional, Schema, string } from '../schema.js';

export interface LedgerAccountCategoryUpdateRequest {
  /** The name of the ledger account category. */
  name?: string;
  /** The description of the ledger account category. */
  description?: string | null;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
}

export const ledgerAccountCategoryUpdateRequestSchema: Schema<LedgerAccountCategoryUpdateRequest> = object(
  {
    name: ['name', optional(string())],
    description: ['description', optional(nullable(string()))],
    metadata: ['metadata', optional(dict(string()))],
  }
);
