/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  nullable,
  object,
  Schema,
  string,
} from '../schema.js';
import {
  LedgerEventHandlerLedgerEntries,
  ledgerEventHandlerLedgerEntriesSchema,
} from './ledgerEventHandlerLedgerEntries.js';

export interface LedgerEventHandlerLedgerTransactionTemplate {
  /** An optional description for internal use. */
  description: string | null;
  /** The timestamp (ISO8601 format) at which the ledger transaction happened for reporting purposes. */
  effectiveAt: string | null;
  /** An array of ledger entry objects. */
  ledgerEntries: LedgerEventHandlerLedgerEntries[];
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string> | null;
}

export const ledgerEventHandlerLedgerTransactionTemplateSchema: Schema<LedgerEventHandlerLedgerTransactionTemplate> = lazy(
  () =>
    object({
      description: ['description', nullable(string())],
      effectiveAt: ['effective_at', nullable(string())],
      ledgerEntries: [
        'ledger_entries',
        array(ledgerEventHandlerLedgerEntriesSchema),
      ],
      metadata: ['metadata', nullable(dict(string()))],
    })
);
