/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface LedgerEventHandlerConditions {
  /** The field you're fetching from the `ledgerable_event`. */
  field: string;
  /** What the operator between the `field` and `value` is. Currently only supports `equals`. */
  operator: string;
  /** What raw string you are comparing the `field` against. */
  value: string;
}

export const ledgerEventHandlerConditionsSchema: Schema<LedgerEventHandlerConditions> = object(
  {
    field: ['field', string()],
    operator: ['operator', string()],
    value: ['value', string()],
  }
);
