/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  lazy,
  nullable,
  object,
  Schema,
  string,
} from '../schema.js';
import { LedgerBalances, ledgerBalancesSchema } from './ledgerBalances.js';
import { NormalBalance2, normalBalance2Schema } from './normalBalance2.js';

export interface LedgerAccountCategory {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  /** The name of the ledger account category. */
  name: string;
  /** The description of the ledger account category. */
  description: string | null;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string>;
  /** The id of the ledger that this account category belongs to. */
  ledgerId: string;
  /** The normal balance of the ledger account category. */
  normalBalance: NormalBalance2;
  balances: LedgerBalances;
}

export const ledgerAccountCategorySchema: Schema<LedgerAccountCategory> = lazy(
  () =>
    object({
      id: ['id', string()],
      object: ['object', string()],
      liveMode: ['live_mode', boolean()],
      createdAt: ['created_at', string()],
      updatedAt: ['updated_at', string()],
      discardedAt: ['discarded_at', nullable(string())],
      name: ['name', string()],
      description: ['description', nullable(string())],
      metadata: ['metadata', dict(string())],
      ledgerId: ['ledger_id', string()],
      normalBalance: ['normal_balance', normalBalance2Schema],
      balances: ['balances', ledgerBalancesSchema],
    })
);
