/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface LegacyDocumentCreateRequest {
  /** A category given to the document, can be `null`. */
  documentType?: string;
  file: string;
}

export const legacyDocumentCreateRequestSchema: Schema<LegacyDocumentCreateRequest> = object(
  {
    documentType: ['document_type', optional(string())],
    file: ['file', string()],
  }
);
