/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface LegacyDocumentCreateRequest {
  /** A category given to the document, can be `null`. */
  documentType?: string;
  file: string;
  additionalProperties?: Record<string, unknown>;
}

export const legacyDocumentCreateRequestSchema: Schema<LegacyDocumentCreateRequest> = typedExpandoObject(
  {
    documentType: ['document_type', optional(string())],
    file: ['file', string()],
  },
  'additionalProperties',
  optional(unknown())
);
