/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  lazy,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import { Accounting, accountingSchema } from './accounting.js';
import {
  ItemizableTypeEnum,
  itemizableTypeEnumSchema,
} from './itemizableTypeEnum.js';

export interface LineItem {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  /** The ID of the payment order or expected payment. */
  itemizableId: string;
  /** One of `payment_orders` or `expected_payments`. */
  itemizableType: ItemizableTypeEnum;
  /** Value in specified currency's smallest unit. e.g. $10 would be represented as 1000. */
  amount: number;
  /** A free-form description of the line item. */
  description: string | null;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string>;
  accounting: Accounting;
  /** The ID of one of your accounting categories. Note that these will only be accessible if your accounting system has been connected. */
  accountingCategoryId: string | null;
  /** The ID of one of the class objects in your accounting system. Class objects track segments of your business independent of client or project. Note that these will only be accessible if your accounting system has been connected. */
  accountingLedgerClassId: string | null;
}

export const lineItemSchema: Schema<LineItem> = lazy(() =>
  object({
    id: ['id', string()],
    object: ['object', string()],
    liveMode: ['live_mode', boolean()],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    itemizableId: ['itemizable_id', string()],
    itemizableType: ['itemizable_type', itemizableTypeEnumSchema],
    amount: ['amount', number()],
    description: ['description', nullable(string())],
    metadata: ['metadata', dict(string())],
    accounting: ['accounting', accountingSchema],
    accountingCategoryId: ['accounting_category_id', nullable(string())],
    accountingLedgerClassId: ['accounting_ledger_class_id', nullable(string())],
  })
);
