/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface LineItemUpdateRequest {
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const lineItemUpdateRequestSchema: Schema<LineItemUpdateRequest> = typedExpandoObject(
  { metadata: ['metadata', optional(dict(string()))] },
  'additionalProperties',
  optional(unknown())
);
