/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for NormalBalance2
 */
export enum NormalBalance2 {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for NormalBalance2
 */
export const normalBalance2Schema: Schema<NormalBalance2> = stringEnum(
  NormalBalance2
);
