/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for NormalBalance
 */
export enum NormalBalance {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for NormalBalance
 */
export const normalBalanceSchema: Schema<NormalBalance> = stringEnum(
  NormalBalance
);
