/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for NormalBalance2Enum
 */
export enum NormalBalance2Enum {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for NormalBalance2Enum
 */
export const normalBalance2EnumSchema: Schema<NormalBalance2Enum> = stringEnum(
  NormalBalance2Enum
);
