/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import { CreatedAtEnum, createdAtEnumSchema } from './createdAtEnum.js';
import { EffectiveAtEnum, effectiveAtEnumSchema } from './effectiveAtEnum.js';

export interface OrderBy {
  createdAt?: CreatedAtEnum;
  effectiveAt?: EffectiveAtEnum;
}

export const orderBySchema: Schema<OrderBy> = object({
  createdAt: ['created_at', optional(createdAtEnumSchema)],
  effectiveAt: ['effective_at', optional(effectiveAtEnumSchema)],
});
