/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import { CreatedAt, createdAtSchema } from './createdAt.js';
import { EffectiveAt, effectiveAtSchema } from './effectiveAt.js';

export interface OrderBy {
  createdAt?: CreatedAt;
  effectiveAt?: EffectiveAt;
}

export const orderBySchema: Schema<OrderBy> = object({
  createdAt: ['created_at', optional(createdAtSchema)],
  effectiveAt: ['effective_at', optional(effectiveAtSchema)],
});
