/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OriginatingAccountNumberTypeEnum
 */
export enum OriginatingAccountNumberTypeEnum {
  Clabe = 'clabe',
  Iban = 'iban',
  Other = 'other',
  Pan = 'pan',
  WalletAddress = 'wallet_address',
}

/**
 * Schema for OriginatingAccountNumberTypeEnum
 */
export const originatingAccountNumberTypeEnumSchema: Schema<OriginatingAccountNumberTypeEnum> = stringEnum(
  OriginatingAccountNumberTypeEnum
);
