/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OriginatingAccountNumberType
 */
export enum OriginatingAccountNumberType {
  Clabe = 'clabe',
  Iban = 'iban',
  Other = 'other',
  Pan = 'pan',
  WalletAddress = 'wallet_address',
}

/**
 * Schema for OriginatingAccountNumberType
 */
export const originatingAccountNumberTypeSchema: Schema<OriginatingAccountNumberType> = stringEnum(
  OriginatingAccountNumberType
);
