/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import { CurrencyEnum, currencyEnumSchema } from './currencyEnum.js';
import { Status16Enum, status16EnumSchema } from './status16Enum.js';

export interface PaperItem {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  /** The ID of the reconciled Transaction Line Item or `null`. */
  transactionLineItemId: string | null;
  /** The ID of the reconciled Transaction or `null`. */
  transactionId: string | null;
  /** The current status of the paper item. One of `pending`, `completed`, or `returned`. */
  status: Status16Enum;
  /** The identifier for the lockbox assigned by the bank. */
  lockboxNumber: string;
  /** The date the paper item was deposited into your organization's bank account. */
  depositDate: string;
  /** The amount of the paper item. */
  amount: number;
  /** Three-letter ISO currency code. */
  currency: CurrencyEnum;
  /** The account number on the paper item. */
  accountNumber: string | null;
  /** The last 4 digits of the account_number. */
  accountNumberSafe: string | null;
  /** The routing number on the paper item. */
  routingNumber: string | null;
  /** The check number on the paper item. */
  checkNumber: string | null;
  /** The name of the remitter on the paper item. */
  remitterName: string | null;
  /** The memo field on the paper item. */
  memoField: string | null;
}

export const paperItemSchema: Schema<PaperItem> = object({
  id: ['id', string()],
  object: ['object', string()],
  liveMode: ['live_mode', boolean()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  transactionLineItemId: ['transaction_line_item_id', nullable(string())],
  transactionId: ['transaction_id', nullable(string())],
  status: ['status', status16EnumSchema],
  lockboxNumber: ['lockbox_number', string()],
  depositDate: ['deposit_date', string()],
  amount: ['amount', number()],
  currency: ['currency', currencyEnumSchema],
  accountNumber: ['account_number', nullable(string())],
  accountNumberSafe: ['account_number_safe', nullable(string())],
  routingNumber: ['routing_number', nullable(string())],
  checkNumber: ['check_number', nullable(string())],
  remitterName: ['remitter_name', nullable(string())],
  memoField: ['memo_field', nullable(string())],
});
