/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PartyType5
 */
export enum PartyType5 {
  Business = 'business',
  Individual = 'individual',
}

/**
 * Schema for PartyType5
 */
export const partyType5Schema: Schema<PartyType5> = stringEnum(PartyType5);
