/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PartyTypeEnum
 */
export enum PartyTypeEnum {
  Business = 'business',
  Individual = 'individual',
}

/**
 * Schema for PartyTypeEnum
 */
export const partyTypeEnumSchema: Schema<PartyTypeEnum> = stringEnum(
  PartyTypeEnum
);
