/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PartyType
 */
export enum PartyType {
  Business = 'business',
  Individual = 'individual',
}

/**
 * Schema for PartyType
 */
export const partyTypeSchema: Schema<PartyType> = stringEnum(PartyType);
