/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** The address associated with the owner or null. */
export interface PartyAddress {
  line1: string;
  line2?: string;
  /** Locality or City. */
  locality: string;
  /** Region or State. */
  region: string;
  /** The postal code of the address. */
  postalCode: string;
  /** Country code conforms to [ISO 3166-1 alpha-2] */
  country: string;
  additionalProperties?: Record<string, unknown>;
}

export const partyAddressSchema: Schema<PartyAddress> = typedExpandoObject(
  {
    line1: ['line1', string()],
    line2: ['line2', optional(string())],
    locality: ['locality', string()],
    region: ['region', string()],
    postalCode: ['postal_code', string()],
    country: ['country', string()],
  },
  'additionalProperties',
  optional(unknown())
);
