/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PartyType5Enum
 */
export enum PartyType5Enum {
  Business = 'business',
  Individual = 'individual',
}

/**
 * Schema for PartyType5Enum
 */
export const partyType5EnumSchema: Schema<PartyType5Enum> = stringEnum(
  PartyType5Enum
);
