/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentType2
 */
export enum PaymentType2 {
  Ach = 'ach',
  AuBecs = 'au_becs',
  Bacs = 'bacs',
  Book = 'book',
  Card = 'card',
  Check = 'check',
  Eft = 'eft',
  CrossBorder = 'cross_border',
  Interac = 'interac',
  Masav = 'masav',
  Neft = 'neft',
  Provxchange = 'provxchange',
  Rtp = 'rtp',
  Sen = 'sen',
  Sepa = 'sepa',
  Signet = 'signet',
  Wire = 'wire',
}

/**
 * Schema for PaymentType2
 */
export const paymentType2Schema: Schema<PaymentType2> = stringEnum(
  PaymentType2
);
