/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentMethod
 */
export enum PaymentMethod {
  Ui = 'ui',
  Manual = 'manual',
  Automatic = 'automatic',
}

/**
 * Schema for PaymentMethod
 */
export const paymentMethodSchema: Schema<PaymentMethod> = stringEnum(
  PaymentMethod
);
