/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Direction10, direction10Schema } from './direction10.js';

export interface PaymentFlowCreateRequest {
  /** Required. Value in specified currency's smallest unit. e.g. $10 would be represented as 1000. Can be any integer up to 36 digits. */
  amount: number;
  /** Required. The currency of the payment. */
  currency: string;
  /** Required. Describes the direction money is flowing in the transaction. Can only be `debit`. A `debit` pulls money from someone else's account to your own. */
  direction: Direction10;
  /** Required. The ID of a counterparty associated with the payment. As part of the payment workflow an external account will be associated with this model. */
  counterpartyId: string;
  /** Required. The ID of one of your organization's internal accounts. */
  originatingAccountId: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentFlowCreateRequestSchema: Schema<PaymentFlowCreateRequest> = typedExpandoObject(
  {
    amount: ['amount', number()],
    currency: ['currency', string()],
    direction: ['direction', direction10Schema],
    counterpartyId: ['counterparty_id', string()],
    originatingAccountId: ['originating_account_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
