/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentType5
 */
export enum PaymentType5 {
  Eft = 'eft',
  Ach = 'ach',
}

/**
 * Schema for PaymentType5
 */
export const paymentType5Schema: Schema<PaymentType5> = stringEnum(
  PaymentType5
);
