/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentMethod1Enum
 */
export enum PaymentMethod1Enum {
  Ui = 'ui',
  Manual = 'manual',
  Automatic = 'automatic',
}

/**
 * Schema for PaymentMethod1Enum
 */
export const paymentMethod1EnumSchema: Schema<PaymentMethod1Enum> = stringEnum(
  PaymentMethod1Enum
);
