/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface PaymentFlowUpdateRequest {
  /** Required. The updated status of the payment flow. Can only be used to mark a flow as `cancelled`. */
  status: string;
}

export const paymentFlowUpdateRequestSchema: Schema<PaymentFlowUpdateRequest> = object(
  { status: ['status', string()] }
);
