/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentDirectionEnum
 */
export enum PaymentDirectionEnum {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for PaymentDirectionEnum
 */
export const paymentDirectionEnumSchema: Schema<PaymentDirectionEnum> = stringEnum(
  PaymentDirectionEnum
);
