/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentMethod1
 */
export enum PaymentMethod1 {
  Ui = 'ui',
  Manual = 'manual',
  Automatic = 'automatic',
}

/**
 * Schema for PaymentMethod1
 */
export const paymentMethod1Schema: Schema<PaymentMethod1> = stringEnum(
  PaymentMethod1
);
