/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentType5Enum
 */
export enum PaymentType5Enum {
  Eft = 'eft',
  Ach = 'ach',
}

/**
 * Schema for PaymentType5Enum
 */
export const paymentType5EnumSchema: Schema<PaymentType5Enum> = stringEnum(
  PaymentType5Enum
);
