/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PaymentFlowUpdateRequest {
  /** Required. The updated status of the payment flow. Can only be used to mark a flow as `cancelled`. */
  status: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentFlowUpdateRequestSchema: Schema<PaymentFlowUpdateRequest> = typedExpandoObject(
  { status: ['status', string()] },
  'additionalProperties',
  optional(unknown())
);
