/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentType
 */
export enum PaymentType {
  Ach = 'ach',
  Wire = 'wire',
}

/**
 * Schema for PaymentType
 */
export const paymentTypeSchema: Schema<PaymentType> = stringEnum(PaymentType);
