/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Accounting, accountingSchema } from './accounting.js';
import { ChargeBearer, chargeBearerSchema } from './chargeBearer.js';
import { Currency, currencySchema } from './currency.js';
import { Direction5, direction5Schema } from './direction5.js';
import { FallbackType, fallbackTypeSchema } from './fallbackType.js';
import {
  ForeignExchangeIndicator,
  foreignExchangeIndicatorSchema,
} from './foreignExchangeIndicator.js';
import {
  LedgerTransactionCreateRequest,
  ledgerTransactionCreateRequestSchema,
} from './ledgerTransactionCreateRequest.js';
import { LineItemRequest, lineItemRequestSchema } from './lineItemRequest.js';
import { Priority, prioritySchema } from './priority.js';
import {
  ReceivingAccount1,
  receivingAccount1Schema,
} from './receivingAccount1.js';
import { Subtype, subtypeSchema } from './subtype.js';
import { Type5, type5Schema } from './type5.js';

export interface PaymentOrderAsyncCreateRequest {
  /** One of `ach`, `eft`, `wire`, `check`, `sen`, `book`, `rtp`, `sepa`, `bacs`, `au_becs`, `interac`, `signet`, `provexchange`. */
  type: Type5;
  /** An additional layer of classification for the type of payment order you are doing. This field is only used for `ach` payment orders currently. For `ach`  payment orders, the `subtype`  represents the SEC code. We currently support `CCD`, `PPD`, `IAT`, `CTX`, `WEB`, `CIE`, and `TEL`. */
  subtype?: Subtype | null;
  /** Value in specified currency's smallest unit. e.g. $10 would be represented as 1000 (cents). For RTP, the maximum amount allowed by the network is $100,000. */
  amount: number;
  /** One of `credit`, `debit`. Describes the direction money is flowing in the transaction. A `credit` moves money from your account to someone else's. A `debit` pulls money from someone else's account to your own. Note that wire, rtp, and check payments will always be `credit`. */
  direction: Direction5;
  /** Either `normal` or `high`. For ACH and EFT payments, `high` represents a same-day ACH or EFT transfer, respectively. For check payments, `high` can mean an overnight check rather than standard mail. */
  priority?: Priority;
  /** The ID of one of your organization's internal accounts. */
  originatingAccountId: string;
  /** Either `receiving_account` or `receiving_account_id` must be present. When using `receiving_account_id`, you may pass the id of an external account or an internal account. */
  receivingAccountId?: string;
  accounting?: Accounting;
  /** The ID of one of your accounting categories. Note that these will only be accessible if your accounting system has been connected. */
  accountingCategoryId?: string | null;
  /** The ID of one of your accounting ledger classes. Note that these will only be accessible if your accounting system has been connected. */
  accountingLedgerClassId?: string | null;
  /** Three-letter ISO currency code. */
  currency?: Currency;
  /** Date transactions are to be posted to the participants' account. Defaults to the current business day or the next business day if the current day is a bank holiday or weekend. Format: yyyy-mm-dd. */
  effectiveDate?: string;
  /** An optional description for internal use. */
  description?: string | null;
  /** An optional descriptor which will appear in the receiver's statement. For `check` payments this field will be used as the memo line. For `ach` the maximum length is 10 characters. Note that for ACH payments, the name on your bank account will be included automatically by the bank, so you can use the characters for other useful information. For `eft` the maximum length is 15 characters. */
  statementDescriptor?: string | null;
  /** For `ach`, this field will be passed through on an addenda record. For `wire` payments the field will be passed through as the "Originator to Beneficiary Information", also known as OBI or Fedwire tag 6000. */
  remittanceInformation?: string | null;
  /** For `wire`, this is usually the purpose which is transmitted via the "InstrForDbtrAgt" field in the ISO20022 file. If you are using Currencycloud, this is the `payment.purpose_code` field. For `eft`, this field is the 3 digit CPA Code that will be attached to the payment. */
  purpose?: string | null;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  /** The party that will pay the fees for the payment order. Only applies to wire payment orders. Can be one of shared, sender, or receiver, which correspond respectively with the SWIFT 71A values `SHA`, `OUR`, `BEN`. */
  chargeBearer?: ChargeBearer | null;
  /** Indicates the type of FX transfer to initiate, can be either `variable_to_fixed`, `fixed_to_variable`, or `null` if the payment order currency matches the originating account currency. */
  foreignExchangeIndicator?: ForeignExchangeIndicator | null;
  /** If present, indicates a specific foreign exchange contract number that has been generated by your financial institution. */
  foreignExchangeContract?: string | null;
  /** A boolean to determine if NSF Protection is enabled for this payment order. Note that this setting must also be turned on in your organization settings page. */
  nsfProtected?: boolean;
  /** If present, this will replace your default company name on receiver's bank statement. This field can only be used for ACH payments currently. For ACH, only the first 16 characters of this string will be used. Any additional characters will be truncated. */
  originatingPartyName?: string | null;
  /** Name of the ultimate originator of the payment order. */
  ultimateOriginatingPartyName?: string | null;
  /** Identifier of the ultimate originator of the payment order. */
  ultimateOriginatingPartyIdentifier?: string | null;
  /** Name of the ultimate funds recipient. */
  ultimateReceivingPartyName?: string | null;
  /** Identifier of the ultimate funds recipient. */
  ultimateReceivingPartyIdentifier?: string | null;
  /** Send an email to the counterparty when the payment order is sent to the bank. If `null`, `send_remittance_advice` on the Counterparty is used. */
  sendRemittanceAdvice?: boolean | null;
  /** RFP payments require an expires_at. This value must be past the effective_date. */
  expiresAt?: string | null;
  /** A payment type to fallback to if the original type is not valid for the receiving account. Currently, this only supports falling back from RTP to ACH (type=rtp and fallback_type=ach) */
  fallbackType?: FallbackType;
  /** Either `receiving_account` or `receiving_account_id` must be present. When using `receiving_account_id`, you may pass the id of an external account or an internal account. */
  receivingAccount?: ReceivingAccount1;
  ledgerTransaction?: LedgerTransactionCreateRequest;
  /** An array of line items that must sum up to the amount of the payment order. */
  lineItems?: LineItemRequest[];
  /** A flag that determines whether a payment order should go through transaction monitoring. */
  transactionMonitoringEnabled?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const paymentOrderAsyncCreateRequestSchema: Schema<PaymentOrderAsyncCreateRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        type: ['type', type5Schema],
        subtype: ['subtype', optional(nullable(subtypeSchema))],
        amount: ['amount', number()],
        direction: ['direction', direction5Schema],
        priority: ['priority', optional(prioritySchema)],
        originatingAccountId: ['originating_account_id', string()],
        receivingAccountId: ['receiving_account_id', optional(string())],
        accounting: ['accounting', optional(accountingSchema)],
        accountingCategoryId: [
          'accounting_category_id',
          optional(nullable(string())),
        ],
        accountingLedgerClassId: [
          'accounting_ledger_class_id',
          optional(nullable(string())),
        ],
        currency: ['currency', optional(currencySchema)],
        effectiveDate: ['effective_date', optional(string())],
        description: ['description', optional(nullable(string()))],
        statementDescriptor: [
          'statement_descriptor',
          optional(nullable(string())),
        ],
        remittanceInformation: [
          'remittance_information',
          optional(nullable(string())),
        ],
        purpose: ['purpose', optional(nullable(string()))],
        metadata: ['metadata', optional(dict(string()))],
        chargeBearer: ['charge_bearer', optional(nullable(chargeBearerSchema))],
        foreignExchangeIndicator: [
          'foreign_exchange_indicator',
          optional(nullable(foreignExchangeIndicatorSchema)),
        ],
        foreignExchangeContract: [
          'foreign_exchange_contract',
          optional(nullable(string())),
        ],
        nsfProtected: ['nsf_protected', optional(boolean())],
        originatingPartyName: [
          'originating_party_name',
          optional(nullable(string())),
        ],
        ultimateOriginatingPartyName: [
          'ultimate_originating_party_name',
          optional(nullable(string())),
        ],
        ultimateOriginatingPartyIdentifier: [
          'ultimate_originating_party_identifier',
          optional(nullable(string())),
        ],
        ultimateReceivingPartyName: [
          'ultimate_receiving_party_name',
          optional(nullable(string())),
        ],
        ultimateReceivingPartyIdentifier: [
          'ultimate_receiving_party_identifier',
          optional(nullable(string())),
        ],
        sendRemittanceAdvice: [
          'send_remittance_advice',
          optional(nullable(boolean())),
        ],
        expiresAt: ['expires_at', optional(nullable(string()))],
        fallbackType: ['fallback_type', optional(fallbackTypeSchema)],
        receivingAccount: [
          'receiving_account',
          optional(receivingAccount1Schema),
        ],
        ledgerTransaction: [
          'ledger_transaction',
          optional(ledgerTransactionCreateRequestSchema),
        ],
        lineItems: ['line_items', optional(array(lineItemRequestSchema))],
        transactionMonitoringEnabled: [
          'transaction_monitoring_enabled',
          optional(boolean()),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
