/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentMethodEnum
 */
export enum PaymentMethodEnum {
  Ui = 'ui',
  Manual = 'manual',
  Automatic = 'automatic',
}

/**
 * Schema for PaymentMethodEnum
 */
export const paymentMethodEnumSchema: Schema<PaymentMethodEnum> = stringEnum(
  PaymentMethodEnum
);
