/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentType4Enum
 */
export enum PaymentType4Enum {
  Ach = 'ach',
  AuBecs = 'au_becs',
  Bacs = 'bacs',
  Book = 'book',
  Card = 'card',
  Check = 'check',
  CrossBorder = 'cross_border',
  Eft = 'eft',
  Interac = 'interac',
  Masav = 'masav',
  Neft = 'neft',
  Provxchange = 'provxchange',
  Rtp = 'rtp',
  Sen = 'sen',
  Sepa = 'sepa',
  Signet = 'signet',
  Wire = 'wire',
}

/**
 * Schema for PaymentType4Enum
 */
export const paymentType4EnumSchema: Schema<PaymentType4Enum> = stringEnum(
  PaymentType4Enum
);
