/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema.js';
import {
  ReferenceableTypeEnum,
  referenceableTypeEnumSchema,
} from './referenceableTypeEnum.js';
import {
  ReferenceNumberType1Enum,
  referenceNumberType1EnumSchema,
} from './referenceNumberType1Enum.js';

export interface PaymentReferenceObject {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  /** The id of the referenceable to search for. Must be accompanied by the referenceable_type or will return an error. */
  referenceableId: string;
  /** One of the referenceable types. This must be accompanied by the id of the referenceable or will return an error. */
  referenceableType: ReferenceableTypeEnum;
  /** The actual reference number assigned by the bank. */
  referenceNumber: string;
  /** The type of reference number. */
  referenceNumberType: ReferenceNumberType1Enum;
}

export const paymentReferenceObjectSchema: Schema<PaymentReferenceObject> = object(
  {
    id: ['id', string()],
    object: ['object', string()],
    liveMode: ['live_mode', boolean()],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    referenceableId: ['referenceable_id', string()],
    referenceableType: ['referenceable_type', referenceableTypeEnumSchema],
    referenceNumber: ['reference_number', string()],
    referenceNumberType: [
      'reference_number_type',
      referenceNumberType1EnumSchema,
    ],
  }
);
