/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentDirection
 */
export enum PaymentDirection {
  Credit = 'credit',
  Debit = 'debit',
}

/**
 * Schema for PaymentDirection
 */
export const paymentDirectionSchema: Schema<PaymentDirection> = stringEnum(
  PaymentDirection
);
