/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface PingResponse {
  ping: string;
}

export const pingResponseSchema: Schema<PingResponse> = object({
  ping: ['ping', string()],
});
