/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Priority4
 */
export enum Priority4 {
  High = 'high',
  Normal = 'normal',
}

/**
 * Schema for Priority4
 */
export const priority4Schema: Schema<Priority4> = stringEnum(Priority4);
