/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PriorityEnum
 */
export enum PriorityEnum {
  High = 'high',
  Normal = 'normal',
}

/**
 * Schema for PriorityEnum
 */
export const priorityEnumSchema: Schema<PriorityEnum> = stringEnum(
  PriorityEnum
);
