/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Priority
 */
export enum Priority {
  High = 'high',
  Normal = 'normal',
}

/**
 * Schema for Priority
 */
export const prioritySchema: Schema<Priority> = stringEnum(Priority);
