/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReasonEnum
 */
export enum ReasonEnum {
  Duplicate = 'duplicate',
  IncorrectAmount = 'incorrect_amount',
  IncorrectReceivingAccount = 'incorrect_receiving_account',
  DateEarlierThanIntended = 'date_earlier_than_intended',
  DateLaterThanIntended = 'date_later_than_intended',
}

/**
 * Schema for ReasonEnum
 */
export const reasonEnumSchema: Schema<ReasonEnum> = stringEnum(ReasonEnum);
