/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReceivingAccountTypeEnum
 */
export enum ReceivingAccountTypeEnum {
  InternalAccount = 'internal_account',
  ExternalAccount = 'external_account',
}

/**
 * Schema for ReceivingAccountTypeEnum
 */
export const receivingAccountTypeEnumSchema: Schema<ReceivingAccountTypeEnum> = stringEnum(
  ReceivingAccountTypeEnum
);
