/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { AccountDetail, accountDetailSchema } from './accountDetail.js';
import { AccountTypeEnum, accountTypeEnumSchema } from './accountTypeEnum.js';
import { Address, addressSchema } from './address.js';
import { ContactDetail, contactDetailSchema } from './contactDetail.js';
import { PartyTypeEnum, partyTypeEnumSchema } from './partyTypeEnum.js';
import { RoutingDetail, routingDetailSchema } from './routingDetail.js';
import {
  VerificationStatusEnum,
  verificationStatusEnumSchema,
} from './verificationStatusEnum.js';

export interface ReceivingAccount {
  id?: string;
  object?: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode?: boolean;
  createdAt?: string;
  updatedAt?: string;
  discardedAt?: string | null;
  /** Can be `checking`, `savings` or `other`. */
  accountType?: AccountTypeEnum;
  /** Either `individual` or `business`. */
  partyType?: PartyTypeEnum | null;
  partyAddress?: Address | null;
  /** A nickname for the external account. This is only for internal usage and won't affect any payments */
  name?: string | null;
  accountDetails?: AccountDetail[];
  routingDetails?: RoutingDetail[];
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  /** The legal name of the entity which owns the account. */
  partyName?: string;
  contactDetails?: ContactDetail[];
  /** If the external account links to a ledger account in Modern Treasury, the id of the ledger account will be populated here. */
  ledgerAccountId?: string | null;
  verificationStatus?: VerificationStatusEnum;
}

export const receivingAccountSchema: Schema<ReceivingAccount> = lazy(() =>
  object({
    id: ['id', optional(string())],
    object: ['object', optional(string())],
    liveMode: ['live_mode', optional(boolean())],
    createdAt: ['created_at', optional(string())],
    updatedAt: ['updated_at', optional(string())],
    discardedAt: ['discarded_at', optional(nullable(string()))],
    accountType: ['account_type', optional(accountTypeEnumSchema)],
    partyType: ['party_type', optional(nullable(partyTypeEnumSchema))],
    partyAddress: ['party_address', optional(nullable(addressSchema))],
    name: ['name', optional(nullable(string()))],
    accountDetails: ['account_details', optional(array(accountDetailSchema))],
    routingDetails: ['routing_details', optional(array(routingDetailSchema))],
    metadata: ['metadata', optional(dict(string()))],
    partyName: ['party_name', optional(string())],
    contactDetails: ['contact_details', optional(array(contactDetailSchema))],
    ledgerAccountId: ['ledger_account_id', optional(nullable(string()))],
    verificationStatus: [
      'verification_status',
      optional(verificationStatusEnumSchema),
    ],
  })
);
