/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReceivingAccountType
 */
export enum ReceivingAccountType {
  InternalAccount = 'internal_account',
  ExternalAccount = 'external_account',
}

/**
 * Schema for ReceivingAccountType
 */
export const receivingAccountTypeSchema: Schema<ReceivingAccountType> = stringEnum(
  ReceivingAccountType
);
