/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReconciliationMethod
 */
export enum ReconciliationMethod {
  Automatic = 'automatic',
  Manual = 'manual',
}

/**
 * Schema for ReconciliationMethod
 */
export const reconciliationMethodSchema: Schema<ReconciliationMethod> = stringEnum(
  ReconciliationMethod
);
