/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReconciliationMethodEnum
 */
export enum ReconciliationMethodEnum {
  Automatic = 'automatic',
  Manual = 'manual',
}

/**
 * Schema for ReconciliationMethodEnum
 */
export const reconciliationMethodEnumSchema: Schema<ReconciliationMethodEnum> = stringEnum(
  ReconciliationMethodEnum
);
