/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReferenceableType1Enum
 */
export enum ReferenceableType1Enum {
  PaymentOrder = 'payment_order',
  Return = 'return',
  Reversal = 'reversal',
}

/**
 * Schema for ReferenceableType1Enum
 */
export const referenceableType1EnumSchema: Schema<ReferenceableType1Enum> = stringEnum(
  ReferenceableType1Enum
);
