/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReferenceableTypeEnum
 */
export enum ReferenceableTypeEnum {
  PaymentOrder = 'payment_order',
  Reversal = 'reversal',
  Return = 'return',
}

/**
 * Schema for ReferenceableTypeEnum
 */
export const referenceableTypeEnumSchema: Schema<ReferenceableTypeEnum> = stringEnum(
  ReferenceableTypeEnum
);
