/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReferenceableType1
 */
export enum ReferenceableType1 {
  PaymentOrder = 'payment_order',
  Return = 'return',
  Reversal = 'reversal',
}

/**
 * Schema for ReferenceableType1
 */
export const referenceableType1Schema: Schema<ReferenceableType1> = stringEnum(
  ReferenceableType1
);
