/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReturnableType1Enum
 */
export enum ReturnableType1Enum {
  IncomingPaymentDetail = 'incoming_payment_detail',
  PaperItem = 'paper_item',
  PaymentOrder = 'payment_order',
  Return = 'return',
  Reversal = 'reversal',
}

/**
 * Schema for ReturnableType1Enum
 */
export const returnableType1EnumSchema: Schema<ReturnableType1Enum> = stringEnum(
  ReturnableType1Enum
);
