/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReturnableType1
 */
export enum ReturnableType1 {
  IncomingPaymentDetail = 'incoming_payment_detail',
  PaperItem = 'paper_item',
  PaymentOrder = 'payment_order',
  Return = 'return',
  Reversal = 'reversal',
}

/**
 * Schema for ReturnableType1
 */
export const returnableType1Schema: Schema<ReturnableType1> = stringEnum(
  ReturnableType1
);
