/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Code1, code1Schema } from './code1.js';

export interface ReturnCreateRequest {
  /** The ID of the object being returned or `null`. */
  returnableId: string | null;
  /** The return code. For ACH returns, this is the required ACH return code. */
  code?: Code1 | null;
  /** An optional description of the reason for the return. This is for internal usage and will not be transmitted to the bank.” */
  reason?: string | null;
  /** If the return code is `R14` or `R15` this is the date the deceased counterparty passed away. */
  dateOfDeath?: string | null;
  /** Some returns may include additional information from the bank. In these cases, this string will be present. */
  additionalInformation?: string | null;
  /** The type of object being returned. Currently, this may only be incoming_payment_detail. */
  returnableType: string;
  additionalProperties?: Record<string, unknown>;
}

export const returnCreateRequestSchema: Schema<ReturnCreateRequest> = typedExpandoObject(
  {
    returnableId: ['returnable_id', nullable(string())],
    code: ['code', optional(nullable(code1Schema))],
    reason: ['reason', optional(nullable(string()))],
    dateOfDeath: ['date_of_death', optional(nullable(string()))],
    additionalInformation: [
      'additional_information',
      optional(nullable(string())),
    ],
    returnableType: ['returnable_type', string()],
  },
  'additionalProperties',
  optional(unknown())
);
