/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReturnableTypeEnum
 */
export enum ReturnableTypeEnum {
  IncomingPaymentDetail = 'incoming_payment_detail',
  PaperItem = 'paper_item',
  PaymentOrder = 'payment_order',
  Return = 'return',
  Reversal = 'reversal',
}

/**
 * Schema for ReturnableTypeEnum
 */
export const returnableTypeEnumSchema: Schema<ReturnableTypeEnum> = stringEnum(
  ReturnableTypeEnum
);
