/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import { Code1, code1Schema } from './code1.js';
import { Currency, currencySchema } from './currency.js';
import { CurrentReturn, currentReturnSchema } from './currentReturn.js';
import {
  PaymentReference,
  paymentReferenceSchema,
} from './paymentReference.js';
import { ReturnableType, returnableTypeSchema } from './returnableType.js';
import { Role, roleSchema } from './role.js';
import { Status4, status4Schema } from './status4.js';
import { Type6, type6Schema } from './type6.js';

export interface Return {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  /** The ID of the object being returned or `null`. */
  returnableId: string | null;
  /** The type of object being returned or `null`. */
  returnableType: ReturnableType | null;
  /** The return code. For ACH returns, this is the required ACH return code. */
  code: Code1 | null;
  /** Often the bank will provide an explanation for the return, which is a short human readable string. */
  reason: string | null;
  /** If the return code is `R14` or `R15` this is the date the deceased counterparty passed away. */
  dateOfDeath: string | null;
  /** Some returns may include additional information from the bank. In these cases, this string will be present. */
  additionalInformation: string | null;
  /** The current status of the return. */
  status: Status4;
  /** The ID of the relevant Transaction Line Item or `null`. */
  transactionLineItemId: string | null;
  /** The ID of the relevant Transaction or `null`. */
  transactionId: string | null;
  /** The ID of the relevant Internal Account. */
  internalAccountId: string | null;
  /** The type of return. Can be one of: `ach`, `ach_noc`, `au_becs`, `bacs`, `eft`, `interac`, `manual`, `paper_item`, `wire`. */
  type: Type6;
  /** Value in specified currency's smallest unit. e.g. $10 would be represented as 1000. */
  amount: number;
  /** Three-letter ISO currency code. */
  currency: Currency;
  /** If an originating return failed to be processed by the bank, a description of the failure reason will be available. */
  failureReason: string | null;
  /** The role of the return, can be `originating` or `receiving`. */
  role: Role;
  /** If the return's status is `returned`, this will include the return object's data that is returning this return. */
  currentReturn: CurrentReturn | null;
  /** An array of Payment Reference objects. */
  referenceNumbers: PaymentReference[];
  /** The ID of the ledger transaction linked to the return. */
  ledgerTransactionId: string | null;
}

export const returnSchema: Schema<Return> = lazy(() =>
  object({
    id: ['id', string()],
    object: ['object', string()],
    liveMode: ['live_mode', boolean()],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    returnableId: ['returnable_id', nullable(string())],
    returnableType: ['returnable_type', nullable(returnableTypeSchema)],
    code: ['code', nullable(code1Schema)],
    reason: ['reason', nullable(string())],
    dateOfDeath: ['date_of_death', nullable(string())],
    additionalInformation: ['additional_information', nullable(string())],
    status: ['status', status4Schema],
    transactionLineItemId: ['transaction_line_item_id', nullable(string())],
    transactionId: ['transaction_id', nullable(string())],
    internalAccountId: ['internal_account_id', nullable(string())],
    type: ['type', type6Schema],
    amount: ['amount', number()],
    currency: ['currency', currencySchema],
    failureReason: ['failure_reason', nullable(string())],
    role: ['role', roleSchema],
    currentReturn: ['current_return', nullable(currentReturnSchema)],
    referenceNumbers: ['reference_numbers', array(paymentReferenceSchema)],
    ledgerTransactionId: ['ledger_transaction_id', nullable(string())],
  })
);
