/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, dict, nullable, object, Schema, string } from '../schema.js';
import { Reason, reasonSchema } from './reason.js';
import { Status19, status19Schema } from './status19.js';

export interface Reversal {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  /** The current status of the reversal. */
  status: Status19;
  /** The ID of the relevant Payment Order. */
  paymentOrderId: string | null;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string>;
  /** The reason for the reversal. */
  reason: Reason;
}

export const reversalSchema: Schema<Reversal> = object({
  id: ['id', string()],
  object: ['object', string()],
  liveMode: ['live_mode', boolean()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  status: ['status', status19Schema],
  paymentOrderId: ['payment_order_id', nullable(string())],
  metadata: ['metadata', dict(string())],
  reason: ['reason', reasonSchema],
});
