/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  LedgerTransactionCreateRequest,
  ledgerTransactionCreateRequestSchema,
} from './ledgerTransactionCreateRequest.js';
import { Reason1, reason1Schema } from './reason1.js';

export interface ReversalCreateRequest {
  /** The reason for the reversal. Must be one of `duplicate`, `incorrect_amount`, `incorrect_receiving_account`, `date_earlier_than_intended`, `date_later_than_intended`. */
  reason: Reason1;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  ledgerTransaction?: LedgerTransactionCreateRequest;
  additionalProperties?: Record<string, unknown>;
}

export const reversalCreateRequestSchema: Schema<ReversalCreateRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        reason: ['reason', reason1Schema],
        metadata: ['metadata', optional(dict(string()))],
        ledgerTransaction: [
          'ledger_transaction',
          optional(ledgerTransactionCreateRequestSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
