/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Role
 */
export enum Role {
  Originating = 'originating',
  Receiving = 'receiving',
}

/**
 * Schema for Role
 */
export const roleSchema: Schema<Role> = stringEnum(Role);
