/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentType2, paymentType2Schema } from './paymentType2.js';
import {
  RoutingNumberType1,
  routingNumberType1Schema,
} from './routingNumberType1.js';

export interface RoutingDetail1 {
  routingNumber: string;
  routingNumberType: RoutingNumberType1;
  paymentType?: PaymentType2;
  additionalProperties?: Record<string, unknown>;
}

export const routingDetail1Schema: Schema<RoutingDetail1> = typedExpandoObject(
  {
    routingNumber: ['routing_number', string()],
    routingNumberType: ['routing_number_type', routingNumberType1Schema],
    paymentType: ['payment_type', optional(paymentType2Schema)],
  },
  'additionalProperties',
  optional(unknown())
);
