/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RoutingNumberType1
 */
export enum RoutingNumberType1 {
  Aba = 'aba',
  AuBsb = 'au_bsb',
  BrCodigo = 'br_codigo',
  CaCpa = 'ca_cpa',
  Chips = 'chips',
  Cnaps = 'cnaps',
  GbSortCode = 'gb_sort_code',
  InIfsc = 'in_ifsc',
  MyBranchCode = 'my_branch_code',
  Swift = 'swift',
}

/**
 * Schema for RoutingNumberType1
 */
export const routingNumberType1Schema: Schema<RoutingNumberType1> = stringEnum(
  RoutingNumberType1
);
