/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RoutingNumberType7Enum
 */
export enum RoutingNumberType7Enum {
  Aba = 'aba',
  AuBsb = 'au_bsb',
  CaCpa = 'ca_cpa',
  GbSortCode = 'gb_sort_code',
  InIfsc = 'in_ifsc',
  Swift = 'swift',
}

/**
 * Schema for RoutingNumberType7Enum
 */
export const routingNumberType7EnumSchema: Schema<RoutingNumberType7Enum> = stringEnum(
  RoutingNumberType7Enum
);
