/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentType1, paymentType1Schema } from './paymentType1.js';
import {
  RoutingNumberType,
  routingNumberTypeSchema,
} from './routingNumberType.js';

export interface RoutingDetailCreateRequest {
  /** The routing number of the bank. */
  routingNumber: string;
  /** One of `aba`, `swift`, `ca_cpa`, `au_bsb`, `gb_sort_code`, `in_ifsc`, `cnaps`. */
  routingNumberType: RoutingNumberType;
  /** If the routing detail is to be used for a specific payment type this field will be populated, otherwise null. */
  paymentType?: PaymentType1 | null;
  additionalProperties?: Record<string, unknown>;
}

export const routingDetailCreateRequestSchema: Schema<RoutingDetailCreateRequest> = typedExpandoObject(
  {
    routingNumber: ['routing_number', string()],
    routingNumberType: ['routing_number_type', routingNumberTypeSchema],
    paymentType: ['payment_type', optional(nullable(paymentType1Schema))],
  },
  'additionalProperties',
  optional(unknown())
);
