/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema.js';
import {
  PaymentType1Enum,
  paymentType1EnumSchema,
} from './paymentType1Enum.js';
import {
  RoutingNumberTypeEnum,
  routingNumberTypeEnumSchema,
} from './routingNumberTypeEnum.js';

export interface RoutingDetailCreateRequest {
  /** The routing number of the bank. */
  routingNumber: string;
  /** One of `aba`, `swift`, `ca_cpa`, `au_bsb`, `gb_sort_code`, `in_ifsc`, `cnaps`. */
  routingNumberType: RoutingNumberTypeEnum;
  /** If the routing detail is to be used for a specific payment type this field will be populated, otherwise null. */
  paymentType?: PaymentType1Enum | null;
}

export const routingDetailCreateRequestSchema: Schema<RoutingDetailCreateRequest> = object(
  {
    routingNumber: ['routing_number', string()],
    routingNumberType: ['routing_number_type', routingNumberTypeEnumSchema],
    paymentType: ['payment_type', optional(nullable(paymentType1EnumSchema))],
  }
);
