/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';
import { AddressRequest, addressRequestSchema } from './addressRequest.js';
import {
  RoutingNumberType7,
  routingNumberType7Schema,
} from './routingNumberType7.js';
import {
  SupportedPaymentType,
  supportedPaymentTypeSchema,
} from './supportedPaymentType.js';

export interface RoutingNumberLookupRequest {
  /** The routing number of the bank. */
  routingNumber?: string;
  /** One of `aba`, `au_bsb`, `br_codigo`, `ca_cpa`, `cnaps`, `gb_sort_code`, `in_ifsc`, `my_branch_code`, or `swift`. In sandbox mode we currently only support `aba` and `swift` with routing numbers '123456789' and 'GRINUST0XXX' respectively. */
  routingNumberType?: RoutingNumberType7;
  /** An array of payment types that are supported for this routing number. This can include `ach`, `wire`, `rtp`, `sepa`, `bacs`, `au_becs` currently. */
  supportedPaymentTypes?: SupportedPaymentType[];
  /** The name of the bank. */
  bankName?: string;
  bankAddress?: AddressRequest;
  /** An object containing key-value pairs, each with a sanctions list as the key and a boolean value representing whether the bank is on that particular sanctions list. Currently, this includes eu_con, uk_hmt, us_ofac, and un sanctions lists. */
  sanctions?: unknown;
}

export const routingNumberLookupRequestSchema: Schema<RoutingNumberLookupRequest> = lazy(
  () =>
    object({
      routingNumber: ['routing_number', optional(string())],
      routingNumberType: [
        'routing_number_type',
        optional(routingNumberType7Schema),
      ],
      supportedPaymentTypes: [
        'supported_payment_types',
        optional(array(supportedPaymentTypeSchema)),
      ],
      bankName: ['bank_name', optional(string())],
      bankAddress: ['bank_address', optional(addressRequestSchema)],
      sanctions: ['sanctions', optional(unknown())],
    })
);
