/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, nullable, object, Schema, string } from '../schema.js';
import { Address, addressSchema } from './address.js';
import { PaymentType1, paymentType1Schema } from './paymentType1.js';
import {
  RoutingNumberType,
  routingNumberTypeSchema,
} from './routingNumberType.js';

export interface RoutingDetail {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  /** The routing number of the bank. */
  routingNumber: string;
  /** One of `aba`, `swift`, `ca_cpa`, `au_bsb`, `gb_sort_code`, `in_ifsc`, `cnaps`. */
  routingNumberType: RoutingNumberType;
  /** If the routing detail is to be used for a specific payment type this field will be populated, otherwise null. */
  paymentType: PaymentType1 | null;
  /** The name of the bank. */
  bankName: string;
  bankAddress: Address | null;
}

export const routingDetailSchema: Schema<RoutingDetail> = lazy(() =>
  object({
    id: ['id', string()],
    object: ['object', string()],
    liveMode: ['live_mode', boolean()],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    discardedAt: ['discarded_at', nullable(string())],
    routingNumber: ['routing_number', string()],
    routingNumberType: ['routing_number_type', routingNumberTypeSchema],
    paymentType: ['payment_type', nullable(paymentType1Schema)],
    bankName: ['bank_name', string()],
    bankAddress: ['bank_address', nullable(addressSchema)],
  })
);
