/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status6Enum
 */
export enum Status6Enum {
  Archived = 'archived',
  Archiving = 'archiving',
  Pending = 'pending',
  Posted = 'posted',
  Processing = 'processing',
}

/**
 * Schema for Status6Enum
 */
export const status6EnumSchema: Schema<Status6Enum> = stringEnum(Status6Enum);
