/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status17
 */
export enum Status17 {
  Completed = 'completed',
  Pending = 'pending',
  Returned = 'returned',
}

/**
 * Schema for Status17
 */
export const status17Schema: Schema<Status17> = stringEnum(Status17);
