/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status22Enum
 */
export enum Status22Enum {
  Pending = 'pending',
  Posted = 'posted',
  Archived = 'archived',
}

/**
 * Schema for Status22Enum
 */
export const status22EnumSchema: Schema<Status22Enum> = stringEnum(
  Status22Enum
);
