/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status9Enum
 */
export enum Status9Enum {
  Archived = 'archived',
  Pending = 'pending',
  Posted = 'posted',
}

/**
 * Schema for Status9Enum
 */
export const status9EnumSchema: Schema<Status9Enum> = stringEnum(Status9Enum);
