/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status9
 */
export enum Status9 {
  Posted = 'posted',
  Archived = 'archived',
}

/**
 * Schema for Status9
 */
export const status9Schema: Schema<Status9> = stringEnum(Status9);
