/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status5Enum
 */
export enum Status5Enum {
  Draft = 'draft',
  Paid = 'paid',
  PaymentPending = 'payment_pending',
  Unpaid = 'unpaid',
  Voided = 'voided',
}

/**
 * Schema for Status5Enum
 */
export const status5EnumSchema: Schema<Status5Enum> = stringEnum(Status5Enum);
