/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status5
 */
export enum Status5 {
  Draft = 'draft',
  Paid = 'paid',
  PaymentPending = 'payment_pending',
  Unpaid = 'unpaid',
  Voided = 'voided',
}

/**
 * Schema for Status5
 */
export const status5Schema: Schema<Status5> = stringEnum(Status5);
