/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status4Enum
 */
export enum Status4Enum {
  Completed = 'completed',
  Failed = 'failed',
  Pending = 'pending',
  Processing = 'processing',
  Returned = 'returned',
  Sent = 'sent',
}

/**
 * Schema for Status4Enum
 */
export const status4EnumSchema: Schema<Status4Enum> = stringEnum(Status4Enum);
