/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status23
 */
export enum Status23 {
  Pending = 'pending',
  Posted = 'posted',
  Archived = 'archived',
}

/**
 * Schema for Status23
 */
export const status23Schema: Schema<Status23> = stringEnum(Status23);
