/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status19Enum
 */
export enum Status19Enum {
  Completed = 'completed',
  Failed = 'failed',
  Pending = 'pending',
  Processing = 'processing',
  Returned = 'returned',
  Sent = 'sent',
}

/**
 * Schema for Status19Enum
 */
export const status19EnumSchema: Schema<Status19Enum> = stringEnum(
  Status19Enum
);
