/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status15Enum
 */
export enum Status15Enum {
  Archived = 'archived',
  Pending = 'pending',
  Posted = 'posted',
}

/**
 * Schema for Status15Enum
 */
export const status15EnumSchema: Schema<Status15Enum> = stringEnum(
  Status15Enum
);
