/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status21
 */
export enum Status21 {
  Completed = 'completed',
  Pending = 'pending',
  Returned = 'returned',
}

/**
 * Schema for Status21
 */
export const status21Schema: Schema<Status21> = stringEnum(Status21);
