/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status24
 */
export enum Status24 {
  Approved = 'approved',
  Cancelled = 'cancelled',
  Completed = 'completed',
  Denied = 'denied',
  Failed = 'failed',
  NeedsApproval = 'needs_approval',
  Pending = 'pending',
  Processing = 'processing',
  Returned = 'returned',
  Reversed = 'reversed',
  Sent = 'sent',
}

/**
 * Schema for Status24
 */
export const status24Schema: Schema<Status24> = stringEnum(Status24);
