/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status20
 */
export enum Status20 {
  Archived = 'archived',
  Reconciled = 'reconciled',
  Unreconciled = 'unreconciled',
}

/**
 * Schema for Status20
 */
export const status20Schema: Schema<Status20> = stringEnum(Status20);
