/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status25
 */
export enum Status25 {
  Approved = 'approved',
  Cancelled = 'cancelled',
  Completed = 'completed',
  Denied = 'denied',
  Failed = 'failed',
  NeedsApproval = 'needs_approval',
  Pending = 'pending',
  Processing = 'processing',
  Returned = 'returned',
  Reversed = 'reversed',
  Sent = 'sent',
}

/**
 * Schema for Status25
 */
export const status25Schema: Schema<Status25> = stringEnum(Status25);
