/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status21Enum
 */
export enum Status21Enum {
  Completed = 'completed',
  Pending = 'pending',
  Returned = 'returned',
}

/**
 * Schema for Status21Enum
 */
export const status21EnumSchema: Schema<Status21Enum> = stringEnum(
  Status21Enum
);
