/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status8
 */
export enum Status8 {
  Pending = 'pending',
  Posted = 'posted',
}

/**
 * Schema for Status8
 */
export const status8Schema: Schema<Status8> = stringEnum(Status8);
