/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status22
 */
export enum Status22 {
  Pending = 'pending',
  Posted = 'posted',
  Archived = 'archived',
}

/**
 * Schema for Status22
 */
export const status22Schema: Schema<Status22> = stringEnum(Status22);
