/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status18
 */
export enum Status18 {
  Cancelled = 'cancelled',
  Completed = 'completed',
  Expired = 'expired',
  Pending = 'pending',
}

/**
 * Schema for Status18
 */
export const status18Schema: Schema<Status18> = stringEnum(Status18);
