/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status16
 */
export enum Status16 {
  Completed = 'completed',
  Pending = 'pending',
  Returned = 'returned',
}

/**
 * Schema for Status16
 */
export const status16Schema: Schema<Status16> = stringEnum(Status16);
