/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status12Enum
 */
export enum Status12Enum {
  Archived = 'archived',
  Pending = 'pending',
  Posted = 'posted',
}

/**
 * Schema for Status12Enum
 */
export const status12EnumSchema: Schema<Status12Enum> = stringEnum(
  Status12Enum
);
