/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status8Enum
 */
export enum Status8Enum {
  Posted = 'posted',
  Archived = 'archived',
}

/**
 * Schema for Status8Enum
 */
export const status8EnumSchema: Schema<Status8Enum> = stringEnum(Status8Enum);
