/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status15
 */
export enum Status15 {
  Archived = 'archived',
  Pending = 'pending',
  Posted = 'posted',
}

/**
 * Schema for Status15
 */
export const status15Schema: Schema<Status15> = stringEnum(Status15);
