/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status13
 */
export enum Status13 {
  Archived = 'archived',
  Pending = 'pending',
  Posted = 'posted',
}

/**
 * Schema for Status13
 */
export const status13Schema: Schema<Status13> = stringEnum(Status13);
