/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SubtypeEnum
 */
export enum SubtypeEnum {
  Enum0C = '0C',
  Enum0N = '0N',
  Enum0S = '0S',
  CCD = 'CCD',
  CIE = 'CIE',
  CTX = 'CTX',
  IAT = 'IAT',
  PPD = 'PPD',
  TEL = 'TEL',
  WEB = 'WEB',
}

/**
 * Schema for SubtypeEnum
 */
export const subtypeEnumSchema: Schema<SubtypeEnum> = stringEnum(SubtypeEnum);
