/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Subtype
 */
export enum Subtype {
  Enum0C = '0C',
  Enum0N = '0N',
  Enum0S = '0S',
  Ccd = 'CCD',
  Cie = 'CIE',
  Ctx = 'CTX',
  Iat = 'IAT',
  Ppd = 'PPD',
  Tel = 'TEL',
  Web = 'WEB',
}

/**
 * Schema for Subtype
 */
export const subtypeSchema: Schema<Subtype> = stringEnum(Subtype);
