/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import {
  TransactableTypeEnum,
  transactableTypeEnumSchema,
} from './transactableTypeEnum.js';
import { Type12Enum, type12EnumSchema } from './type12Enum.js';

export interface TransactionLineItem {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment, or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  /** Indicates whether the line item is `originating` or `receiving` (see https://www.moderntreasury.com/journal/beginners-guide-to-ach for more). */
  type: Type12Enum;
  /** If a matching object exists in Modern Treasury, the type will be populated here, otherwise `null`. */
  transactableType: TransactableTypeEnum | null;
  /** If a matching object exists in Modern Treasury, the ID will be populated here, otherwise `null`. */
  transactableId: string | null;
  /** If a matching object exists in Modern Treasury, `amount` will be populated. Value in specified currency's smallest unit (taken from parent Transaction). */
  amount: number;
  /** If no matching object is found, `description` will be a free-form text field describing the line item. This field may contain personally identifiable information (PII) and is not included in API responses by default. Learn more about changing your settings at https://docs.moderntreasury.com/reference/personally-identifiable-information. */
  description: string;
  /** The ID for the counterparty for this transaction line item. */
  counterpartyId: string;
  /** The ID of the reconciled Expected Payment, otherwise `null`. */
  expectedPaymentId: string;
}

export const transactionLineItemSchema: Schema<TransactionLineItem> = object({
  id: ['id', string()],
  object: ['object', string()],
  liveMode: ['live_mode', boolean()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  discardedAt: ['discarded_at', nullable(string())],
  type: ['type', type12EnumSchema],
  transactableType: ['transactable_type', nullable(transactableTypeEnumSchema)],
  transactableId: ['transactable_id', nullable(string())],
  amount: ['amount', number()],
  description: ['description', string()],
  counterpartyId: ['counterparty_id', string()],
  expectedPaymentId: ['expected_payment_id', string()],
});
