/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import { Currency, currencySchema } from './currency.js';
import { Type11, type11Schema } from './type11.js';
import { VendorCodeType1, vendorCodeType1Schema } from './vendorCodeType1.js';

export interface Transaction {
  id: string;
  object: string;
  /** This field will be true if this object exists in the live environment or false if it exists in the test environment. */
  liveMode: boolean;
  createdAt: string;
  updatedAt: string;
  discardedAt: string | null;
  /** Value in specified currency's smallest unit. e.g. $10 would be represented as 1000. */
  amount: number;
  /** Three-letter ISO currency code. */
  currency: Currency;
  /** Either `credit` or `debit`. */
  direction: string;
  /** The transaction detail text that often appears in on your bank statement and in your banking portal. */
  vendorDescription: string | null;
  /** When applicable, the bank-given code that determines the transaction's category. For most banks this is the BAI2/BTRS transaction code. */
  vendorCode: string | null;
  /** The type of `vendor_code` being reported. Can be one of `bai2`, `bankprov`, `bnk_dev`, `cleartouch`, `currencycloud`, `cross_river`, `dc_bank`, `dwolla`, `evolve`, `goldman_sachs`, `iso20022`, `jpmc`, `mx`, `signet`, `silvergate`, `swift`, or `us_bank`. */
  vendorCodeType: VendorCodeType1 | null;
  /** An identifier given to this transaction by the bank. */
  vendorId: string | null;
  /** The date on which the transaction occurred. */
  asOfDate: string | null;
  /** The time on which the transaction occurred. Depending on the granularity of the timestamp information received from the bank, it may be `null`. */
  asOfTime: string | null;
  /** The ID of the relevant Internal Account. */
  internalAccountId: string;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata: Record<string, string>;
  /** This field will be `true` if the transaction has posted to the account. */
  posted: boolean;
  /** An identifier given to this transaction by the bank, often `null`. */
  vendorCustomerId: string | null;
  /** This field will be `true` if a transaction is reconciled by the Modern Treasury system. This means that it has transaction line items that sum up to the transaction's amount. */
  reconciled: boolean;
  /** This field contains additional information that the bank provided about the transaction. This is structured data. Some of the data in here might overlap with what is in the `vendor_description`. For example, the OBI could be a part of the vendor description, and it would also be included in here. The attributes that are passed through the details field will vary based on your banking partner. Currently, the following keys may be in the details object: `originator_name`, `originator_to_beneficiary_information`. */
  details: Record<string, string>;
  /** The type of the transaction. Can be one of `ach`, `wire`, `check`, `rtp`, `book`, or `sen`. */
  type: Type11;
}

export const transactionSchema: Schema<Transaction> = object({
  id: ['id', string()],
  object: ['object', string()],
  liveMode: ['live_mode', boolean()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  discardedAt: ['discarded_at', nullable(string())],
  amount: ['amount', number()],
  currency: ['currency', currencySchema],
  direction: ['direction', string()],
  vendorDescription: ['vendor_description', nullable(string())],
  vendorCode: ['vendor_code', nullable(string())],
  vendorCodeType: ['vendor_code_type', nullable(vendorCodeType1Schema)],
  vendorId: ['vendor_id', nullable(string())],
  asOfDate: ['as_of_date', nullable(string())],
  asOfTime: ['as_of_time', nullable(string())],
  internalAccountId: ['internal_account_id', string()],
  metadata: ['metadata', dict(string())],
  posted: ['posted', boolean()],
  vendorCustomerId: ['vendor_customer_id', nullable(string())],
  reconciled: ['reconciled', boolean()],
  details: ['details', dict(string())],
  type: ['type', type11Schema],
});
