/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type16Enum
 */
export enum Type16Enum {
  Originating = 'originating',
  Receiving = 'receiving',
}

/**
 * Schema for Type16Enum
 */
export const type16EnumSchema: Schema<Type16Enum> = stringEnum(Type16Enum);
