/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type4
 */
export enum Type4 {
  Ach = 'ach',
  Book = 'book',
  Check = 'check',
  Eft = 'eft',
  Interac = 'interac',
  Rtp = 'rtp',
  Sepa = 'sepa',
  Signet = 'signet',
  Wire = 'wire',
}

/**
 * Schema for Type4
 */
export const type4Schema: Schema<Type4> = stringEnum(Type4);
