/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type5
 */
export enum Type5 {
  Ach = 'ach',
  AuBecs = 'au_becs',
  Bacs = 'bacs',
  Book = 'book',
  Card = 'card',
  Check = 'check',
  CrossBorder = 'cross_border',
  Eft = 'eft',
  Interac = 'interac',
  Masav = 'masav',
  Neft = 'neft',
  Provxchange = 'provxchange',
  Rtp = 'rtp',
  Sen = 'sen',
  Sepa = 'sepa',
  Signet = 'signet',
  Wire = 'wire',
}

/**
 * Schema for Type5
 */
export const type5Schema: Schema<Type5> = stringEnum(Type5);
