/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type
 */
export enum Type {
  Customer = 'customer',
  Vendor = 'vendor',
}

/**
 * Schema for Type
 */
export const typeSchema: Schema<Type> = stringEnum(Type);
