/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type10Enum
 */
export enum Type10Enum {
  Ach = 'ach',
  Book = 'book',
  Check = 'check',
  Eft = 'eft',
  Interac = 'interac',
  Rtp = 'rtp',
  Sepa = 'sepa',
  Signet = 'signet',
  Wire = 'wire',
}

/**
 * Schema for Type10Enum
 */
export const type10EnumSchema: Schema<Type10Enum> = stringEnum(Type10Enum);
