/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type16
 */
export enum Type16 {
  Originating = 'originating',
  Receiving = 'receiving',
}

/**
 * Schema for Type16
 */
export const type16Schema: Schema<Type16> = stringEnum(Type16);
