/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for VendorCodeType1
 */
export enum VendorCodeType1 {
  Bai2 = 'bai2',
  Bankprov = 'bankprov',
  BnkDev = 'bnk_dev',
  Cleartouch = 'cleartouch',
  Column = 'column',
  CrossRiver = 'cross_river',
  Currencycloud = 'currencycloud',
  DcBank = 'dc_bank',
  Dwolla = 'dwolla',
  Evolve = 'evolve',
  GoldmanSachs = 'goldman_sachs',
  Iso20022 = 'iso20022',
  Jpmc = 'jpmc',
  Mx = 'mx',
  Plaid = 'plaid',
  RspecVendor = 'rspec_vendor',
  Signet = 'signet',
  Silvergate = 'silvergate',
  Swift = 'swift',
  UsBank = 'us_bank',
}

/**
 * Schema for VendorCodeType1
 */
export const vendorCodeType1Schema: Schema<VendorCodeType1> = stringEnum(
  VendorCodeType1
);
