/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for VerificationStatus
 */
export enum VerificationStatus {
  PendingVerification = 'pending_verification',
  Unverified = 'unverified',
  Verified = 'verified',
}

/**
 * Schema for VerificationStatus
 */
export const verificationStatusSchema: Schema<VerificationStatus> = stringEnum(
  VerificationStatus
);
