/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for VerificationStatus1
 */
export enum VerificationStatus1 {
  Denied = 'denied',
  NeedsApproval = 'needs_approval',
  Unverified = 'unverified',
  Verified = 'verified',
}

/**
 * Schema for VerificationStatus1
 */
export const verificationStatus1Schema: Schema<VerificationStatus1> = stringEnum(
  VerificationStatus1
);
