/**
 * ModernTreasury
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AccountDetailCreateRequest,
  accountDetailCreateRequestSchema,
} from './accountDetailCreateRequest.js';
import {
  RoutingDetailCreateRequest,
  routingDetailCreateRequestSchema,
} from './routingDetailCreateRequest.js';

export interface VirtualAccountCreateRequest {
  /** The name of the virtual account. */
  name: string;
  /** An optional description for internal use. */
  description?: string;
  /** The ID of the counterparty that the virtual account belongs to. */
  counterpartyId?: string;
  /** The ID of the internal account that this virtual account is associated with. */
  internalAccountId: string;
  /** An array of account detail objects. */
  accountDetails?: AccountDetailCreateRequest[];
  /** An array of routing detail objects. */
  routingDetails?: RoutingDetailCreateRequest[];
  /** The ID of a debit normal ledger account. When money enters the virtual account, this ledger account will be debited. Must be accompanied by a credit_ledger_account_id if present. */
  debitLedgerAccountId?: string;
  /** The ID of a credit normal ledger account. When money leaves the virtual account, this ledger account will be credited. Must be accompanied by a debit_ledger_account_id if present. */
  creditLedgerAccountId?: string;
  /** Additional data represented as key-value pairs. Both the key and value must be strings. */
  metadata?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const virtualAccountCreateRequestSchema: Schema<VirtualAccountCreateRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        name: ['name', string()],
        description: ['description', optional(string())],
        counterpartyId: ['counterparty_id', optional(string())],
        internalAccountId: ['internal_account_id', string()],
        accountDetails: [
          'account_details',
          optional(array(accountDetailCreateRequestSchema)),
        ],
        routingDetails: [
          'routing_details',
          optional(array(routingDetailCreateRequestSchema)),
        ],
        debitLedgerAccountId: ['debit_ledger_account_id', optional(string())],
        creditLedgerAccountId: ['credit_ledger_account_id', optional(string())],
        metadata: ['metadata', optional(dict(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
