/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, nullable, object, optional, Schema, string } from '../schema.js';

export interface VirtualAccountUpdateRequest {
  name?: string | null;
  counterpartyId?: string;
  metadata?: Record<string, string>;
}

export const virtualAccountUpdateRequestSchema: Schema<VirtualAccountUpdateRequest> = object(
  {
    name: ['name', optional(nullable(string()))],
    counterpartyId: ['counterparty_id', optional(string())],
    metadata: ['metadata', optional(dict(string()))],
  }
);
