/**
 * Modern TreasuryLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface VirtualAccountUpdateRequest {
  name?: string | null;
  counterpartyId?: string;
  metadata?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const virtualAccountUpdateRequestSchema: Schema<VirtualAccountUpdateRequest> = typedExpandoObject(
  {
    name: ['name', optional(nullable(string()))],
    counterpartyId: ['counterparty_id', optional(string())],
    metadata: ['metadata', optional(dict(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
